### ISSUE TITLE
Difference in step count

### ISSUE THREAD

**Issue by mrzasa** [firasdib/Regex101#1018]
I noticed that number of steps in the main window and in the debugger differs sometimes, what is the reason for that?

Example:
https://regex101.com/r/zwP5am/1/ step count is 4
https://regex101.com/r/zwP5am/1/debugger step count for the first match is 5

In other examples the difference can be event bigger.

Btw great service, I learned a lot using it! :+1:

**Comment by firasdib** [comment]
The reason is the debugger is trying to be explicit, counting ALL the steps, being quite naive. The tester uses an optimized implementation in which shortcuts are taken. I've disabled these for the debugger to avoid this magic behavior as its unwanted while debugging. The end result should be identical.
