### ISSUE TITLE
TIME OUT!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by blogers2** [firasdib/Regex101#1026]
TIME OUT!!!!!!!!!!!!!!!!!!!!!!!!
No work more this tool, ever is always marking timeout, and is very annoying, better I'm going to another page, because this does not see that they want to put maintenance, that few desire to see the owners to fix this tool problems

**Comment by working-name** [comment]
Is the timeout notification from your browser or is it in the UI of the application? Because those are two very different things.

**Comment by JMichaelTX** [comment]
**Why have a time-out at all?**  This is not a financial web app, and there is very low risk to keep it always active.

**Comment by working-name** [comment]
I don’t know how to address your question. What I do know is that the app runs in your browser, and the timeout in the UI is an option. 

Timeouts can happen in programming languages too if your regex is stuck in a backtracking loop. So rather than waiting forever on a process to finish, timeouts are implemented. 

If the browser says timeout when connecting to the site then that’s another issue altogether. I don’t monitor the uptime of this site but I have yet to see any significant downtime.

**Comment by JMichaelTX** [comment]
> What I do know is that the app runs in your browser, and the timeout in the UI is an option.

@working-name , I am referring to the sign-in time-out imposed by the web app, not by the Browser.
After a short period of inactivity, the regex101 app will sign me out.

I don't know of any regex101 settings that control this.  I don't see any here:

![image](https://user-images.githubusercontent.com/11052885/43485584-3a5c5fe0-94d7-11e8-898c-2f03df79641b.png)

**Comment by working-name** [comment]
I realize timeout is the same word but there are 3 different kinds so far:

1. Connection timeout (a browser message) when the site is down or the client's ISP is messing up
2. Regex timeout which is the one available in options, set at 2 seconds by default. This refers to the time allowed the "regex engine" running in your browser, locally, to parse the sample text using the regex you provide.
3. Sign-in timeout as you call it, which is cookie based, and involves a third-party ID provider (google, github, whatever). 

Item number the first is the only one outside of your control. The second one is in regex101's options. The third has to do with your browser's cookie policy/settings. 

Please correct me if I'm wrong, but I believe the site only checks for the presence of the cookie and then logs you in if it's valid.

**Comment by JMichaelTX** [comment]
From my research, it appears that the cookie time-out is set BY THE WEB APP, not by the user's Browser's settings.  Please see:
[How do I prevent an auto logout session in a website?](https://www.quora.com/How-do-I-prevent-an-auto-logout-session-in-a-website)

**Comment by Zarthus** [comment]
How long is the cookie duration? if it's a month, I don't really think it's that much of a problem to make the OP (@blogers2) flip out that much.

**Comment by JMichaelTX** [comment]
> How long is the cookie duration?

Perhaps you could help us all and find out.

From my experience, I'd say << 1 hour.

It should be easy to change.  In the code where the cookie is put, you specify the timeout.

**Comment by working-name** [comment]
@JMichaelTX there usually is a keep cookies until I close my browser option. There's also don't accept third party cookies which might make login not work and you'd have to manually add an exception for github/regex101.com.

There's also addons that clear cookies on whatever timeline you want. uMatrix for example can can be used to control cookie setting on a per host basis, and so on.

**Comment by Zarthus** [comment]
I don't use regex101 as a registered user, anyone willing to use any of the
third parties for login can check the cookie expiry time in a matter of
seconds..

From past experiences it certainly wasn't an hour or less though, so if
that's what it's behaving like for you we should treat this as a bug report.

**Comment by JMichaelTX** [comment]
> I don't use regex101 as a registered user

Then your comments are not relevant to this discussion.

**Comment by JMichaelTX** [comment]
> Check the Expiration value for the cookie using your Web Dev tools. For mine, it expires 2018-08-14T18:33:59.148Z

@working-name , thanks for sharing.

Looks like about 13-14 days before expiration.  Mine was 2018-08-13T21:08:04.114Z.
Maybe it is 15 days, and it is just not updated until it expires.

This is plenty of time, although I still don't know why we need any expiration.
It must have changed since I last checked.  Before it was definitely < 1 hr.  I now have a macro which helps with this.

It is not obvious how to get the cookie expiration.  Here's the steps for others:

1. Login at regex101.com
2. In Chrome, goto View>Developer>Developer Tools
3. Click the "Application" tab
4. Expand the Cookies item in the left panel
5. Select https://regex101.com

Then you will see:

![image](https://user-images.githubusercontent.com/11052885/43494563-126385be-94f9-11e8-9a82-17ac4988672d.png)

**Comment by Zarthus** [comment]
https://github.com/firasdib/Regex101/issues/1026#issuecomment-409408454
>Then your comments are not relevant to this discussion.

Yes they are, just because I don't use regex101 as a registered user does not mean I do not have the technical expertise to discuss how the login system works. 

A cookie that never expires is a poor idea. Being logged in indefinitely is a security problem and convention across just about any website is to have an expiring token.  This is especially true if no sort of session invalidation is used.

What is possible is to re-authorize (or re-'expire') the cookie, making it seem like an infinite duration. Regardless, I think that's too much effort to implement and not a priority.

I will re-iterate: If you are experiencing sessions dropping in less than an hour, we should treat this a bug. If you don't, the feature is working as intended and at best we can discuss to raise the time to something like 30 days. (separate feature suggestions can be filed for the above)

**Comment by JMichaelTX** [comment]
> Yes they are, just because I don't use regex101 as a registered user does not mean I do not have the technical expertise to discuss how the login system works.
> 
> A cookie that never expires is a poor idea. Being logged in indefinitely is a security problem and convention across just about any website is to have an expiring token.

@Zarthus, Let me put it like this:  Your comments are not relevant to me because you are not using regexp101 like those of us who have a stake this discussion.  Please take your "expertise" elsewhere.

IAC, your statement shows your lack of expertise.  Most cookies do NOT expire.  Any cookie that routinely has a expiration > 1 day might as well not have one at all.  That's the reason banks expire their cookies within minutes.

**Comment by Zarthus** [comment]
The cookie protocol itself does not even support "non expiring cookies",
you do realize this, right?

IIRC the maximum limit is the 2038, though maybe newer specs permit longer
expiry dates.

Do not tell me to bring my expertise elsewhere and fail to properly explain
why: your statements completely dodge why there is a flaw in my reasoning,
they lack concrete examples on why more than a day of an expiry holds any
merit.

Furthermore, I have used registration in the past, and it hasn't changed
that much. Saying that because I don't use it currently means I have no
stake in this discussion is equally pointless, and further such hostility
is not appreciated if you're not willing to provide the facts you base your
arguments upon.

If there is a lack of expertise on my part I welcome being shown the
contrary, but you completely fail to do so, and instead opt for an 'I
discard your opinion and move on' strategy.

**Comment by firasdib** [comment]
Fwiw, i've increased the timeout to 30 days.

**Comment by blogers2** [comment]
TIEMOUT persists

I am going to report to google to remove this website from the search engine, because it is no longer useful, it is better that you remove your tool because the truth is trash.

Because I will report, simple because when searching in google, you are the one with the most results.

It's not my fault that you do not put adsense to pay for good severs.

**Comment by Zarthus** [comment]
Threats and hostility are also not a good way to communicate or request anything, in life or otherwise.

If you're frustrated, that's OK. But turn that frustration into constructive feedback, not meaningless banter we can't do anything with.
