### ISSUE TITLE
Default Title & Tags of New Version to Old Version

### ISSUE THREAD

**Issue by JMichaelTX** [firasdib/Regex101#1032]
### Please use the Title and Tags of the current regex snippet version when saving a new version.
99%+ of the time that is exactly what I want.  If not, then usually a small change to current title.
Yet I have no way to even see the current version title/tags.
Please implement this.  Surely it is not that hard.

It would be a huge productivity improvement.

Thanks.

**Comment by firasdib** [comment]
I wonder a better solution would be to collapse all subsequent versions under the first version instead? Then you can click to expand and see the rest, but they would "live" under the same title/tags as the first version.

Or is there a use case for putting a unique title and tags on each version? If so, I can start with your suggestion.

**Comment by TWiStErRob** [comment]
Example unique title/tags use case off the top of my head: tutorials

V1: "input without solution", tag: initial
V2: "basic cases", tag: partial
V3: "backtrack hell (times out)", tag: partial
V4: "slow solution", tag: partial
V5: "lookahead solution", tag: working
V6: "lookbehind solution", tag: working

If I were to write some, I would do as described above.

**Comment by firasdib** [comment]
@TWiStErRob So do we want to use the previous tags/title for new entries, or are we happy with the way it sits today?

You have the ability to adjust these things when you are saving/updating the regex.

**Comment by lostpebble** [comment]
Usability wise, this was completely unexpected for me as I just updated a previously saved regex for the first time.

Was completely expecting it to keep the same title and tags etc. The way I see it is that I'm working on a single "document", much like Google Sheets or Docs. I shouldn't even be sent to a dialog at all - it should just update in the background and keep the same title and everything - with maybe a small notification that pops up saying its saved or something.

If you really care about historical messages (like I see above), then you can have a dialog pop up that lets you put in a commit-style title and even tags about what this iteration represents [initial, partial, working] so that people can time travel between the steps easier.

Just that I now have a bunch of regular expressions that have no title - but I of course want to categorise them properly for later use. I didn't want to have to type in a new name every time, so this is the outcome.

There should also be an easy way to get a "clean slate", like starting a new regex document - so we don't mistakenly use the same regex document and save over it with something new.

I understand if its not possible with the current system or you have no time, just would like to give my two-cents about the usability in this area that I just noticed after actually using saved regexes for the first time today.

Thanks for the great site!

**Comment by TWiStErRob** [comment]
> There should also be an easy way to get a "clean slate", like starting a new regex document

@lostpebble have you tried clicking on the website logo?
![image](https://user-images.githubusercontent.com/2906988/51936729-c11cc980-2400-11e9-8b37-7febf90f376d.png)
it usually brings you back to the home page on the web

> So do we want to use the previous tags/title for new entries

@firasdib yes, copy it as the default; I totally agree with @lostpebble's analogy with documents, usually we're saving some version of the same "document"; my example was just a response to your query:

> is there a use case for putting a unique title and tags on each version?

but this should be the minority of the cases. even if the version differ it's usually improvements, right? so having the same title is better than clearing it

**Comment by lostpebble** [comment]
> @lostpebble have you tried clicking on the website logo?
> ![image](https://user-images.githubusercontent.com/2906988/51936729-c11cc980-2400-11e9-8b37-7febf90f376d.png)
> it usually brings you back to the home page on the web

Ah, okay cool. Wasn't very obvious but seems to do the trick! Think it could be made a little more obvious if you placed a button about the "Save & Share" menu that said "New Regex".

> but this should be the minority of the cases. even if the version differ it's usually improvements, right? so having the same title is better than clearing it

So about this, it might also be desired if each time you saved it, it didn't represent it as a whole new thing, but represents it under the same item in the "My Expressions" menu (which you can dig into the history of optionally somehow). Right now the functionality feels kinda like a "Save As" instead of "Save", because it feels like we just keep making copies of everything (I know technically we are) which quickly clogs up the "My Expressions" area.

**Comment by firasdib** [comment]
This behavior has been adjusted with the most recent updated.

**Comment by ApolloBiz** [comment]
> This behavior has been adjusted with the most recent updated.

@firasdib thanks for the update.  Unfortunately it seems that only the Title is saved and presented in the "update" dialog.  The Tags field is blank on the update.  Could you please also set the Tags field for the update to that of the prior version?

Thanks.

**Comment by firasdib** [comment]
Could you please confirm if you are saving or updating? Either way it seems we have a bug. 


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by ApolloBiz** [comment]
> Could you please confirm if you are saving or updating? Either way it seems we have a bug.

Updating.
Sorry, my bad.  I entered the tag name on the original, but did not press ENTER to save/create it.  Once I did this, then the Tag is presented on the update.

**Comment by ApolloBiz** [comment]
Thanks for the quick response.  You can re-close this issue now if you like.
