### ISSUE TITLE
\b not included in capture group backreference

### ISSUE THREAD

**Issue by danyalette** [firasdib/Regex101#1042]
## Bug Description

Backreference appears to ignore `\b`. So, `(i\b)` correctly only matches i at the end of a word, but then `\1` matches an `i` anywhere. 

### Reproduction steps

With regex `(i\b).*\1` and string `hello i am hello in` I get 
```
Match 1
--
Full match | 6-18 | `i am hello i`
Group 1. | 6-7 | `i`
```

### Expected Outcome

I expect the backreference to the capture group to account for the character `\b`. So, the regex and string above should have no match, since the pattern `i\b` in fact only occurs once in that string. 

This regex and string have the expected behaviour when using `echo "hello i am hello in" | grep -owE '(i\b).*\1'` (grep (BSD grep) 2.5.1-FreeBSD).

**Comment by working-name** [comment]
Are you using the `-w` flag intentionally?

```
-w, --word-regexp       force PATTERN to match only whole words
```

That's the only thing that makes the behavior align with your expectations. Otherwise, everything behaves the same across the board, where `\1` matches the same text as most recently matched by the 1st capturing group. 

It does not recurse capture group 1 at the current position, which would yield the behavior you expect. In other words, if you were to use `\g<1>` instead of `\1`. 

However, the limitation would then be that if capture group 1 was `([a-z]\b)`, that would match any letter at the end of a word.

**Comment by danyalette** [comment]
Quite right, thanks @Doqnach and @working-name.
