### ISSUE TITLE
Look behind behaving as lazy instead of greedy (Javascript)

### ISSUE THREAD

**Issue by JebediahSpringfield** [firasdib/Regex101#1044]
## Bug Description
Look behind regexes seem to be behaving as lazy by default instead of greedy

### Reproduction steps
regex (JavaScript): (?<=\w+).*
test string: qual1<!=value

### Expected Outcome
regex should match **<!=value**, instead it's matching **ual1<!=value**

**Comment by JebediahSpringfield** [comment]
Apparently this is not an issue, it's the standard behavior of regex where after being greedy (ie, matching everything, it back tracks until it's able to fulfill the next step of the expression.

In this case, the next step is "anything", it back tracks to the first character, fulfilling the look behind and letting the ".*" to be the greedy one.

**Comment by Ouims** [comment]
Hello, this is indeed not an issue and has nothing to do with greediness, you're just misunderstanding how the regex engine is working, here are the only two steps of what's going on here:

(?<=\w+) is tried at the beginning of the string and fail, because at the beginning of the string, there's no character on your left, so definitely no word characters. So the regex engine moves to the next position, between the 'q' and the 'u'. There, (?<=\w+) does match, because on your left, \w+ matches the 'q', therefore .* will match the rest of the line, aka "ual1<!=value".

There's absolutely no backtracking needed here. it looks like you're thinking that the .* is always applied first, and therefore has to backtrack until (?<=\w+) is true, but that's not how the engine works.
