### ISSUE TITLE
Documentation of \g{n}

### ISSUE THREAD

**Issue by pepsiman** [firasdib/Regex101#1073]
## Bug Description
The explanation for \g{n} claims "\g{+3} would be the third next capture group".
pcre documentation only mentions negative numbers: "A negative number is a relative reference".

### Reproduction steps
$ pcregrep -u "()\\g{+1}()" 
pcregrep: Error in command-line regex at offset 5: subpattern name expected

### Expected Outcome
The documentation makes no claim about positive numbers being relative references.

**Comment by Doqnach** [comment]
> \g{n}
Matches the text captured by the nth group. n can contain more than one digit, and can be positional as well; i.e. \g{-1} would be the previous capture group, \g{+3} would be the third next capture group. This may be useful in order to avoid ambiguity with octal characters, or when a literal number needs to be matched immediately after a \g{n} in the regex.

That `+` feels erroneous there indeed. I can't find a resource that states supporting this in a specific regex engine? (granted, I didn't look very long...)

**Comment by firasdib** [comment]
I'm confused. Where are you seeing `\g{+3}`? Can you attach a screenshot and a permalink so I can see the error myself?

**Comment by Doqnach** [comment]
In the quick reference explanation for `\g{n}`.

**Comment by firasdib** [comment]
Ah, that needs to be corrected then.

Thanks.

**Comment by pepsiman** [comment]
Only PCRE syntax includes \g.

**Comment by working-name** [comment]
Fixed and submitted the quickref

> Matches the text captured by the nth group. n represents the capture group number and can positionally refer to past capture groups as well; i.e. \g{-2} would be the second previous capture group, \g{3} would be the third capture group. This may be useful in order to avoid ambiguity with octal characters, or when a literal number needs to be matched immediately after a \gn in the regex.

**Comment by firasdib** [comment]
This has been fixed.

It'll be pushed live in a few weeks time.
