### ISSUE TITLE
Allow overriding versions

### ISSUE THREAD

**Issue by ciscorucinski** [firasdib/Regex101#1084]
## Feature
Allow users to override a specific version of a regex while keeping other versions the same.

### Background
I have created a regex that is rather large that does one thing; however, it has many ways to alternative solutions (paths) to do this task. After the regex got too large, it is hard to handle, so I created different "versions" where each on version is a small subset of alternative paths. This is a lot easier to manage, but it doesn't fit in the current implementation of Regex101. The issue comes when I want to update an earlier "version". I want an update to version 4 to still be version 4.

The solution under Regex101 is to create forks and to work on them all individually. However, this has its disadvantages. I will now have to remember each and every URL to navigate back and forth (or will have to view all my saved regexes first and select the right one). With my approach, I divided it so version 3 was alternative 1; version 4 was alternative 2, 3, and 4; version 5 was alternative 6 and 7; etc. **I just have to remember the version number, and this is fast and powerful** 

I know this is not the desired pathway, but the UI could highlight desired pathways. Highlight `Update Regex` and minimize the effect of `Override current version` for example.

### Other Possible Solutions
Keep the current methods as-is, but allow linking of related forked regexes to allow faster moving between related code.

## Related Questions
#809 - I am uncertain if we are talking about the same thing.

**Comment by firasdib** [comment]
Currently, you are not able to override a regex version. The idea has always been that this should be a permanent storage for each version, and you should not be able to modify it afterwards. If you need to change it, make a new entry. Kind of like how you'd do in git (although, much much simplified).

Is there a reason you could not just save them however, and then open the account page, and structure them as you see fit?

**Comment by firasdib** [comment]
While I do agree it needs work, it does feel like you're trying to use the website in a way it was not originally intended. If you do need to store this data in a specific manner, I suggest you try to find another way to do it, or save N separate regexes. That way you'll know which is which.

In the history page (and when you save a regex), you can add a title and tags to it.

There are a few issues related to the history page, which you are free to look at and add your input, so I get a better grasp of what people want :-).

**Comment by ciscorucinski** [comment]
> I suggest you try to find another way to do it, or save N separate regexes. That way you'll know which is which.

I agree, and I will probably end up forking each one, I think.

**However** I would suggest to allow user to add the option to link related regex together for easier finding. Maybe in the **Save and Share** section, add the option to **Link to other regex**. In a dialog box you ask if uni-direction link or bi-directional link.

For a quick thought to solve a short fall of this website. The idea of having related regexes in different forks is probably somewhat common.

**Comment by firasdib** [comment]
I think this is getting too complicated.

@TWiStErRob @Zarthus @working-name @OnlineCop thoughts?

**Comment by Doqnach** [comment]
isn't this something that tags solve? the relating things together?

**Comment by firasdib** [comment]
@Doqnach I'd like to think so. Even though the account page isn't perfect by any measure, I can't implement a full fledged system, as its a monumental task.

**Comment by OnlineCop** [comment]
This seems a lot more like tags, where you can tag any revision, and even move tags around to newer revisions, and then simply have a "show only tags" flag to give the feeling of folding all the mini-commits.

A concept of incremental "pointer" tags may allow a user to show off the chain of revisions in "tag" order: instead of /r/xxxyyy/[1-99] as the URL, maybe /t/xxxyyy/[1-8] could serve the same kind of purpose, but instead of the /r/... version showing some of the mini/incremental changes, the /t/... version would act as pointers back to the /r/... revisions and let incrementing from /1/xxxyyy/3 ==> /1/xxxyyy/4 that ACTUALLY resolves from /r/xxxyyy/22 ==> /r/xxxyyy/26.

This may have a side effect (good? bad?) of allowing "tag" revisions to point to non-incrementing /r/... revisions if the user wishes. Not sure how to handle two "pointer tags" from pointing to the same "actual" revisions, though.

"t/aaabbb/1" ==> "r/aaabbb/1"
"t/aaabbb/2" ==> "r/aaabbb/5"
"t/aaabbb/3" ==> "r/aaabbb/6"
"t/aaabbb/4" ==> "r/aaabbb/3"  <-- like in this case
"t/aaabbb/5" ==> "r/aaabbb/12"
"t/aaabbb/6" ==> "r/aaabbb/42"

Notice how the "t/.../#" numbers increment by 1 each time, but can point to almost arbitrary "r/.../#" revisions.

Just one idea of how something like this could work instead of actually modifying the regex itself.

(Slack/Skype/Discord have the concept of letting users modify or deleting their original message, but other users can often see the "change history" behind those revisions and see what was originally posted. IRC/Google Hangouts, on the other hand, have the concept of "once it's posted, it's out there forever; no taking it back." This would give the feel of the former behavior, while only leaving a "pristine line of revisions" for everyone but those who want to see the actual edits.)

**Comment by Zarthus** [comment]
I would "wontfix", overriding a version kind of eliminates the purpose of
versioning; consider maintaining two (one for playing around, the other for
final versions) or just bookmark the important revisions.

**Comment by TWiStErRob** [comment]
Agree with bookmarks, versions by themselves shouldn't guide any discovery.

Reading OP again, do we have an xy problem? @ciscorucinski I think you may need to look at the `x` flag and consider formatting and commenting your regex. See for example: https://regex101.com/library/gJ7pU0
Also named capture groups by themselves can help a lot, pick your language to see support: https://www.regular-expressions.info/refext.html

> overriding a version kind of eliminates the purpose of versioning

@Zarthus `git push -f`? 😉

**Comment by firasdib** [comment]
I would agree that this is a `wontfix`.
