### ISSUE TITLE
Regex Editor Shortcuts

### ISSUE THREAD

**Issue by firasdib** [firasdib/Regex101#1088]
I was thinking about adding some keyboard shortcuts to the regex editor. Please help me brainstorm what you think is needed.

Previous issue (https://github.com/firasdib/Regex101/issues/699) requested keyboard shortcut to enable/disable syntax highlight.

The new system is available in the new regex debugger.

**Comment by TWiStErRob** [comment]
regex editor:
 - [ ] prev/next group: <kbd>ctrl+alt+left/right</kbd> (see above too)
 - [ ] jump to matching parentheses/bracket/brace (<kbd>Ctrl + .</kbd>)
 - [ ] jump to start/end paren/bracket/brace (<kbd>Ctrl + [</kbd> and <kbd>Ctrl + ]</kbd>)
 - [ ] expand selection: word, quantified word, group, super group, whole thing (https://blog.jetbrains.com/dotnet/2008/01/25/extendshrink-selection/)

**Comment by OnlineCop** [comment]
Doesn't `Ctrl + [` cause many browsers to go back in history?
On Ubuntu, I've got `ctrl+alt+left/right` bound to switch desktops.

**Comment by TWiStErRob** [comment]
Good point about desktops.

Re <kbd>Ctrl + [</kbd>, similarly <kbd>Ctrl + S</kbd> would save the web page... @firasdib I guess it needs to be clear if this is going to be a full-fledged app hosted on web, or just a webpage regarding keyboard shortucts.

**Comment by TWiStErRob** [comment]
- [ ] change flavor to # (now, I'd put this as Ctrl+1..4, but that again conflicts with focus tab # in browsers)

**Comment by firasdib** [comment]
@TWiStErRob I can override certain shortcuts, but we don't want to ruin the overall experience for the user by killing their shortcuts. I'd personally dislike that.

I don't think many use <kbd>ctrl+s</kbd> to save the html of the page they're viewing, so thats an OK use case.

**Comment by akaihola** [comment]
- [ ] run unit tests (global, or at least in regex editor) – suggestion: <kbd>Ctrl + Enter</kbd>

**Comment by firasdib** [comment]
@akaihola Not a bad idea, but how should feedback be reported back? Should this only be allowed if the unit test pane is showing?

**Comment by akaihola** [comment]
@firasdib yes, I was missing a quick mouseless way to fire up the unit tests while the unit test pane is visible.

**Comment by OnlineCop** [comment]
Switching between MATCH, SUBSTITUTION, and UNIT TESTS with a keyboard shortcut would be useful. Mouse-less (keyboard only) navigation seems like it would benefit many of the developers who visit the site.

I can see this being handled efficiently in one of two ways, so open discussions/feedback would be useful.

A hotkey to navigate quickly to the left panel (and expand it if it's hidden due to size requirements/preferences) could allow the Save&Share, Flavor, Function and Tools area to be selectable, and from there, arrow keys and ENTER might allow the sub-groups to receive focus. That would only require 1 new "custom" keybind.

Or, use individual hotkeys for each option. We'd have to be more careful about these, since each of the OSes tend to bind completely different key combinations for the same functions (an example being Linux -- and some Mac -- defaults for `Ctrl Alt Left/Right Arrow` to switch desktops).

We would need hotkeys for:
* Function->Match
* Function->Substitution
* Function->Unit Tests
* Tools->Code Generator
* Tools->Regex Debugger
* [Possibly] Flavor->[one of the flavors], or just `Flavor` and then use Arrow Keys + `Enter` to select one
* [Possibly] Save&Share->[one of the options] (if we want *full* keyboard navigation)

I'd personally favor the former: a single hotkey to select the left panel subgroups, then Arrow+Enter navigation, since users don't tend to change flavors often.

If the `Function->[options...]` is switched between frequently (switching back and forth between Unit Tests and Match/Substitution), then that might warrant its own custom hotkeys.

Discuss.

**Comment by firasdib** [comment]
The first option will be the most complicated to implement, since I completely rely on the browser to navigate tabindex for me. If we want to start using custom navigation using arrows, things get complicated fast.

I think using specific key combos for the site is fine, as long as they don't interfere with the general key bindings of the browser.

On Linux, Firefox switches tabs with `Alt+N`, while Chromium allows switching with both `Ctrl+N` and `Alt+n`. I'd say `Ctrl+N` would be a good candidate for a series of key bindings. I'd have to double check Windows and OSX first.

Since this is an SPA, I feel more confident overriding standard key bindings (such as bookmark, `Ctrl+D`), as you're less likely to be using those.

I agree with the list of candidates for hotkeys.

**Comment by firasdib** [comment]
One question: Where should we document all these shortcuts? Should probably be a button with a modal somewhere.

**Comment by working-name** [comment]
I like the `?` keybinding. Would placing `? shortcuts` at the top right, after what's new be ok?

**Comment by firasdib** [comment]
I dont think it fits there. There are already many links, and these shortscuts only apply to the regex editor. 


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by firasdib** [comment]
One problem with the `?` binding is that it won't work when you're focused in a text input, which is what you're going to be 99% of the time.

**Comment by firasdib** [comment]
This has been merged, will be pushed live in a couple of days.

`?` opens the help modal

![image](https://user-images.githubusercontent.com/1335165/108095411-1ecfed00-7080-11eb-8e39-b5eeae10f715.png)
