### ISSUE TITLE
Quiz: Report solution as invalid / automatically delete invalid solutions

### ISSUE THREAD

**Issue by Timvde** [firasdib/Regex101#1096]
It's rather annoying to always ask you to remove our invalid solutions :P It would be nice if we could get a button to report the current solution as invalid, which would:

- give a pop-up to let us enter a counterexample, which is sent to you
- remove our solution from the database
- if possible (but optional), automatically reinstate our previous solution

**Comment by firasdib** [comment]
Great idea. I will try to get around to it.

**Comment by Davidebyzero** [comment]
Even better will be is what is currently planned, to automatically go through the full list of solutions when appropriate, check which ones are valid, and delete the ones that are not.

Ideally this would email people who have had some of their solution(s) deleted, so that they could come back and fix their solution(s), but that is apparently not possible.

I would then like to see the full list of how many solutions of each length in each task were deleted due to being invalid.

**Comment by Timvde** [comment]
That would still involve asking a quiz admin to add a test and invalidate my solution, then later get back and enter my old valid solution. If I can invalidate my own solution, I can do it all at once. It would also give an option to report invalid solutions without reporting a bug on Github and either potentially spoiling a part of the solution, or having to be really vague about the regex you tried.
