### ISSUE TITLE
Your expression caused an unhandled error

### ISSUE THREAD

**Issue by andreea93m** [firasdib/Regex101#1111]
## Bug Description
![2019-01-24_16-26-49](https://user-images.githubusercontent.com/5804990/51689373-d5bf2300-1ff6-11e9-9cca-68d44012723f.png)
Instead of seeing the results of running my regular expression on my input, I see `Your expression caused an unhandled error` and the number `-21`.

### Reproduction steps
Go to regex101.com and paste the following regular expression in the input field: `<p[^>]*>(?:(?!(<\/p>)).){400,}<\/p>`.
Then paste the following text into the other text input field.
[input_text.txt](https://github.com/firasdib/Regex101/files/2792398/input_text.txt)

### Expected Outcome
I expect a match to be highlighted, or to see that there are no matches, if that is the case, but not an error and a negative number.

### Browser
Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)

### OS
Windows 10

**Comment by Doqnach** [comment]
https://www.pcre.org/original/doc/html/pcreapi.html

PCRE_ERROR_RECURSIONLIMIT (-21)
The internal recursion limit, as specified by the match_limit_recursion field in a pcre_extra structure (or defaulted) was reached. See the description above.

I agree those error messages could be made a bit more user friendly (for the less initiated among us), but your problem is in the regex itself reaching recursion limit. The engine itself is working as intended.

**Comment by firasdib** [comment]
Fixed. Will push soon.

**Comment by Doqnach** [comment]
which part did you fix? the display of the error or was there some cause afterall?

**Comment by firasdib** [comment]
Just added that error explanation for that code. There’s very many


Vänliga hälsningar / Best regards,

Firas Dib
