### ISSUE TITLE
IPv6 task 

### ISSUE THREAD

**Issue by Timvde** [firasdib/Regex101#1115]
## Quiz Bug

DO NOT POST QUIZ SOLUTIONS!

### Task
Task 27: Shorten IPv6

### Bug Description
The tests don't check for multiple groups of zero hextets. It allows a solution that transforms `a:0:0:0:b:0:0:0:c` to `a::b::c` instead of `a::b:0:0:0:c` or `a:0:0:0:b::c`

### Reproduction steps
Write a regex that doesn't take into account multiple groups of zero hextets. Watch it pass.

### Expected Outcome
Well, I actually prefer the current behaviour, but Lindrian asked me to create an issue so we could discuss. The quiz should still mainly be a learning experience. I actually already don't really the IPv6 task, because it forces you to do two separate things in one regex. Adding this requirement would make it unreasonably hard.

### Browser
Waterfox 56.2.6

### OS
Arch Linux, versionless ;)

**Comment by Davidebyzero** [comment]
> The tests don't check for multiple groups of zero hextets. It allows a solution that transforms `a:0:0:0:b:0:0:0:c` to `a::b:0:0:0:c`.

Don't you mean it allows a solution that transforms `a:0:0:0:b:0:0:0:c` to `a::b::c`? What you said would be the correct thing for a solution to do.

**Comment by Timvde** [comment]
> > The tests don't check for multiple groups of zero hextets. It allows a solution that transforms `a:0:0:0:b:0:0:0:c` to `a::b:0:0:0:c`.
> 
> Don't you mean it allows a solution that transforms `a:0:0:0:b:0:0:0:c` to `a::b::c`? What you said would be the correct thing for a solution to do.

Correct, that was a bad copy-paste on my part. Edited the original post to avoid confusion.

**Comment by Davidebyzero** [comment]
What bugs me about this is that I put a lot of time and effort into making a solution that only collapses the first group of zero hextets it finds, because the problem description didn't say not to do that and I thought it was the only way for it to be valid. And then when I saw jaytea had a much, much better score than I did, I was mystified, as it seemed like magic.

Now I understand how that was possible. His solution doesn't do everything that mine does.

I would be okay if this if the problem description specifically said that the test cases do not include any IPv6 addresses with more than one group of zero hextets. So please either fix the description, or add test cases with more than one group of zero hextets.

**Comment by Davidebyzero** [comment]
Fixed by editing the task's description. Not yet live.
