### ISSUE TITLE
Code generator c# lower and upper

### ISSUE THREAD

**Issue by BoatWar** [firasdib/Regex101#1134]
## Bug Description
@"(?<part>[[:upper:]][[:lower:]]{0,})" not work in c#!

### Browser
Include browser name and version

### OS
Include OS name and version

**Comment by Doqnach** [comment]
The code generator only takes the regex you wrote and puts it into a template. It does not validate the working of the regex for you in the language the template is for.
Since C# is not (yet) a flavour for the website, it unfortunately can't check for you if the syntax is okay.

Also, the notation of `(?...)` is [invalid syntax](https://regex101.com/r/RKtZ9I/1). I'm not sure what you are trying to do, but if you want help on the regex itself, please join the regex chat (from the left menu) if you are looking for help.

**Comment by firasdib** [comment]
Yeah unfortunately I don't convert between flavors this way, its too complex.
