### ISSUE TITLE
PCRE flavor is reporting the / (slash) char as a reserved one when it is not

### ISSUE THREAD

**Issue by emruiz81** [firasdib/Regex101#1147]
## Bug Description
The PCRE validator is claiming that the / (slash) char needs to be escaped with backslash \. But this isn't a special char, at least not in PCRE.

### Reproduction steps
Just write any regular expression using the PCRE flavor and an unnescaped slash char, like: .*/.*

### Expected Outcome
It should be allowed as a literal char

### Browser
Google chrome, latest versions

### OS
Windows 10

**Comment by working-name** [comment]
Did you mean this message?
`/ An unescaped delimiter must be escaped with a backslash (\)`

If so, as the message says, when `/` is also the delimiter it needs to be escaped. Otherwise the regex engine won't know what the start and end of your regex is. 

As an alternative you can include the delimiter in a character class `[/]`.

If you choose a different delimiter, `/` will no longer need escaping, but the new delimiter will.

While there's a chance I may be wrong, I have not come across any regex implementation that's okay with the delimiter being used inside the regular expression without escaping.

**Comment by TWiStErRob** [comment]
@working-name not all languages have delimiters. For example in Java you write regex into normal strings. In Kotlin it's either normal string or raw string (`"""`) but there's no magical delimiter (`/`) like in JavaScript or Groovy.

**Comment by firasdib** [comment]
This is how it works in Perl. You're right that PCRE does not care, as you can compile the string in any way you see fit, but this is the standard I've chosen to follow.

It doesn't hurt to escape the delimiter, and you can always change to another non-conflicting one in the UI if you want.

**Comment by TWiStErRob** [comment]
@firasdib wouldn't it be possible to choose a "no delimiter" delimiter? Since PCRE is universal, and the site is not focused on Perl.
