### ISSUE TITLE
Settings: save preferred language for code generator

### ISSUE THREAD

**Issue by SimpelMe** [firasdib/Regex101#1156]
## Feature
I'd like to save my preferred code generator language in the settings.

Regards, Simpel

**Comment by Doqnach** [comment]
You can set it if you login.

**Comment by SimpelMe** [comment]
I am logged in. On OS X and WIN7, on IE, FF, Safari or Chrome. I don't see a possibility to set it. And it always shows PHP no matter what I selected last time.

**Comment by Doqnach** [comment]
![image](https://user-images.githubusercontent.com/25537191/58081706-cff8d900-7bb5-11e9-9413-8acb99024664.png)

**Comment by Zarthus** [comment]
it would make more sense to default to the language of the flavour you're using, no?

**Comment by SimpelMe** [comment]
I don't exactly get what you mean. AutoIt uses PCRE flavor. But I want to define my default language at code generator page to AutoIt. I don't care where exactly I can set it. I thought settings would be the best place.

**Comment by firasdib** [comment]
The code generator will automatically select the flavor of the selected language.

I could add an option to select the preferred language in the settings, but this does feel like something very few people would use.

**Comment by TWiStErRob** [comment]
@firasdib If we if ignore that rarely I mess around in JavaScript, the default languages on the site don't make sense to me. I only use regex in Java, Kotlin, C#, Sublime Text and IntelliJ IDEA. Yet I still use your site for developing the regex. If I use the code generator, I always need to change the language because the defaults just don't make sense.

Would remembering the last selected language be a good compromise?

**Comment by Ouims** [comment]
An option in setting has been implemented for a preferred/default code gen language, this issue can be closed.
