### ISSUE TITLE
Commentable explanation

### ISSUE THREAD

**Issue by thisismydesign** [firasdib/Regex101#1173]
## Feature

I would like to be able to document what certain parts of the regex are doing.

I noticed many currently use the `TEST STRING` tab to do this and the formatting and breakdown of the regex are arbitrary. Instead, I'd prefer a feature where this can be added in an organized manner, such as adding comments to specific parts of the parsed regex in the `EXPLANATION` tab. This feature could also be used to determine how much to expand the regex explanation by default (i.e. it should be expanded the least much to be able to show all comments).

I think an `EXPLANATION` tab enriched this way would serve to understand the regexes more easily.

**Comment by firasdib** [comment]
You can use `# comments` with the `x` flag, or `(?#comments)`.

**Comment by thisismydesign** [comment]
@firasdib This doesn't cover my use case. The placement of these is still arbitrary. Also neither the `x` flag nor `(?#)` is supported for all flavors (e.g. JS supports none of these).

**Comment by Doqnach** [comment]
I think a feature like this would also bring big design challenges...

Like how does it relate to the versions of a regex? Can anyone place and/or edit a comment, and will it produce a new version (most likely with how it currently works) or replace the current one? Then if you make a typo in the documentation (which is more likely to happen than a typo in the regex since that is validated to work most of the time before you save it), you create a new version every time... or risk people altering your documentation later by replacing it if it would stick to the same version.

I'm not sure if this is something the tool should support. My feeling is that you should comment your code with a link to regex101 if you want to, and explain it in code (comments), rather than on regex101.

**Comment by thisismydesign** [comment]
> I think a feature like this would also bring big design challenges... Like how does it relate to the versions of a regex?

The proposed workaround by @firasdib and other features already posed this challenge and they are all version controlled. For example, unit tests have free-text descriptions which are version controlled too. If you make a typo there you have to fix it in a new version.

Other than the fact that this takes effort, I don't see why this wouldn't be a nice-to-have feature, also considering that currently other parts of the system (comments, test string) are being "abused" to support this.

> I'm not sure if this is something the tool should support. My feeling is that you should comment your code with a link to regex101 if you want to, and explain it in code (comments), rather than on regex101.

Your service is often used to pass around standalone regexes, without such context. I also think that'd be redudant and by the same token you could argue against having the feature of unit tests.

> I think that if this discussion were to be revisited, it would be better suited to do that in #832

This feature request is different than #832:
> Have you tried comments in regex? https://regex101.com/r/hpu2Fu/1

> I'm familiar with, but not all flavours support it (as far as I know). And I'm thinking more paragraph-form stuff to document the context of the regex. Why it was written, upstream validation requirements, etc.

I'm thinking more regex docs in an organized manner.
