### ISSUE TITLE
Task #9: Non-cyrllic TLD

### ISSUE THREAD

**Issue by USSX-Hares** [firasdib/Regex101#1184]
### Task
Task 9: Match an E-Mail (Simplified) (optional)

### Bug Description
Hint 22/56 states that TLD should be only [a-z].
However, there is a `.рф` TLD for Russian Federation, with an ASCII representation of `xn--p1ai`
See [wiki](https://en.wikipedia.org/wiki/.%D1%80%D1%84) for details.

### Reproduction steps
Use `\w{2,6}` in TLD part of regexp

### Browser
Chrome 75

### OS
Windows 7 x64

**Comment by Dinoguy1000** [comment]
`.рф` was one of the first four registered internationalized ccTLDs (the other three being in Arabic), but there have been a number of others since, including other Cyrillic ccTLDs and ccTLDs in Arabic, a number of Brahmic scripts, Chinese, and a handful of others, and there are currently also three proposed ccTLDs, one each using Greek, Hebrew, and Japanese.

I think handling these would distract from the intent of the task and make an already quite difficult problem much harder for very little benefit, especially since there are [a lot of other cases](https://codefool.tumblr.com/post/15288874550/list-of-valid-and-invalid-email-addresses) the problem doesn't touch on either. You could of course argue that if someone was actually validating emails, they'd also have to catch these cases, but validating emails is a [famously](https://www.regular-expressions.info/email.html) [hard](https://haacked.com/archive/2007/08/21/i-knew-how-to-validate-an-email-address-until-i.aspx/) [and](https://stackoverflow.com/a/201378) [complex](https://medium.com/hackernoon/the-100-correct-way-to-validate-email-addresses-7c4818f24643) [task](https://emailregex.com/) and the usual recommendation is to ~~use a standard function or library instead of attempting your own solution~~ forego validating near-entirely and just send your users an activation email.

**Comment by firasdib** [comment]
I agree with @Dinoguy1000 here. The purpose of the task is not to create the perfect regex, but rather to help perfect your skills.
