### ISSUE TITLE
bug with a pattern `\/[^]\/`

### ISSUE THREAD

**Issue by perymimon** [firasdib/Regex101#1201]
## Bug Description
I find the pattern /\/[^]\// that should not match anything or the pattern   `\/[^*]\/` that should match /s/ and not /*/ mark in the `test string` and `substitution` as match from / --> \n --> / 

### Reproduction steps
regex: /\/[^*].*\//
text 
/*kj*/
/s*kj*/
exmaple: (https://regex101.com/r/nR4UhE/1)

### Expected Outcome
mark /*kj*/

### Browser
Include browser name and version
chrome 76
### OS
Include OS name and version
windows 10

**Comment by working-name** [comment]
It's very hard for me to follow your post, so I apologize ahead of time if my post seems off.

`[^]` means "match anything but nothing", which effectively will match absolutely everything.

`\/[^*]\/` does indeed match "/s/", and it does not match "/*/". It would never match "/kj/" because that's made up of 4 characters, not 3 as the regex you wrote expects.

Your example link seems to be an entirely new regex, not quite sure what to make of that.

It is my strong recommendation that you should join #regex on Freenode to further discuss this in realtime.
