### ISSUE TITLE
Regex simplifier tool

### ISSUE THREAD

**Issue by kkava** [firasdib/Regex101#1206]
## Feature
Would be great to have a simplify button to generate an equivalent regex that is optimized for speed, and maybe separately for readability.
See for example https://www.reddit.com/r/regex/comments/9wnsnt/simplifying_ridiculous_regex/

**Comment by firasdib** [comment]
The idea is good, but its very hard to know what you're actually optimizing for.

I guess if you would insert enough input data with positive and negative entries, you would generate something. But I don't think this is an easy task at all.

**Comment by radekivan** [comment]
https://github.com/firasdib/Regex101.wiki.git

**Comment by asasine** [comment]
Since regular expressions are conceptually a form of [deterministic finite automaton](https://en.wikipedia.org/wiki/Deterministic_finite_automaton), you could compile them [DFA minimization](https://en.wikipedia.org/wiki/DFA_minimization) algorithms. This seems like something the language interpreter or compiler should perform.

**Comment by firasdib** [comment]
@asasine That doesn't hold true for modern regex engines, unfortunately. PCRE (and modern engines) include a lot of complex features, such as backreferences, subroutines, recursion, etc.

**Comment by verdy-p** [comment]
I agree, not all regexps can be converted to DFA. In general regexps are parsed using only NFA (i.e. using a variable number of active states instead of just one). Trying to convert these NFA to DFA swith a single integer has a combinatorial complexity and the result DFA from a modest NFA could easily not fit at all in memory (a small reggexp of a few bytes could then generate a DFA which requires petabytes or even much more).

Consider the case of regexp with repetitions and bounded counts like "A{1,1000000}B" which is trivoal to parse with a NFA using only 3 active states and a small integer counter, but impossible to realize with a DFA using a single integer state whose value would be large enough to store a little more than 1000000 bits, yes more than 1 million bits only for that state and we's still not stored the graph containing the billions of billions of... of billions of activable nodes (it would require a computer larger than the number of atoms in the universe, so this is simply impossible !).

Regexps containing backreferences, subroutines, recursions are also NOT representable at all with a simple DFA, as you cannot predict the number of deterministic states. In fact, in addition to the set of states in the NFA graph of nodes (active nodes can be represented in a bitset, with one bit per activable node prior to traversing it, but counters are additional integer variables you need to store in that object), the regexp engine collect this set of state variables into an object that is pushed on a stack (with an implementation-dependant maximum depth).

When you compile a regexp actually it parses the syntax and builds a representation of the NFA using memory that is proportional to the length of the regexp, plus the memory for representing each object containining states in that graph (including counters), plus the memory required by the stack and the allocation of a new state object for each allowed depth in the stack.

The compilation of character classes is also not necessarily as a a small bitset if the set of characters is much larger than ASCII, for exampel if it refers to the Unicode character set and this is even worse when the character classes are refering to Unicode character properties (because these set of properties is evoluting with the encoding of new characters with their character properties, and most characters properties may also change over time for the same encoded characters; for this reason, character classes are implemented as collection of static and dynamic rules, the dynamic rules being evaluated by a call to a functional hook and not representable only with static data only: the genreated "data" structure will contain pointers to functions!)

----

However there are limited possibilities:
* to reduce some parts of regexps in branches that do not contain any counter (but that may contain alternations, including character classes)
* to factorize common leading parts of alternate branches that are comon in these parts, provided they do not contain capture groups, and then eliminate the remaining empty parts at end of alternate branches.

This is quite complex to do and there's in fact no real benefit in performance and the reduction in the regexp size is quite small.

I some cases, the factorization of leading branches may create a regexp that is actually longer: remember that such factorization must not create new capture groups, so you would have to use non-capturing groups for the leading part! As well, working with character classes to detect common alternate branches would require rewriting them (you'd have to compute and represeent new character classes with substracted characters).

Finally once you've detected common leading branches, it's not so easy to merge the trailing parts when they are supposed to be equivalent syntaxically, because they can also contain capture groups that you cannot merge without affecting their numbering (so this would affect other features like recursion, subroutines, or the final result of the matches that expect to contain some values in specific capture groupe numbers.

**Comment by kkava** [comment]
A universal simplification tool isn't needed. Just something simple that shows you basic 'tricks' that a pro would apply. The simplifier could be as simple as a regex itself!

**Comment by firasdib** [comment]
@kkava If it can't be generalized, it's just a search and replace, which is meaningless. The basic "tricks" a pro would apply aren't as easy to fit into code, as they are for a pro to come up with :).

I'll close this for now, even though it would be a great feature, as I just don't see how this would be feasible.

**Comment by verdy-p** [comment]
I do agree. However there are some minor use cases: if the regexp is not just "optimized" alone, but in association with its usage (you can know which capture groups are needed by a substitution pattern, or the application knows which capture groups it needs for searches), then all unnecessary capture groups can be removed: add the "?:" flag after their opening parenthese. Then the regexp can be compiled in a faster engine.
But then a regexp engine that has a compile() API could be given a hint about the capture groups needed, could then compile the regexp, find common branches in a more optimal NFA, from which a new regexp can be regenerated.
So basically, this is something that can only be done safely with a true implementation of a regexp compiler (that will fully parse it).

On the opposite, reformatting a complex regexp with a "pretty print" that will indent it (using the /x format) is possible with little efforts ands as well you can very simply reduce the /x presentation to remove unprotected whitespaces/newlines and comments: this is very easy to do before (or after) parentheses (with their attached "?*" flags), or pipes "|" for alternates, and quantifiers ("?", "+", "*", "{m,n}", "{m,}", "{,n}" with their optional optional greedyness flag "?" or "*" ).

The regexp editor can include helpers for:
- adding or removing capturing groups (ie. the pairs of parentheses, changing them to non capturing groups is easy, just add "?:" after the leading "(").
- sorting alternates delimtied by "|" by their content, to detect duplicates
- merging parts of alternates that have common prefixes or suffixes (using non-capuring groups for containing the other non-common parts in a set of reduced alternates)
- changing sets of one-character alternates (that have the identical quantifiers) into character classes between "[]" (with the same quantifier)
- sorting characters or subclasses in a character class to detect and remove duplicates, or compressing them using ranges.

All these optimizations are safe provided they do not change the set of capturing groups and their ordering (if they are implicitly ordered and not named).
