### ISSUE TITLE
Task 7: Test 137 fails with used capture group

### ISSUE THREAD

**Issue by Obbi89** [firasdib/Regex101#1209]
## Quiz Bug

First of. Cool idea with the quiz. It's useful to freshen up on some regex from time to time. And those exercises help on trying to flex some old brain cells :)

### Task
Task 7, Test 137

### Bug Description

Either the test case failure message is misleading or I found a bug when using recursive patterns. The error says that I should omit non used capture groups. I'm using it however.

### Reproduction steps

Without giving too much info about a possible solution:

Example: `(NUMBER)(?:\.(?1)){3}`.
Hint: I tried matching a number first (0-255); followed by a repetition of dot and the first capture group (valid number) three times.

### Expected Outcome
Should either tell me that no capture groups are allowed or accept a solution.

### Browser
Chrome 76

### OS
Linux (Debian Bullseye)

**Comment by Davidebyzero** [comment]
The failure message you got:

**Test 132/134:** Don't create backreferences when you don't need them. If you need to group, use `(?:regex)`; it's the same as `(regex)` but it doesn't create a backreference.

is not at all misleading. Note that in order to be able to use your subroutine call of `(?1)`, you had to use a capturing group `(NUMBER)`. This creates a backreference in your example. To get around this you'll have to do something like `(?(DEFINE)(NUMBER))(?1)(?:\.(?1)){3}`. (To avoid giving too much info, I have left this incomplete, and ungolfed. It is possible to do something like this with much fewer characters.)

**Comment by firasdib** [comment]
The first couple of tasks will discourage any and all use of capturing groups, which basically means you cannot use `(group)` but have to use `(?:group)`

**Comment by Obbi89** [comment]
@Davidebyzero yeah I got that. I parsed the error message differently though.
I thought it meant, that I am not using the backreference and thereof should omit it.
But It actually says that I should not use backreferences unless I have to, which has a completely different meaning.
Thanks for clarifying.
I'm not sure how the (?(DEFINE)(<pattern>))(?1) is different though. Since (?1) still references the first defined group in the regex :confused:

**Comment by extempl** [comment]
I'd say this is not fair, as you forcing to use features not valid in other languages, so it is should be called PCRE regexp quiz.

**Comment by Davidebyzero** [comment]
`(?1)` is already a PCRE feature.

And you don't *have* to use `(?(DEFINE)(NUMBER))` to prevent a backreference from being created. Some other ways are `(NUMBER){0}` or `(?>|(NUMBER))` (doesn't get evaluated, just like DEFINE), or `(?!(?!(NUMBER)))` (gets evaluated once).

**Comment by extempl** [comment]
>  `(NUMBER){0}`, `(?>|(NUMBER))`, `(?!(?!(NUMBER)))`

I do not see these constructions in the reference. What are they for? Could you point me to the according place in docs, please? 
Quick look through sections on https://www.php.net/manual/en/reference.pcre.pattern.syntax.php also without any luck. And they are not searchable.

> `(?1)` is already a PCRE feature.

Well, that is what I was talking about as well. As quiz can't be passed with other non-pcre syntax because of tests.

**Comment by extempl** [comment]
> `(NUMBER){0}`

My bad, got it.

**Comment by Obbi89** [comment]
> And you don't _have_ to use `(?(DEFINE)(NUMBER))` to prevent a backreference from being created. Some other ways are `(NUMBER){0}` or `(?>|(NUMBER))` 

Okay but is it really best practice to `zero times match` a sub pattern and then reference that sub pattern somewhere later?
I'm not sure on the performance impact of that, cause I'm no expert. But regarding readability this is even worse than regex in general :laughing:
