### ISSUE TITLE
`(a)(?(1)\1|B)` does not match _aB_

### ISSUE THREAD

**Issue by Welgriv** [firasdib/Regex101#1223]
The regular expression:

`(a)(?(1)\1|B)`

does not match the expression:

_aB_

Has it should. egrep do.

screen: 

![regexp101 bug](https://user-images.githubusercontent.com/22592156/67693185-9799ca00-f9a1-11e9-9607-941591a01063.PNG)

**Comment by firasdib** [comment]
If you add anchors it will work. 

you’re evaluating the expression against the full document, not each line. 


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by Welgriv** [comment]
Like this:

`^(a)(?(1)\1|B)$`

?

I thought about it just after post my question but it does not seems to work better:

https://regex101.com/r/DQlvJ7/1/

(link better than screenshot...)

Thanks for your interest anyway.

**Comment by Doqnach** [comment]
Looks to me like intended behaviour when looking at the Explanation pane:

```
If Clause (?(1)\1|B)
   - Evaluate the condition below and proceed accordingly
      (1) checks whether the 1st capturing group matched when it was last attempted
   - If condition is met, match the following regex \1
      \1 matches the same text as most recently matched by the 1st capturing group
   - Else match the following regex B
      B matches the character B literally (case sensitive)
```

Since the first group '(a)' matched, it will never check 'B' since the `if` states it should only check `\1`.

What is your expected behaviour?

Sounds more like: https://regex101.com/r/DQlvJ7/2

**Comment by Welgriv** [comment]
I expect that the first `(a)` of the regexp match the first _a_ of the test sequence, then the test is on **the second** symbol of the test sequence, in this case _B_. Since _B_ is not the first group because it is not _a_  then the regexp should try to match _B_ and succeed.
Do I get something wrong ?

**Comment by firasdib** [comment]
@Doqnach is correct.

**Comment by Doqnach** [comment]
@Welgriv yes you got something wrong, and easy to see using the regex debugger on the website.

The `if` tests the first `(1)` group, which is `(a)`. If that group matched it will try to match `\1` next, which it then expects to be `a`, but in reality it is `B`. If the group matched it will never check the alternate value.
Because the first group is `(a)`, the string *has* to start with an 'a'. Because of that the `if` will always be true and the alternate branch won't ever trigger.

Drop by the IRC channel if you want help on crafting a regex for your use-case, because this one seems to be wrong.
