### ISSUE TITLE
Following suggested links abandons changes since last save

### ISSUE THREAD

**Issue by tjt263** [firasdib/Regex101#1228]
## Bug Description
Following links suggested by the web-app (e.g., https://www.regular-expressions.info/catastrophic.html) doesn't open the new page in a new tab. That's not necessarily a problem, but when you return to the previous page, you will notice all changes since the previous save (if any) will be lost.

### Reproduction steps
1. Enter a regex syntax error or similar problem (e.g. catastrophic backtracking). 
2. Follow the hyperlink (observe there's no new tab).
3. Return to regex101.com (i.e., click <kbd>back</kbd> in your browser).

### Expected Outcome
 - Opening a new tab would step around the problem altogether ( I suggest this option).
 - Otherwise the page should maintain it's unsaved state somehow (i.e., changes should persist between saves (using cookies perhaps?), I don't really know – I'm not a web developer).

### Browser
Chrome, Safari, (I assume it's universal).

### OS
macOS, (I assume it's universal).

**Comment by firasdib** [comment]
This is intentional. The website will not store any data, unless you ask it to. If you have unsaved data, you will be warned. It does not open new tabs as some people do not like that behavior, instead, the user can select how they want to open the link.

I recommend you enable the warning in the settings (if you have disabled it) to avoid this in the future.
