### ISSUE TITLE
(?<=\G.{2})(?!$) do not match correctly

### ISSUE THREAD

**Issue by liuxilu** [firasdib/Regex101#1236]
## Bug Description
(?<=\G.{2})(?!$) do not match correctly

### Reproduction steps
1. select PCRE flavor
1. input regex `(?<=\G.{2})(?!$)`
1. input some chars, such as dfgdftrbrtdtr
1. chars are splited as 2,3,3,3
### Expected Outcome
chars should be splited as 2,2,2,2

### Browser
not releated

### OS
not releated

**Comment by firasdib** [comment]
Works for me. 

Got a permalink?

**Comment by Davidebyzero** [comment]
This should probably get the "upstream" label, because it's an oddity in the way PCRE handles zero-width matches. regex101 is behaving correctly, in following standard PCRE behavior. You can confirm this by using pcretest:

```
$ pcretest
PCRE version 8.43 2019-02-23

  re> /(?<=(\G.{2}))(?!$)/g
data> dfgdftrbrtdtr
 0:
 1: df
 0:
 1: df
 0:
 1: rb
 0:
 1: td
data>
```

When PCRE finds a zero-length match in /g mode, it starts the next attempted match one character later. It must do this, because if it didn't, it would fall into an infinite loop, matching at the same position over and over again. Your test shows that it does this by setting the end-of-match pointer to one character later, thus influencing the result of `\G` as well as the start of the next attempted match. In theory this could be fixed, but it's not going to be done with PCRE.

PCRE2 behaves like you want:

```
$ pcre2test
PCRE2 version 10.33 2019-04-16
  re> /(?<=(\G.{2}))(?!$)/g
data> dfgdftrbrtdtr
 0:
 1: df
 0:
 1: gd
 0:
 1: ft
 0:
 1: rb
 0:
 1: rt
 0:
 1: dt
data> 
```

**Comment by liuxilu** [comment]
Well, PCRE's bug. In fact, this regex is used for .Net to split string into two-char sub-strings, so it must match zero-width char, or the matched char will be deleted.

**Comment by Davidebyzero** [comment]
Okay, then does `..\K(?!$)` work the way you want? https://regex101.com/r/MNLo1V/1

**Comment by liuxilu** [comment]
It does work, and it's briefer!

**Comment by Doqnach** [comment]
Please note that the website does not (yet) natively support a .NET regex engine. So when choosing anything but the ECMAScript flavour will have the regex run through a PCRE based engine.

**Comment by firasdib** [comment]
That only applies to python!

**Comment by Doqnach** [comment]
> That only applies to python!

Oops, forgot there was also Golang :-P

**Comment by firasdib** [comment]
If anyone would like to report this to PCRE and track it, feel free. Likely it won't get changed in PCRE1.
