### ISSUE TITLE
s flag not mentionned in ECMA mode

### ISSUE THREAD

**Issue by RolandGautier** [firasdib/Regex101#1242]
## Bug Description
s flag is not present in ECMA mode

### Browser
Include browser name and version
FIREFOX 70.0

### OS
Include OS name and version
Ubuntu 18.04 (linux)

**Comment by Doqnach** [comment]
The existence of the flag is feature detected based on your browser (since the regex will run in the browser, so the browser needs to support the features you intend to use).

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/dotAll for browsers supporting this flag. As you can see, Firefox is not among them.

**Comment by RolandGautier** [comment]
That's funny, because Mozilla Development Network clearly present the 's' flag as effective part  of regular expressions ;
[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions](url)

**Comment by Doqnach** [comment]
That page event explicitly mentions:

> s | Allows . to match newline characters. (Added in ES2018, not yet supported in Firefox)

**Comment by firasdib** [comment]
The flag is automatically feature detected and added/removed depending on that.
