### ISSUE TITLE
Lookaround assertions match patterns not characters

### ISSUE THREAD

**Issue by paul1149** [firasdib/Regex101#1325]
## Bug Description
Hi guys. Fantastic site. One small quibble. I just was working on a pattern which contained a compound negative lookbehind:

```https:\/\/.*(?<!code|news\.)gab\.com.*```

The Regex101 Explanation reads:
```
Negative Lookbehind (?<!code\.|news\.)
Assert that the Regex below does not match
1st Alternative code\.
code matches the characters code literally (case sensitive)
\. matches the character . literally (case sensitive)
2nd Alternative news\.
news matches the characters news literally (case sensitive)
\. matches the character . literally (case sensitive)
```

Shouldn't that say, "code matches the PATTERN code literally (case sensitive)"? Because it does not match individual characters as if the characters were within brackets, it matches the entire pattern or nothing.

Thanks.

**Comment by working-name** [comment]
I'm not sure I understand the distinction between `pattern code` and `characters code`. A pattern can match characters, and a pattern can be made of characters too, not just tokens. 

In my mind it's a semantics issue, but that's because I don't get it. Would you mind rephrasing or expanding on that distinction and maybe why this is a bug?

**Comment by paul1149** [comment]
I wish I knew enough about regex to write it out succinctly. When I first saw in the Explanation that the lookbehind would match characters, I thought of a set of eligible characters, as in a bracket. For instance, (?<=red) would look for any r, e, or d, as opposed to the string "red".

I see that the Quick Reference has it as I would expect:

```Ensures that the given pattern would not match and end at the current position in the expression. The pattern must have a fixed width. Does not consume characters. ```

When I see the word 'pattern' I know that the regex engine will judge the characters as a string, not as individual characters.

Does that make sense?

**Comment by working-name** [comment]
I can't say I get it fully, and being concise isn't an issue. I still think it's a semantics issue.

- **match** = what the engine does
- **pattern** = your string which is a set of commands for the engine
- **string** = any number of characters or symbols to be interpreted either as regex commands or the target of a regex pattern ( which is a set of commands, which is made of characters, which could also be referred to as string ). It makes 0 difference what you call them as long as you understand which role they play.
- **character class** = commands to match certain symbols (=characters) or ranges thereof, with an implicit alternation (this ...OR... that) between each command

When you write a regex like this, `/abc{4}d/g` the engine will read that as individual commands:
```js
a: match 1 'a', then
b: match 1 'b', then
c: match a 'c'
{4}: exactly 4 times (of the previous token, which is 'c'), then
d: match 1 'd'
g: it's a global flag, it instructs the regex engine not to stop after the first match
```

As you can see the regex engine doesn't see strings, it sees commands. Some are special characters or metacharacters which mean something; for example `\Z` means end of string/input rather than `match a '\' then match a 'Z'`.

Now, contrasting with the character class which you reference: `/[bacd]{4}/g`

```js
[bacd]: match an 'a', a 'b', a 'c', or a 'd'
{4}: exactly 4 times (of the previous token)
g: don't stop after the first match
```

As you can see the character class doesn't care about the order of symbols it contains because it is essentially the same as `(?:a|b|c|d)` or `(?:d|b|a|c)` or however else you want to arrange the items.

Your negative lookbehind is just another command telling the engine to peek back and make sure `code` doesn't match at the current location. It peeks only, it doesn't consume/match.

**Comment by paul1149** [comment]
Ok. I appreciate your attention, and don't want to belabor this, so I will close the issue. Thanks and be well.
