### ISSUE TITLE
Basic error?

### ISSUE THREAD

**Issue by jhgarrison** [firasdib/Regex101#1341]
https://regex101.com/r/JV8iKe/1

Regex /host.*/ matches "host" but not "host2"?

**Comment by jhgarrison** [comment]
non-obvious testing UI

**Comment by Doqnach** [comment]
Your problem is that the testing UI was not obvious enough in its usage?

What specific problems did you face? What do you feel could use improving?

**Comment by iago-lito** [comment]
@Doqnach Well, I actually also had troubles understanding what was wrong in this very situation. I think a simple last line in the `Explanation` or `Match Information` pane(s) would be enough. Something like:

    No further match is searched because the `g` flag is not set.

**Comment by Doqnach** [comment]
The default for the website is `/.../gm` flags, so a person would have to explicitly disable global search which you would think is intentional. Such a message would then most of the time be less useful. Right now the explanation pane shows information about everything that **is** there, and not really about any possible omissions. I'm not sure if in general it would improve the UX. Could maybe be better suited in the match information pane, but again 9/10 times not having the `g` flag is intentional since you have to explicitly turn it off.
