### ISSUE TITLE
python substitutions

### ISSUE THREAD

**Issue by MalikRumi** [firasdib/Regex101#1348]
https://regex101.com/r/3VfA6h/1/

How is the substitution feature supposed to work? I am not sure I am doing it right. My substitution comes up as literal, not as regex metacharacters. I tried several variations with the same result. I looked in the wiki and found nothing. I also tried logging into IRC but the 'start' button would not go live for me. Thanks for your assistance.

**Comment by iago-lito** [comment]
@MalikRumi You need to find help about [python regex](https://docs.python.org/3.8/howto/regex.html) specifically I think.

First, you have been confused with the `r'substitution_string'` pattern. This is python language. It's the way to have the `substitution_string` litterally, with no escape code parsed inside. In regex101, you just have to write the `substitution_string` directly without the `r''` stuff.

Then, I think you need to `(capture)` the part of the matched pattern you want to be kept. Use parentheses in the match pattern for that, like `([^.])\s</p>` instead of `[^.]\s</p>`. And then just use `\1` as a substitution string to replace the matched bits with the capture group. See [this example](https://regex101.com/r/3VfA6h/2) which is maybe closer from what you expect.

Finally, it seems like you are attempting to parse html with regexes, with is [famously known](https://stackoverflow.com/a/1732454) as a bad thing to do. You will likely get better results with less effort with a [html parser](https://docs.python.org/3/library/html.parser.html) instead ;)

**Comment by working-name** [comment]
@MalikRumi IRC interface is freenode's, not regex101.com's. It is supposed to take the generated nickname and randomize some digits at the end but it's failing right now. Will look into it. Until then, please type in a nickname you wish to use and then start will be enabled.

We generally like to use IRC for help with regex creation/understanding/issues because it is live, and there are many volunteers ready to help at all hours of the day (almost). If you still require help with this please connect to freenode with your favorite irc client and join #regex.

Closing this for now, please reopen if necessary.
