### ISSUE TITLE
Can support Sublime keyboard mapping for CodeMirror-editor?

### ISSUE THREAD

**Issue by dnknn** [firasdib/Regex101#1354]
Can support ⌨ Sublime keyboard mapping for CodeMirror-editor❓	👇

- ## https://codemirror.net/demo/sublime.html
- #### https://github.com/codemirror/CodeMirror

----
Why ?  because it's hotkey  is very versatile and powerful , It is the same shortcut key in many places,, 
E.g `Tampermonkey` &emsp;  [Stylus](https://github.com/openstyles/stylus/)&emsp;.etc

![Sublime](https://user-images.githubusercontent.com/10995302/87325219-bfe34c00-c563-11ea-9919-c2bc5afea4bf.gif)

☝The gif demo above is a Chrome-extension of `Stylus`

Most useful ⌨ | to
------------ | -------------
Ctrl+Shift+D | duplicate line
Ctrl+Shift+⇅ | exchange line
Ctrl+D |  Highlight matching & multi-point selection
Alt+F3 |  Match all highlights
Ctrl+J  |  Join line
Ctrl+Enter↵ |  insert Line After
Ctrl+Shift+Enter↵ |  insert Line before
F2/Ctrl+F2 |  bookmarks
.etc | .etc

---

![0713225616](https://user-images.githubusercontent.com/10995302/87319333-13519c00-c55c-11ea-8f19-501af8a4a067.png)

**Comment by Doqnach** [comment]
I feel that if such a thing were to be added, it would be optional. Something you can maybe pick in settings? This because not everyone is used to the same mapping.

For me for instance it would be more logical to have CTRL/CMD+D be duplicate line since my primary editor is of the JetBrains family and that is their default mapping.

Question is also if to limit this to certain input fields or not.

**Comment by dnknn** [comment]
@Doqnach 
> For me for instance it would be more logical to have CTRL/CMD+D be duplicate line since my primary editor is of the JetBrains family and that is their default mapping.

![Sublime](https://user-images.githubusercontent.com/10995302/87325460-0cc72280-c564-11ea-9749-26542e6d4392.gif)
But the current default Ctrl+D is to delete line.

> I feel that if such a thing were to be added, it would be optional. 

They all use CodeMirror, and then the same optional keyboard mapping👇 Can refer to them👇
![0714000222](https://user-images.githubusercontent.com/10995302/87326453-519f8900-c565-11ea-89f5-6d17927833ea.png)

![Stylus](https://user-images.githubusercontent.com/10995302/87326724-b4912000-c565-11ea-9750-f15de315ca72.gif)

**Comment by Doqnach** [comment]
RIght now the only key-binds that are supported is whatever the default is of CodeMirror (see https://github.com/codemirror/CodeMirror/blob/f5bf57b39816f0e6524a1b7d0212e9f26135ba08/src/input/keymap.js#L6).

I can see the appeal of supporting different keymaps. I would even go as far as defaulting to actually no default outside of the keybinds that are app specific (like the CTRL/CMD+S for save, and the ones in the debugger for instance). This because there is nothing in the UI to direct you to the keybinds and I somewhat doubt they are in high use under most users (since there is no indication of them existing in the first place).

Then via settings (if you have an account and are logged in) you can choose a keymap, from ones that are shipped by (and officially supported by) CodeMirror, so that would be the ones from https://github.com/codemirror/CodeMirror/tree/master/keymap. I wouldn't be that keen on supporting keymaps outside of those from CodeMirror itself, simply because of the added maintenance and compatibility issues that can arise when doing updates etc.

**Comment by dnknn** [comment]
Knowledge of code lang such as JavaScript is required to implement it with Tampermonkey. It's complicated, don’t how to do it.
It doesn't matter, I just said it happened.
