### ISSUE TITLE
Incorrect substitution

### ISSUE THREAD

**Issue by Piterden** [firasdib/Regex101#1387]
## Bug Description
I found unnecessary duplication in the result of substitution.

### Reproduction steps
https://regex101.com/r/Nh29o8/2
There shouldn't been duplication of zeros!

### Browser
Chrome 85.0.4183.83 (Official Build) (64-bit)
Firefox 79.0 (64-bit)

### OS
Manjaro

**Comment by working-name** [comment]
Hi Piterden, 

That's actually correct behavior because that's what you instructed the engine to do. Replace every match with 0 and contents of group 1. Some of your matches are blank which is why it seems that zeroes are duplicated when in fact that's not consistent throughout if you look closely. It only happens on lines 1 and 4.

Zero length matches are created by your lookahead. If you erase `|(^\d{1,3}$)` and switch to debugger you can see how that happens. 

If you have further questions about how the regex engine works please [drop by on IRC](https://webchat.freenode.net/#regex?nick=re101-zebra-?) to have a live conversation with our volunteers. 

Thank you!

**Comment by Piterden** [comment]
Thanx for explanation. I had missed these things.
