### ISSUE TITLE
Recursive pattern regex  

### ISSUE THREAD

**Issue by parthiban982** [firasdib/Regex101#1404]
Recursive pattern in regex for square bracket and curly braces. not match. choose the python language.
for example:
{((?>[^{}]+|(?R))*)}

**Comment by OnlineCop** [comment]
The `re` package in Python does not support recursion. The `regex` package does. The regex101.com site implements the `re` package. If you switch to PCRE flavor, you'll notice that the pattern does match recursively.

Also, don't forget to escape the `{` and `}` characters, since those are used as quantifiers for atoms: `.{1,3}`.
