### ISSUE TITLE
Provide List like in Regexr

### ISSUE THREAD

**Issue by muizidn** [firasdib/Regex101#1410]
## Feature

List in Regexr is very handy tool to generate bulk of new strings based on matched values from current regex session. Regexr doesn't support replacing case with \U\E so I choose Regex101 to do the hardjob.

**Comment by Doqnach** [comment]
https://regexr.com/ vs https://regex101.com/r/5EPryy/1

At regex101, at the "MATCH INFORMATION" pane there is an export button. It might not give you the flexibility of what Regexr's "List" feature offers (being able to somewhat customise the output), but does this provide the actual functionality you are looking for maybe?

**Comment by firasdib** [comment]
Can someone give me a short explanation of that the list feature does? What are the benefits of it, etc.

**Comment by Doqnach** [comment]
It seems to be more or less a customisable "match information" export.

**Comment by firasdib** [comment]
Ah, I see. I can understand how that could be useful, perhaps it could be integrated into the toolset in the sidebar. Does not seem like a very complicated feature.

**Comment by Doqnach** [comment]
Since we chanced the panes to menu items in the sidebar, I do think this indeed fits under the "FUNCTION" header.

UX-wise it would be like the Substitution view, but then showing only match information (with that "<Fullmatch>\n" as default).

Both this "Export/list" pane and the "Substitution" pane can maybe benefit of some (i) tooltip showing what replace-tokens are possible?

**Comment by Doqnach** [comment]
Something like the suggestions from #1361 could maybe also be implemented under such a feature. This can limit the effect of the syntax to only here, which limits any problems with the syntax?

**Comment by firasdib** [comment]
This will be pushed live soon.
