### ISSUE TITLE
Regex substitution differs from my local python

### ISSUE THREAD

**Issue by PhilipSiEn** [firasdib/Regex101#1411]
## Bug Description
Regex substitution differs from my local python

### Reproduction steps
On https://regex101.com/: 
- Select python + substitution
- Regex: ([&%$#_{}~^\\]) 
- Flags: gm
- Substitution: \\\g<1>

Test String: ${TESTVAR}

Output: ${TESTVAR\}

Local Python script:
```
import re
print(re.sub(r"([&%$#_{}~^\\])", r"\\\g<1>", "${TESTVAR}"))
```

### Expected Outcome
Output: \\$\\{TESTVAR\\}

### Browser
Firefox 78.4.1esr (64-bit)

### OS
Python 3.7.3 on debian buster.

**Comment by Doqnach** [comment]
I'm not sure what the expected outcome is since that heading is not filled in the above bug report, and there is also no link to a testcase on regex101.

@PhilipSiEn please confirm if the following is what you are trying to do, and if this is correct or not: https://regex101.com/r/MnZhEP/1

Things I've noticed is that in the regex string the `]` is escaped with a `\` but in your code example the `\` itself is escaped (if I use the above regex of `([&%$#_{}~^\])` it will give an error for an incomplete group structure)? Also the number of escape `\` in the substitution is different.

**Comment by PhilipSiEn** [comment]
> I'm not sure what the expected outcome is since that heading is not filled in the above bug report, 

I corrected that.

> and there is also no link to a testcase on regex101.

Sorry, I was using this tool for the first time and was not aware that there is such a function.

> @PhilipSiEn please confirm if the following is what you are trying to do, and if this is correct or not: https://regex101.com/r/MnZhEP/1

Exactly :)

> Things I've noticed is that in the regex string the ] is escaped with a \ but in your code example the \ itself is escaped (if I use the above regex of ([&%$#_{}~^\]) it will give an error for an incomplete group structure)? Also the number of escape \ in the substitution is different.

I am not able to reproduce the behavior any more. Sorry for the confusion.

**Comment by Doqnach** [comment]
no problem, happy to help! If in the future you have any questions about a regex you could also drop by the chat (either via the website or directly on IRC).
