### ISSUE TITLE
The page stalls randomly

### ISSUE THREAD

**Issue by scrutinizer11** [firasdib/Regex101#1438]
## Bug Description

Quick Reference pane: Clicking on the "Close" icon to close the entry and return to the list makes the whole page temporarily non-responsive. **It's random but persistent**.

### Reproduction steps

1.  Expand the "Quick Reference" item of the accordion on the bottom right.
2. Open any list item directly or by searching.
3. Close the pane.

### Expected Outcome

The entry closes instantly without the page being frozen.

### Browser
Safari 13.1.2

### OS
macOS Mojave 10.14.6

**Comment by working-name** [comment]
Any way you could try to reproduce it with the console open? `Safari -> Preferences -> Advanced -> [x] Show develop menu in menu bar` then right click on the regex101.com page, select `Inspector` and hit the `Console` tab. Now attempt to recreate the bug and take a screenshot: `CMD + SHIFT + 4` and draw a rectangle around Safari.

I have Safari 13.1.3 (on 10.15.7) and I've been clicking like a rabid dog - no freezing yet.

Other things to consider:
- got addons? Disable them
- create a new user, start safari on that user and try to reproduce
- do you happen to run other CPU/RAM intensive programs at the same time? Maybe Chrome with 45 tabs? Try to reproduce the bug with nothing but Safari running
- is your mac's drive derping? trying to die? Taking a smacking because of mighty apple's mds/mdworker?

**Comment by firasdib** [comment]
Please follow the steps and instructions outlined by @working-name -- this will greatly help me debug the issue!

**Comment by working-name** [comment]
This has gone stale, will reopen if the report is confirmed.
