### ISSUE TITLE
backslash in pattern for PHP

### ISSUE THREAD

**Issue by GuusOuwerkerk** [firasdib/Regex101#1440]
## Bug Description
PHP requires four backslashes to represent a single backslash in the string that is being searched
(I am using PHP 7.4.7)

### Reproduction steps
RegEx pattern: /<b>Fatal error<\/b>:\s*(.+?(?= in C:)) in C:\\xampp\\htdocs\\Project\\([^:]+):(\d+)/
works when tested using "https://regex101.com" but not when used in my PHP code.
There the pattern has to be /<b>Fatal error<\/b>:\s*(.+?(?= in C:)) in C:\\\\xampp\\\\htdocs\\\\Project\\([^:]+):(\d+)/

### Browser
Chrome 87.0.4280.88
IE 2004 (OS Build 19041.685)
Edge 87.0.664.66 (Official build) (64-bit)

### OS
Microsoft Windows 10 Home 10.0.19041

**Comment by OnlineCop** [comment]
This is exactly what the Code Generator on the left side of the page is for. It escapes each of those \ characters, turning `\\` into `\\\\` that you could then copy-and-paste into your PHP code.

**Comment by Doqnach** [comment]
This is the example given in the OP:  https://regex101.com/r/mVftzQ/1
This is not a valid regex on regex101.com because it is missing crucial escape-backslashes.

A valid version would be: https://regex101.com/r/mVftzQ/2
This also results in the correct escapes in the code generator: https://regex101.com/r/mVftzQ/2/codegen?language=php
