### ISSUE TITLE
Preview and/or Explanation of Substitution Tokens

### ISSUE THREAD

**Issue by minig0d** [firasdib/Regex101#1468]
## Feature Preview and/or Explanation of Substitution Tokens
This suggestion was kind of but not really touched on by #840 a few years ago but a bit different.  Two separate ideas with the same goal so hopefully y'all will like one of them.

Idea1:
While the substitution pane is active, having a pane just like the "match information" one, that was substitution information, that would preview the values of some of the more common tokens (maybe not all for performance reasons). This is already KIND of what's contained in the match information section, although that section is geared towards previewing the matches for tuning the matching. This would be intended to ease composing of replacements.  As you start getting into complex nested groups, it can be a bit confusing to figure out which numbered token is which and such.

For performance it could probably truncated at a certain length if needed and maybe limited to just $&, $`, $', $1-3 or 5, and maybe the first few named ones if there are any? etc...
![image](https://user-images.githubusercontent.com/54046315/104828302-6834de80-582d-11eb-8d24-88ed1b069dcb.png)

Idea2:
Same goal as the above, except while the substitution pane is open, add the token information to the Explanation box at the top.  Ex where the explanation says 1st Capturing Group ([a-z ]*) can add $1 (but not show it while substitution pane isn't open will reduce the clutter).  While the $1 token is a bit more obvious, having a visual indication of $` and $' are a little less obvious.

Thoughts?

**Comment by firasdib** [comment]
I'd say match into does that, just not in the token-terms for that specific flavor.

I'm not convinced regarding the second idea either, I think it might just get cluttered.

**Comment by Ouims** [comment]
Agreed with @firasdib, what you're suggesting is not so great for solving the proposed problem.

>  This would be intended to ease composing of replacements. As you start getting into complex nested groups, it can be a bit confusing to figure out which numbered token is which and such.

This is not a great argument as counting the parenthesis to know which capture number you need is quite part of the regex feature itself, use named capturing group and reference them by name in substitution if you find numbering hard, that's why named group were added.

Also agree that your second idea is not going to fit well with the current design, adding new panes is probably not really an option, adding the infos to the explanation panel would be very ugly and non intuitive, I believe the substitution field being explained via tooltip by hovering is extremely meaningful and sufficient.

If anything, what's a problem to me is that stuff like $~ and $& are not in quickref and undocumented!

**Comment by minig0d** [comment]
Sorry, I really suck at trying to explain these kinds of things. Perhaps the thing I envision is even bigger than what this issue was originally opened as.  I guess to backtrack, conceptually you can say that the site, is a great swiss army knife for RegEx.  If you know which tool you're looking for it will get the job done.  Where I see a gap is, in when you approach the site in trying to solve common problems, there may be some opportunity to help users tackle the problems directly. i.e. lessen the amount of effort it takes to walk away with a solution).  I am in no way suggesting dumbing things down (removing functions) more so tweaking the layout into a UI that is less general and more more purpose/function-driven.  So I'll leave you with some food for thought and you're welcome to close the issue.

I'm sure there are a billion different use cases for the site, but the majority would probably fall under:
1) I want to match a pattern to or ensure I don't match it (ex confirm the url I'm on has a domain name ending in .edu)
2) I want to extract a piece of data (ex. a domain name from a url)
3) I have some type of input data that I want to manipulate (ex. strip/replace/append query parameters in a url  or replace tabs with spaces if they are leading, or otherwise want to look a different way, etc. )

If you pretend to be an end user... pull up regex101.com in your browser, and try a simple task of each of the above, do you see anything that would make that specific task easier?  (clutter that's not relevant to the task that can be hidden, placement altered, etc).  I think you'll find #3 has the most opportunity :)

Random example: some of the above is accomplished under unit tests, but how do users even know what unit tests are?  Is there a way to transition/guide the user between the tasks?  And if you're working on more ad-hoc tasks like this, should there be something between formal unit testing and the "home screen"? Or maybe a way to make the unit testing a little quicker to configure?  Because (in my mind) if we are talking about a formal project then we are probably talking about having testing frameworks etc. and probably not so much in need of the site for that use case.

Just food for thought :)

**Comment by Ouims** [comment]
I think the design of the website is very much what it is meant to be, you can collapse almost everything and resize stuff, I'm not sure what it is specifically that would help with the tasks, that you're talking about, I like the UI for all the things I'm doing on the website, I don't use unit test because the same test can be achieved with workarounds in a muuuuuch quicker. But there have been suggestions about unit test getting some love, as @firasdib like to put it, so maybe unit tests specifically can be improved.

**Comment by firasdib** [comment]
Yeah, I think keeping hover explanations for the substitution area is sufficient.
