### ISSUE TITLE
Switch shortcuts for save/update

### ISSUE THREAD

**Issue by Timvde** [firasdib/Regex101#1478]
I believe that the default action when working on an existing regex should be update instead of save. It allows people to easily go through different versions of a regex.

I'd like to see two changes to support this:
- Switch the default shortcut so that Ctrl-S updates, while Ctrl-Shift-S stores the regex under a new URL. This also feels more consistent with "Save / Save As" semantics in most other programs. Ctrl-S can of course save as a new URL if there is no previous version.
- Change the order such that "Update Regex" is above "Save Regex".

**Comment by firasdib** [comment]
This was an intentional change, since the majority of people did not utilize this feature to its intended purpose. Nine times out of ten, people just wanted to save a regex and accidentally saved it as another version of a previous persons regex. I constantly get asked to remove revisions as they accidentally saved them ontop of someone elses.

However, there might be some merit in reworking this behavior. Perhaps if its your entry, you default to update?

**Comment by Ouims** [comment]
This change is good but people who consider themselves 'aware' would still like to have the old design.

I think that what Timvde suggested is great but we just need it as an option in setting, the option would change the behavior of control + (shift)? + S and the order in UI.

**Comment by Timvde** [comment]
> This was an intentional change, since the majority of people did not utilize this feature to its intended purpose.

I don't even remember: was there only "Update" before, without a "Save as" option? Or have it always been two buttons? I do think splitting them is a good thing, I just don't like the new default.

> I constantly get asked to remove revisions as they accidentally saved them ontop of someone elses.

It isn't really harmful, though? Why do people need them removed?

I think the main use case is still us helping people in #regex, and in that context it is way more helpful to have them all bundled behind one identifier, so we can loop over them. It's also useful to see which responses are answers to your question. I know this is still possible, and if you feel strongly that the new behaviour is better, I'll probably adapt over time to just use ctrl-shift-s, but it feels counter-intuitive to me. Or you could, as Ouims suggests, add a setting.

**Comment by Ouims** [comment]
Before you already had the functionnality, there was a save/update and fork button, though forking used to default to use the original various values (pattern, input, etc) and you had to use shift to fork using your current content, I believe it now has changed to fork the current content by default when you fork.

It's a good change in theory, in practice it seems to bother a lot of people.

as far as forking, forking the current content is definitely the way to go since you now use it as a saving button.

I keep forking people's url instead of updating because of the position of the button in the UI, that's definitely a bother, I'd rather have my UI back as far as those two buttons are concerned. This is one of the most used features on the website, to save and update, so this should be handled carefuly.

@Timvde the default need to be forking to prevent people from updating the url of someone else with sensitive data, this is kind of non negociable I think, that's why an option seems best. \#regex can set the option.

**Comment by IsaacG** [comment]
Changing the label from "Save" to "Fork" might make the Update vs Fork behavior stand out more clearly.

**Comment by don922** [comment]
I would like the ability to update an existing version without creating a new version. There are times you just want to save what you are working on so you don't lose it without creating a new version.

**Comment by working-name** [comment]
@don922 functionality is still there, just click UPDATE rather than save.

**Comment by don922** [comment]
> @don922 functionality is still there, just click UPDATE rather than save.

When I click Update Regex it creates a new version.

**Comment by working-name** [comment]
@don922 double check in other browsers, disable addons in current, if you can still reproduce the issue open a separate github issue please (and provide browser/os version to try to reproduce it ourselves).

**Comment by don922** [comment]
**@working-name** will do. It does it on Chrome and the new MS Edge. I'll open a bug report on github.

**Comment by don922** [comment]
Unless I'm missing it there is also no way to create a new regex session. If I am looking at a regex or finished editing and I want to start a new blank session how to you do it?

**Comment by don922** [comment]
I believe there should be 3 options but it got shot down. I thought I'd add it here maybe to generate some more discussion. 

I think there should be the following save/update options:

1. Save new regex (ctrl-s)
2. Update existing version (ctrl-u)
3. Create new version (ctrl-c)

The keyboard sequences are just suggestions.
