### ISSUE TITLE
Trying to detect a line or no line at all

### ISSUE THREAD

**Issue by TechnoRage** [firasdib/Regex101#1543]
Hi,

I am trying to detect a line or no line at all, so, both below mentioned A & B options should be accepted:

A:
aaa server radius dynamic-author
 client 10.216.9.240 server-key ********

B:
aaa server radius dynamic-author
 client 10.216.2.31 server-key ********
 client 10.216.9.240 server-key ********

I already tried:
\b(?:|client 10.216.9.240 server-key 7 .*)?\b
(|client 10.216.9.240 server-key 7 .*)

So I am looking to accept the absence of a line also.

Thanks in advance! Tom

**Comment by working-name** [comment]
Hi @TechnoRage!

Please click the `Live Help` button to connect with us via IRC. Have your regex101.com link ready, and give a brief explanation as to what regex should and should not do with the test string.
![live-help](https://user-images.githubusercontent.com/16505052/112654613-f200b980-8e25-11eb-94d4-fc60db56584e.jpg)


Github is more for issues with the site rather than regex help. But there are plenty of volunteers on IRC to help with any specific regex you need.
