### ISSUE TITLE
Debugger is not run on a test case

### ISSUE THREAD

**Issue by David263** [firasdib/Regex101#1569]
## Bug Description
Seems to be no way to see any debugging information about a test case failure. The test case is the pattern \[\[DEF ([-_$0-9A-Za-z]+)/([*.+-]*)(\((.*?)\))?[:]?\r?\n(.*?) DEF\]\]\r?\n* run against the string [[DEF test/.]]
[[SET A=abc SET]]
%A% DEF]]

### Reproduction steps
Enter pattern. Now try to paste test case. Nowhere in the test case box is it possible to paste. An error message says "There are no unit tests, click to add some." When I click, it says an empty string does not match. I click in the "Insert test string" field and paste the above test case. I get a correct failure notice, but I can discover no way to get any detailed information about why it failed to match. I tried clicking in different places, but nothing happens. The "Regex Debugger" link is disabled for some unknown reason.

### Expected Outcome
Should tell me why the test case didn't match in detail.

### Browser
Include browser name and version
FF 88.0/64
### OS
Include OS name and version
Windows, latest stable version

**Comment by David263** [comment]
Just a general comment: your tool is a **very** good one, and I'm sure that my bug reports must be incorrect. But user friendliness (ease of use) is very important for a tool like this. It really should be made a bit simpler and more foolproof to use for someone not familiar with the Regex101 instructions who just wants to use the tool. (I am assuming there _are_ instructions. I don't see a Help link. Every tool needs instructions.)

**Comment by working-name** [comment]
Please confirm that the pattern and test string I copied is indeed correct here: https://regex101.com/r/YMh6zf/1/

Debugging is only available for the PCRE engine because it offers said function. If you switch flavors to something else the debugger link goes away. 

That being said, the debugger only takes into consideration the `TEST STRING` input.

Could you please elaborate on a few things that would add value to the site and make it easier to use? For example, would a video overview of how to use the tool help? Would an in-depth video tutorial of each function even be remotely interesting?

**Comment by David263** [comment]
"Debugging is only available for the PCRE engine" - but I specified PHP 7...

"would a video overview of how to use the tool help?" - It probably would help many people. But the problem with video is that it fixes the speed at which the material is presented. A well-organized Help file can be read at variable speed, as the reader may need.

The handling of the outer delimiters is clunky and really should be improved. A good way to improve is to require the user to supply not just the pattern string, but the entire string including the two delimiters and any modifier flags. Then the pattern matching will be reliable, not relying on the user manually discovering how to change the delimiter and the flags.

If you want to force the user to supply a partial pattern string, then the burden is on the tool to pick an unused delimiter and an appropriate set of flags, both depending on the test cases. But this is almost AI! You really should ask for the entire actual argument to the preg_xxx function. I'm not backing down from this. If you want, you can "seed" the pattern field with "//". But  I'm afraid even this suggestion would confuse RE beginners. Maybe give a few examples of valid patterns that are very short and clear, like /\w+/ with a test case 'abc'.

**Comment by David263** [comment]
In further thinking about the problems I have experienced with this tool, I realize that I chose the wrong options several times, not realizing what they really meant. An good example is the Unit Tests link. Choosing that option can really get one confused. The names given to items in the GUI are too short and lacking in expressiveness. The Match should be indicated as a strong default, not just listed first. Maybe ask confirmation to select functioning other than Match. And in the debugger, the most important function is not available by mouse, the right arrow key, which moves one step forward in the matching process so one can find the first place in the test string that fails to match. In fact, a visual arrow should point to that place, since that is the main value of the debugger. And that pointer should always be shown, not requiring displaying the debugger GUI. I hope my suggestions will be considered, as they would have made a big difference for me along the way.

**Comment by working-name** [comment]
> but I specified PHP 7...

Then the debugger link should be there. Again, not in unit tests mode, as it's only available for the test string.

> A well-organized Help file can be read at variable speed, as the reader may need.

Noted.

> The handling of the outer delimiters is clunky and really should be improved. A good way to improve is to require the user to supply not just the pattern string, but the entire string including the two delimiters and any modifier flags. Then the pattern matching will be reliable, not relying on the user manually discovering how to change the delimiter and the flags.
> [...] You really should ask for the entire actual argument to the preg_xxx function

This is the site's behavior. If you give it the full regex it will fill things out for you. So `s@legume@bean@gsmx` would switch to the substitution tab and apply the flags when pasted into the regex field.

> Maybe give a few examples of valid patterns that are very short and clear, like /\w+/ with a test case 'abc'.

There is a tab on the right hand side, at the bottom, called `QUICK REFERENCE` which provides a description and a short example for almost every token.

> A good example is the Unit Tests link. Choosing that option can really get one confused. The names given to items in the GUI are too short and lacking in expressiveness. The Match function should be indicated as a strong default, not just listed first. Maybe ask confirmation to select functioning other than Match.

What GUI options are too short/lacking in expressiveness? I'm not sure I understand the last part about the `match function`.

> And in the debugger, the most important function is not available by mouse, the right arrow key, which moves one step forward in the matching process so one can find the first place in the test string that fails to match. In fact, a visual arrow should point to that place, since that is the main value of the debugger. And that pointer should always be shown, not requiring displaying the debugger GUI.

If you drag the slider using the mouse it will go step by step, it won't skip any.

The debugger is meant to help you understand what the engine does with the instructions you give it. Think of regex as a programming language, albeit with an interesting syntax. If you write a program in php, is there a software that can figure out exactly where your program fails? I think not, which is why you add a bunch of `error_log` and `var_dump` or go for a more sophisticated debugging method like xdebug + breakpoints to understand where you went wrong when coding the program.

**Comment by David263** [comment]
"If you give it the full regex it will fill things out for you"

As I said, this did not work for me. Does it work for you?

"There is a tab on the right hand side, at the bottom, called QUICK REFERENCE which provides a description and a short example for almost every token."

I realize that you are uncomfortable considering any change to your product, since you are understandably attached to it as it is. However, showing some examples the first time the program is run for a user, right next to the input field, would be **very** helpful.

"What GUI options are too short/lacking in expressiveness?"

I don't think we are communicating very well. Let's meet on Zoom and we can talk interactively. I'm in the New York time zone and usually available, and I have a Zoom account.

"If you drag the slider using the mouse it will go step by step, it won't skip any."

You can't see the details because you are too attached to the way it works. Here are the detailed problems:

1. Some people don't have a mouse. For example, they may be blind or visually impaired.
2. It requires a lot of muscle control to move just one step forward when there are many steps in the matching.
3. Some people find pressing the right arrow key the most natural way to achieve this function.

"The debugger is meant to help you understand what the engine does with the instructions you give it. "

While this is true, its more useful function is to pinpoint where in the pattern and in the string a failure is occurring. Perhaps if we can agree on this, improvements to the GUI will be obvious.

"If you write a program in php, is there a software that can figure out exactly where your program fails?"

This is a false comparison. Regexp matching is always a black box, no matter what OS and language. That is **exactly why your tool is so incredibly useful**. In a programming language, interpreted or compiled, you get the luxury of error messages. But the authors of regexp libraries, in their deep lack of caring for users, provide only the most obvious of error messages. They should have provided at least an array of character offsets in pattern and string for any matching failure, when requested by a modifier flag. Since regexp implementations provide no debugging information for matching, your tool is needed. My point is that your debugger should not be a separate and optional interface! What you call debugging information should be presented on an equal footing with the detailed explanation of what the pattern means (which you already show on the main page).

**Comment by working-name** [comment]
> As I said, this did not work for me. Does it work for you?

Yes, it does. See it in action here: https://bugout.regex.cf/a7f0aff85f77a539b8baad222735d3d4_2021-04-24-20_31_26.webm

Is this still on FF 88 on Windows that it doesn't work properly? I'm assuming you used the example pattern I mentioned (and is shown in the video).

> I realize that you are uncomfortable considering any change to your product, since you are understandably attached to it as it is. However, showing some examples the first time the program is run for a user, right next to the input field, would be **very** helpful.

Allow me to set the record straight: I'm not the author of regex101, I'm not a developer. I simply triage reports and try to replicate bugs to save time for the developer.

> I don't think we are communicating very well. Let's meet on Zoom and we can talk interactively. I'm in the New York time zone and usually available, and I have a Zoom account.

I'd love to do that but unfortunately my time availability does not allow for 1:1 video calls for bug reports. Maybe you could instead record your screen to exemplify what you mean?

> You can't see the details because you are too attached to the way it works. Here are the detailed problems:

> 1. Some people don't have a mouse. For example, they may be blind or visually impaired.
> 2. It requires a lot of muscle control to move just one step forward when there are many steps in the matching.
> 3. Some people find pressing the right arrow key the most natural way to achieve this function.

I'll be honest with you, this one confuses me. But it sounds like what you want is a new feature to (maybe) add buttons for `go forward 1 step, go back 1 step`.

> While this is true, its more useful function is to pinpoint where in the pattern and in the string a failure is occurring. Perhaps if we can agree on this, improvements to the GUI will be obvious.
>
> This is a false comparison. Regexp matching is always a black box, no matter what OS and language. That is **exactly why your tool is so incredibly useful**. In a programming language, interpreted or compiled, you get the luxury of error messages. But the authors of regexp libraries, in their deep lack of caring for users, provide only the most obvious of error messages. They should have provided at least an array of character offsets in pattern and string for any matching failure, when requested by a modifier flag. Since regexp implementations provide no debugging information for matching, your tool is needed. My point is that your debugger should not be a separate and optional interface! What you call debugging information should be presented on an equal footing with the detailed explanation of what the pattern means (which you already show on the main page).

It is entirely possible for me to have misunderstood how the regex engine works across certain programming languages. As far as I know, detailed debugging information is only available via PCRE/pcretest. I'm unaware of a programming language that implements those features. Therefore obtaining the same level of detail from the javascript engine, for example, is at this point an impossibility.

Keep in mind though, the regex engine does not simply read your regex from left to right and tries to match that part in the string; that's too simplistic of an implementation. It backtracks, has alternates (think of it like branching), so that the same `\w+` token can match 1 character of the string or 200, depending on where it is placed (recursion, backtracking, alternation, quantifiers, verbs). That's why, I think, it is a very tricky thing to achieve - notifying the user of the first spot in the string where the engine first failed to match. You also can't break up the regex per token and test it out that way (to estimate string position), because individual parts do not have the same meaning as they do in a full pattern.

That's just my understanding of how things work but don't know what it entails to build a feature like that because I'm not a developer. That being said, I'm not for building it, nor against it.

I do think that it would be a much better use of your time if you segregated the ideas for improvement and presented them either individually or per category as 'feature/enhancement requests'. In my opinion, when things are grouped together it's easier to have some ignored due to the focus shifting to other items in the same report.

**Comment by David263** [comment]
Thank you for the video. What I see here is your putting a bare pattern in the pattern field and a longer test string (which I had taken to be a pattern with pattern delimiter "s") in the test string field. **Of course that works.** The case you failed to test is the one **you claimed**: that a full pattern, including pattern delimiters and modifier flags, can be placed in the pattern field and automatically change the current pattern delimiters and modifier flags in the GUI. That is what you claimed, and that claim is false. Again, possibly for the third time, I recommend that you stop trying to do everything for the user. Require a full pattern string for PHP mode and issue error messages if the syntax is wrong.

This reply is to your first point; I am very busy currently, so I'll get to your additional points when I have time. I am willing to engage in this conversation until you hear what I am saying (thank you for staying with it), but I am working on an important project now so my time is limited.

**Comment by working-name** [comment]
You don't need to convince me that there's a bug, we just need some info to be able to reproduce it and figure out a fix for it. We'll be here when you're free, and good luck with the project!

**Comment by David263** [comment]
I am not requesting a fix for this "bug". I am requesting something quite different: allowing the full pattern for whatever environment the user has chosen. Please reread to see what I have suggested.

**Comment by working-name** [comment]
I understand what you meant perfectly across the two bug reports you opened. You're not here to report a bug, you just want the application to behave in a way that appeases or makes more sense to you. There's nothing wrong with that, and I'm all for improvements for everyone. My job here, however, is to triage, provide clarifications of how things work right now (workarounds if you will), organize issues, and recreate/confirm bugs.

The fact is that this is a bug report you opened, and by using "this did not work for me" to describe the issue leaves a lot of room for interpretation that you're actually submitting a bug report 😁

To be clear: I'm not discouraging you from expressing your desires and/or suggestions for improvement. Heck, if I could, I would post each one of your suggestions for you. 

All I'm asking is that you help me keep things organized and in turn ensure that each one of your suggestions get the attention they deserve. Think about it, the two threads we're conversing in are very long, and touch on many different topics (scattered?) - that's a heavy demand on the developer's time to figure out which one is a bug report, feature request, or an enhancement request.

In an effort to help save you some time, here's what I got so far from our conversation:

Feature Requests:
1. Make the regex input box accept a full paste without restricting flags or parsing
  - purpose is for delimiters not currently part of the list can operate on the site. This would also eliminate the need to escape delimiters due to the difference from my copied code and the site's ability to only use a limited set.
2. Have debugger run on each Unit Test as well
3. Set up a visual tutorial introducing new users to each function of the site, complete with a simple regex example.
4. Publish documentation for each part of the site, preferably in written form

Enhancement Requests:
1. Have debugger report on the first point in the string where the regex failed to match
 * preferably have an obvious visual, including while on the main view, not just in debugger view
2. Do not switch back to `/` as the delimiter when switching flavors, display an error instead
3. Do not remove unsupported flags when switching to another flavor, display an error instead
4. "The names given to items in the GUI are too short and lacking in expressiveness." - in Unit Tests.
  * you'll have to make a screencast here, it seems like the best option since describing it via text didn't prove effective.
5. Add "move forward 1 step" and "move back 1 step" mimicking the arrow right/left keyboard shortcut, to make it easier for people who wish to use a mouse instead.
6. Pull debugger in the main UI alongside "EXPLANATION" tab.

**Comment by firasdib** [comment]
Long thread... Responding to your tldr @working-name 

Feature:
1. Whats the issue? The delimiters are limited to avoid confusion and general issues with certain characters.
2. Whats the point of this? I could add a debug button to each failed test case so you can run it through that and figure out what breaks.
3. I will not do this, but someone else might.
4. ^

Enhancement:
1. Please elaborate.
2. The delimiter is switched to ensure it works with the given flavor, no way around this unless I keep history which is senseless.
3. Same here, but even more so, there is no simple way to display the error. The flags menu isn't generic, it depends on the flavor. You would have no way to remove them.
4. Elaborate.
5. Drack the handle on the track using your mouse.
6. I don't understand.

**Comment by firasdib** [comment]
The new version will allow for unit test cases to be individually debugged.
