### ISSUE TITLE
Inaccurate wording of subroutine call in explanation/quick reference

### ISSUE THREAD

**Issue by Timvde** [firasdib/Regex101#1601]
Both the explanation tree and the quick reference say that `(?1)` "recurses" the first subpattern. This is incorrect, as "recursion" by definition means that a call to itself is being made. `(?1)` just calls the first subroutine, and only when the subroutine includes the `(?1)` subroutine call again, it is called recursion. Of course this makes `(?R)` automatically recursive, so there is nothing wrong with the wording there.

Current wording:
- Explanation tree: `(?1) recurses the 1st subpattern`
- Quick reference: `recurse first subpattern`
- Quick reference: `Recursively match the first capture group.`

Proposal for more correct wording:
- `(?1) calls the 1st subroutine`
- `call first subroutine`
- `Match the same pattern as defined in the first capture group. This can be used to implement recursion if the capture group itself contains (?1).`

**Comment by working-name** [comment]
Hello Tim! :) 

I think this is a matter of semantics, really - neither the current definition nor your proposed one confuses or makes it clearer. 

That being said we're trying to be as clear as possible when explaining things because often times it's the new users reading these descriptions. Starting them off the right way rather than creating misunderstandings is absolutely worth it.

The wording is that way to mainly differentiate between `\1` and `(?1)`. How do you propose we describe `\1` ?

- `(?1)` calls the 1st subroutine (your proposal)
- `\1` match subpattern number 1 (current description)

I find `calls` not specific enough as to what it actually does.

**Comment by Ouims** [comment]
I have already reported these wording issues and got the same answer.
I agree that saying 'recursing' when there's no recursion is wrong.
Arguing that you are trying to be clear for new user by using wrong definition is non sense to me.

\1 is called a reference, it refers to what has been matched currently by the first group, it's a static value, always.
(?1) is a subroutine call to the first group, the actual pattern from the first group is injected at the current position

That's how it is described in documentations, either pcre or others, and i don't see how calling it recursion when it's not recursion is any clearer for new users.

"subroutine call" comes from programming language, it's when you call a function, if you call it inside the function, it's recursion, otherwise it's not and it's a subroutine call. with regarde to that, it's a perfect word and it's what should be on the website as well...

**Comment by working-name** [comment]
If the explanation for `(?1)` should be "subroutine call to group 1" that's still fairly uninformative.

People who need regex can be book authors, content managers, one time only problem solvers, log aggregators, and non-programmers of all kinds. When they start using the site for the first time questions are going to be "how do I make it find anything that's not a number?" instead of "what was that thing again? oh right, negated character class!".

Therefore, the question stands: how can we improve on its accuracy while making it accessible to those who are not yet in on the lingo?

**Comment by Timvde** [comment]
Maybe my proposal could still be improved, sure :) "Subroutine call to first capture group" sounds better than what I proposed. I don't think you can have an accurate explanation that is suitable for beginners in the one-line summary. That's what the extended description is for.

I also think that the quick reference is not for learning. It doesn't need a full explanation. So if anything, match the wording of the [official PCRE2 syntax documentation](http://www.pcre.org/current/doc/html/pcre2syntax.html#SEC23), which calls it "subroutine references". The very well-known tutorial on [regular-expressions.info](https://www.regular-expressions.info/subroutine.html) also uses the word "subroutine". I'd argue that calling it "recursion" is more harmful than helpful, even for beginners.

The quick reference has a good search, so if you are worried about beginners looking for "recursion", they should still find it if it's in there. In any case, a wrong description is always more confusing than a correct one.

**Comment by firasdib** [comment]
Where did we land on this? Is renaming this worth the trouble? Reminder, this will affect the translations.

**Comment by working-name** [comment]
Yes, that's why I'm reluctant to pick something but I would go with Tim's "subroutine call to first capture group". Do you agree?

**Comment by firasdib** [comment]
@working-name I'm fine with that. If you wanna update it, ping me on Slack/irc and I'll send you the updated files.

**Comment by firasdib** [comment]
Working on it, will be released soon.
