### ISSUE TITLE
Incorrect syntax in SED substitute with blocks

### ISSUE THREAD

**Issue by thomasboussekey** [firasdib/Regex101#1606]
## Bug Description

Using the website for substitution, it generated this command line for **SED**:

```sh
sed -E 's/^.*"(.*)".*$/$1/gm;t;d'
```

Yet, I needed to change it to this one that works on `bash`:

```sh
sed -E 's/^.*"(.*)".*$/\1/gm;t;d'
```
Using SED 4.2.2, as documented here: https://linuxhint.com/50_sed_command_examples/#s11

### Browser
Include browser name and version
chrome

### OS
Include OS name and version
ubuntu

**Comment by working-name** [comment]
Hello!

The code generator does not modify your strings at all - and that includes the replacement string. If you type in `$1` it stays as `$1`. The only thing it does is try to offer an example of how you would use said regex in a specific language - and even then it only properly escapes the regex to comply with target language. It does not fix your regex nor change it otherwise.

Hope this helps :)
