### ISSUE TITLE
Misleading Expalantion in Python Flavor

### ISSUE THREAD

**Issue by Attacktive** [firasdib/Regex101#1639]
## Bug Description
In Python Flavor, the following explanation is not necessarily right:
> `\d` matches a digit (equivalent to `[0-9]`).

### Reproduction steps
1. Select 'Python' flavor.
2. Type `\d` as the Regular Expression.
3. Type `٠١٢٣٤٥٦٧٨٩` as the Test String. *(optional)*

### Expected Outcome
The Explanation should be something like:
> `\d` matches a digit (*almost* equivalent to `[0-9]`).

### Browser
Include browser name and version
Google Chrome
Version 92.0.4515.159 (Official Build) (64-bit)

### OS
Include OS name and version
Windows 10 Pro Version 21H1 (OS Build 19043.1165)

**Comment by working-name** [comment]
Hello!

This is due to changes in python3 generally, including re module which is unicode by default. The site was build with python2 in mind but there are plans to implement python3 specifics as well.

Once that's completed this issue will inherently be fixed.

Please track general progress using the python tag: https://github.com/firasdib/Regex101/issues?q=is%3Aissue+is%3Aopen+python+label%3Apython
