### ISSUE TITLE
The 5 reported matches look like 3 within the TEST STRING

### ISSUE THREAD

**Issue by jgomezprada** [firasdib/Regex101#1653]
![image](https://user-images.githubusercontent.com/26471671/136719846-fb976ba4-925e-4bf9-9d24-2580c3511835.png)

**Comment by working-name** [comment]
Hello! 

Thank you for bringing this to our attention. 

The color part is tough to get right, there's so many preferences and abilities to see certain spectrums but not others to where it's very difficult to strike a balance.

Maybe we could revisit color shades. The only thing that's missing is the pink bars in the middle of the two matches which is most likely a CodeMirror parser related thing. Otherwise when hovering over the a's in the test string you see that it's two separate matches.

**Comment by firasdib** [comment]
This is whats happening:

Match 1. Empty match, pink dashed line (technically light blue)
Match 2. 'a', dark blue
Match 3. Empty match, pink dashed line (technically light blue)
Match 4. 'a', dark blue (overwrites match 3 as they start on the exact same position)
Match 5. Empty match, pink dashed line (technically light blue)

One way of fixing this would be to start painting all matches 1 px to the right, which would offset them slightly (probably negligible), but highlight edge cases like this better. The idea with alternating colors is to avoid this though. Perhaps the alternating color should disregard empty matches instead?

**Comment by firasdib** [comment]
The alternating color thing becomes an issue in the match information box, where alternation works regardless. This is a touch nut to crack. I will have to explore this a bit more and see if I can find a better, generic, solution. Shifting everything one pixel to the right doesn't look very nice.

**Comment by firasdib** [comment]
I have elected to pain the zero width matches last, to avoid them being overwritten, which means you will always see them.

**Comment by jgomezprada** [comment]
It would also be nice if the alternation of character background colors
were independent of zero width matches.
