### ISSUE TITLE
Tests are not working out correctly

### ISSUE THREAD

**Issue by iLinkses** [firasdib/Regex101#1659]
## Quiz Bug
The tests are not working out correctly, although on the site itself, everything is working out correctly.
I am not writing my solutions at your request.
Suggestion: to give an opportunity to solve all tasks, to give hints.

### Task

- Task 8: HTML Tags (optional)
- Task 9: Match an E-Mail (Simplified) (optional)
- Task 11: Validate Floating Point Numbers

### Expected Outcome
All the examples were taken from the examples of failed tests. On the site itself, with the same regex, everything works out as needed.

### Browser
Opera for dev

### OS
Win10

**Comment by iLinkses** [comment]
> I see. If you could send your regex, quiz step, and the examples from the tips to `contact@regex101.com` that would be awesome. Thank you!
Hello! Did you receive the letter?

**Comment by firasdib** [comment]
Yes thank you. I will look into this at another point in time.

**Comment by Hegy** [comment]
Task 9: Match an E-Mail (Simplified) (optional) 
Not working. Or is it me?
My exp
^([a-z0-9_\.\+-]+)@([\da-z\.-]+)\.([a-z\.]{2,6})$
Result
Test 17/56: .example.co is not a valid domain.

**Comment by working-name** [comment]
> Task 9: Match an E-Mail (Simplified) (optional) Not working. Or is it me? My exp ^([a-z0-9_.+-]+)@([\da-z.-]+).([a-z.]{2,6})$ Result Test 17/56: .example.co is not a valid domain.

Hi, wrong thread, and also we don't post results for the quiz because that ruins the fun of it. There's also a competition for the shortest regex to comply with the requirements.

Anyway, yes, it seems this time it's you. You can open up another instance of regex101.com and then test things out yourself if the checks don't make sense. For the regex you posted `very@..................................................wrong.com` would be a match too. Probably not what you intended. 

For further clarifications and discussion on this please join us on IRC by hitting the live help button.
