### ISSUE TITLE
Generated Swift Code throws NSRangeException

### ISSUE THREAD

**Issue by fritzfr** [firasdib/Regex101#1678]
## Bug Description
Swift code generated for the following example throws an exception when run.

### Reproduction steps

1. Insert `/\[.*?\]|([^\[\]]+)/g` into the regex input field.
2. Insert the following into the test string field:
`hallo [Some bold text|bold]`
3. Generate Swift Code, I got this:

```swift
let pattern = #"\[.*?\]|([^\[\]]+)"#
let regex = try! NSRegularExpression(pattern: pattern)
let testString = #"hallo [Some bold text|bold]"#
let stringRange = NSRange(location: 0, length: testString.utf16.count)
let matches = regex.matches(in: testString, range: stringRange)
var result: [[String]] = []
for match in matches {
    var groups: [String] = []
    for rangeIndex in 1 ..< match.numberOfRanges {
        groups.append((testString as NSString).substring(with: match.range(at: rangeIndex)))
    }
    if !groups.isEmpty {
        result.append(groups)
    }
}
print(result)
```

When I run this in Xcode, I get:
> *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[Swift.__SharedStringStorage substringWithRange:]: Range {9223372036854775807, 0} out of bounds; string length 27'

### Expected Outcome
It should print an array of the results.

### Browser
Chrome Version 96.0.4664.55

### OS
macOS 11.6

**Comment by fritzfr** [comment]
It seems to have to do with `match.range(at: rangeIndex)`. I'm not sure yet why it is being used, but simply replacing it with the `match.range` fixes at least this specific example from what I can tell.

**Comment by rogerluan** [comment]
IIRC the reason the code was implemented as is is because there may be multiple groups in the regex, with multiple matches each. I haven't looked into that crash yet though

**Comment by firasdib** [comment]
Whats the suggested fix for this?

**Comment by rogerluan** [comment]
Hey 👋 
I've spent some time investigating this issue. I was intrigued by the fact that the regex match produces an invalid range 🤔 So I found this Stack Overflow answer https://stackoverflow.com/a/35415787/4075379 that led me to this Apple documentation https://developer.apple.com/documentation/foundation/nsregularexpression that states:

>Some regular expressions (though not the example pattern) can successfully match a zero-length range, so the comparison of the resulting range with {NSNotFound, 0} is the most reliable way to determine whether there was a match or not.

At first I was skeptical that simply ignoring such range would fix the issue, because I was expecting that the regex + test string that you provided should return `print(result) // ["hallo ", "[Some bold text|bold]"]` as you had posted above, but I don't think that's the case. If you enter that regex + test string in regex101 website, you'll see it only has 1 captured group, for `hallo `:

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/8419048/154860052-773344d5-e334-499e-819b-13d4367972d4.png">

The 2nd match (`[Some bold text|bold]`) is just a match, but not a captured group. So I think in the end, the result `[["hallo "]]` is the expected result after all 🤔 And if we can agree on this, then the solution is a simple addition of the following snippet:

```swift
guard !NSEqualRanges(nsRange, NSMakeRange(NSNotFound, 0)) else { continue }
```

Before evaluating the `range(at: index)`. I've suggested the change in my feature PR:

https://github.com/firasdib/Regex101/pull/1369/files#r810671993

@fritzfr @firasdib let me know if that makes sense to everyone 🙏

**Comment by firasdib** [comment]
@rogerluan I haven't written a line of Swift in my life, so I completely rely on you guys for this :-).

If you all feel this is the better change to make, I'll make it.

**Comment by rogerluan** [comment]
@firasdib the point isn't the Swift implementation, but rather the expected result of the given input :) would you say that given that regex and test string, the output should be just "hallo "? Or should it also return the 2nd match (that isn't being captured)?

**Comment by firasdib** [comment]
@rogerluan Some languages return null/empty string for consistency, others don't. I'm fine with either or, as long as thats the expected behavior.

**Comment by fritzfr** [comment]
Should be fine. I'm using this (https://github.com/firasdib/Regex101/issues/1678#issuecomment-985409549) in production and it works, might be for my use case / string though.

**Comment by rogerluan** [comment]
Gotcha, thanks for the input @firasdib . I tested the behavior of the Ruby code generator and it prints `["hallo "] and ["nil"]` :) 
@fritzfr if you agree with this, @firasdib I think we can make the change I suggested in the original PR 👍  I didn't really run/execute that change in js, so it might have minor syntax issues, but hopefully not 😆  once you apply the changes, if it runs once, it's good to go. 🙏

**Comment by firasdib** [comment]
Thanks a lot for your help. I've added your changes and will push it soon, hopefully a few days.
