### ISSUE TITLE
Bug in debugger

### ISSUE THREAD

**Issue by softrasys** [firasdib/Regex101#1685]
## Bug Description
My pattern (simple one) which is working correctly cannot be debugged. It hangs somewhere.

### Reproduction steps
My regular expression:
^([0-9]{10}),((20[2-9]+[0-9]+)(0[1-9]+|1[0-2]+)(0[1-9]+|1[0-9]+|2[0-9]+|3[0-1]+)([0-5]+[0-9]+)([0-5]+[0-9]+)([0-5]+[0-9]+)),([-|+]?[0-9]{1,3}(?:.[0-9]{1,7})?),([-|+]?[0-9]{1,3}(?:.[0-9]{1,7})?),([0-9]{1,3}),([0-9]{1,3}),([0-9]{1,4}),([0-9]{1,2}),([0-9]{1,9}),([0-9]{1,3}),([0-9]{1,3}),([0-9]{1,11}(?:.[0-9]{1,5})?),([0-9]{1,11}(?:.[0-9]{1,5})?),((20[2-9]+[0-9]+)(0[1-9]+|1[0-2]+)(0[1-9]+|1[0-9]+|2[0-9]+|3[0-1]+)([0-5]+[0-9]+)([0-5]+[0-9]+)([0-5]+[0-9]+)),([-|+]?[1-9]+[0-9]*(?:.[0-9]{1,7})?)

My text:
1010003948,20211001042144,35.500537,33.902416,0,291,-29,0,11,1,0,0.000,0.000,20211001042631,137583720

### Expected Outcome
Debugger hanging

### Browser
Include browser name and version
Chrome Version 96.0.4664.93 (Official Build) (64-bit)
### OS
Include OS name and version
Windows 10 Enterprise, OS Build: 19044.1348

**Comment by working-name** [comment]
Hi @softrasys,

I'm unable to make it hang in my `Version 96.0.4664.93 (Official Build) (x86_64)` Do you maybe mean that the debugger seems to stop advancing/highlighting your string as you go along? The regex doesn't return a match, but if you look closely all the way to step 679 there is a cursor advancing one character at a time but not matching anything because it cannot satisfy the requirements of your regex.

**Comment by firasdib** [comment]
I am also unable to reproduce. Could you elaborate further?

**Comment by softrasys** [comment]
Hello,

My pattern:
^([0-9]{10}),((20[2-9]+[0-9]+)(0[1-9]+|1[0-2]+)(0[1-9]+|1[0-9]+|2[0-9]+|3[0-1]+)([0-5]+[0-9]+)([0-5]+[0-9]+)([0-5]+[0-9]+)),([-|+]?[0-9]{1,3}(?:.[0-9]{1,7})?),([-|+]?[0-9]{1,3}(?:.[0-9]{1,7})?),([0-9]{1,3}),([0-9]{1,3}),([+|-]?[0-9]{1,4}),([+|-]?[0-9]{1,2}),([0-9]{1,9}),([0-9]{1,3}),([0-9]{1,3}),([0-9]{1,11}(?:.[0-9]{1,5})?),([0-9]{1,11}(?:.[0-9]{1,5})?),((20[2-9]+[0-9]+)(0[1-9]+|1[0-2]+)(0[1-9]+|1[0-9]+|2[0-9]+|3[0-1]+)([0-5]+[0-9]+)([0-5]+[0-9]+)([0-5]+[0-9]+)),([-|+]?[1-9]+[0-9]*(?:.[0-9]{1,7})?)

My correct string:
1010003948,20211001042144,35.500537,33.902416,0,291,-29,0,11,1,0,0.000,0.000,20211001042631,137583720

Now, let us play a bit with the string, I will add a * (star) at the beginning of one of the parameters so that the expression does not match the pattern:
1010003948,20211001042144,35.500537,*33.902416,0,291,-29,0,11,1,0,0.000,0.000,20211001042631,137583720

I lunch the debugger, it should find the ‘*’ as the error at the error location, but the debugger would not go beyond the second parameter. Try playing with the timeline, it never bypasses the 2nd (date) parameter, unless of course my pattern is not correct.

***@***.***

Regards,
Albert




Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by working-name** [comment]
I see. In my opinion developing a debugger that behaves in the manner you explained is not quite possible or if it is, it's a monumental amount of work.

Think of the debugger as a window inside the engine's execution of your commands. It's not an interactive type of debug, with breakpoints and so on. It just helps you see how it tried to execute your commands on the given string.

Outside of that, there's no knowledge of parameters, type of string, or any structure at all, and it doesn't care or keep track of what it matched, nor does it look ahead any further than your next command. 

---

The regex engine just tries to obey your commands, in the order you gave them, and with the limitations you set. That's what a regex is: a string of commands. In other words, `/ab?c{4}$/` gives the engine commands:
- match an a, anywhere in the string (you set no limitations)
- match a b, 0 or 1 times (immediately after matching an a)
- match a c exactly 4 times (immediately after matching an a, or immediately after matching ab)
- make sure the end of the string comes next (immediately after matching an `a`, then 4 `c`'s, or an `a`, a `b`, and 4 `c`'s

As you can see, even for a very simple regex like that there's options and implicit limitations that can result in a bunch of backtracking on a string with multiple `a` characters in it - aka multiple points where the regex engine can start running your commands. That's why it's tough to find a particular point in the string where the regex "fails" because failure is almost always not a single point.

---

The regex engine assesses failure or success as the result of the whole "program" running on your string, if you consider the whole regex a program and individual tokens as lines of code or commands. As it progresses through your regex and your string, there can be many failure points: backtracking, outright giving up matches (look at the `(*FAIL)` and `(*SKIP)` verbs), giving up on an alternate and trying an nth one, and so on. Therefore you either get a bunch of failure noise that way, or a bunch of silence the current way.

**Comment by softrasys** [comment]
I underdtand. I actually learned a lot from your site with trials and errors on my patterns. Your color grouping made things simpler. I agree, I am asking a lot from the debugger; for the sake of example, could you allow debugging a correct string just to understand the behaviour?

Again, wonderful job (y)

Regards,
Albert



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by working-name** [comment]
@softrasys The debugger works both when successfully matching and when it fails to match. So if you remove the unaccounted for `*` in your string, you'll get the matches. Then click debugger and see how it works.
