### ISSUE TITLE
Clicking on Match Should Also In SUBSTITUTION (not just TEST STRING)

### ISSUE THREAD

**Issue by dbareis** [firasdib/Regex101#1689]
It's great that clicking on a match (Match Information) scrolls to and highlights the match (in "TEST STRING" field), but if "Substitution" is selected it should also do that in "SUBSTITUTION" field.  

That may have to highlight BEFORE & AFTER text in cases where there was empty substitution.

**Comment by firasdib** [comment]
The problem with this is that substitutions act as a single action, there is not an array of matches returned that I can render. I submit a regex, test string and substitution string to the replacement function of said language, and get a result back. I don't know where each match was replaced, and with what, in the output string. Because of that, I cannot do any highlighting or similar.

The only solution would be to re-implement the functionality on my own, which I don't want to do, as it might not match the native result for that language.
