### ISSUE TITLE
Mixed escaping rules for Java 8

### ISSUE THREAD

**Issue by marcardar** [firasdib/Regex101#1706]
## Bug Description

In Java 8, we do not need to escape double quotes in a regex other than for the normal escaping required within String literals.

So the regex `\s"` would be declared in a String literal as `"\\s\""`

However, in regex101, `\s"` gives a [pattern error](https://regex101.com/r/Eh3D8F/1), and the escaped form `\\s\"` [does not match](https://regex101.com/r/kuDCac/1).

### Reproduction steps
See above

### Expected Outcome
Since the UI shows the regex within fake double quotes, I would expect the correct regex to be the fully escaped one `"\\s\""`

### Browser
Chrome 97.0.4692.99

### OS
MacOS 12.1

**Comment by firasdib** [comment]
I'm not entirely sure I agree with your description, but you have highlighted an interesting problem.

The input on regex101 is a raw input, meaning no string interpolation is done. That is, if you could disable the string interpolation in Java, the expression would run exactly as on the website. However, this is not the case, which is why you'd need to copy it from the code generator to get the correct escaping. In there, however, it incorrectly escapes the quote again. This will have to get fixed.

Fixed your first example: https://regex101.com/r/Eh3D8F/2

**Comment by marcardar** [comment]
I've only tested on Android Studio (using Java 1.8), but the code `final String regex = "\\s?\\\"";` gives the compiler warning `Redundant character escape '\\\"' in RegExp`. Can you confirm whether:

`final String regex = "\\s?\"";`

is valid for you?

> The input on regex101 is a raw input, meaning no string interpolation is done

Isn't it misleading to show the fake double quotes around the input area?
