### ISSUE TITLE
Cmd + a /Cmd + Shift + arrow (up or down)/Cmd + Shift + s don't work as expected Mac

### ISSUE THREAD

**Issue by bburgess19** [firasdib/Regex101#1717]
## Bug Description
When using any of these hotkeys either nothing happens or the macOS hotkey activates.

### Reproduction steps
Use any of the above hotkeys when editing a regex.

### Expected Outcome
Cmd + a: nothing.
Cmd + Shift + arrow (up or down): shifts tabgroups in safari.
Cmd + Shift + s: Download the webpage prompt.

### Browser
Include browser name and version
Safari 15.3

### OS
Include OS name and version
Monterey 12.2.1

**Comment by working-name** [comment]
Hey @bburgess19 can you explain further what it is you expect to happen and what URL or view you're on?

I have the same system but don't see any abnormal function. Are you saying regex101.com is taking over the shortcuts? CMD + A is universal for select all. The rest of the available shortcuts you can see by typing `?` when you visit the site (do not highlight any text input box).

**Comment by working-name** [comment]
@bburgess19 For sure. I played around some with safari and you're right about the `CMD` + `s` shortcut, it seems to be taken over by regex101 (works on a news site for example).

As far as the other ones go, they are contextual. For example, if you just loaded the site and press CMD + A, it would select all elements on the site, and some may not show a blue selection bounding box. That's normal behavior.

If you're inside a textarea or text input and press `CMD` + `A` it will select all text in that input. Inside these fields the global shortcuts do not work, and that may or may not be due to codemirror's (editor) shortcut implementation. I think by default it emulates vim or something.

Other than that I didn't come across any other odd behavior. I was going to do a screen recording but screenflow is crashing on me.

**Comment by bburgess19** [comment]
@working-name Thank you for the informative response.
I was actually hoping that `CMD` + `SHIFT` + `s` would be taken over by regex101—I believe it's supposed to be "Update regex". For me, it brings up the finder prompt to download the page. I recorded my screen!

https://user-images.githubusercontent.com/55334507/153933802-a47ebe59-1734-4426-88c7-a85712e4b894.mov

**Comment by working-name** [comment]
@bburgess19 you're right about the cmd + shift + s - if you have the screen small enough to trigger collapsing of the left sidebar, when you press CMD + SHIFT + s it brings up the sidebar even though the shortcut is not noted in the UI (only the save function appears before first saving an entry). So regex101.com is reacting to both shortcuts at all times.

What you're demonstrating however, is not something I can reproduce on my end. That being said, I have a very vanilla safari because I hate it and thus do not use it. So no addons, no special things going on. It might be worth disabling all addons, and trying that again in an incognito/private window. If you are still able to reproduce, then we'll have to look further.

I managed to get screenflow to work. The tab/group navigation works so long as you're not inside a textarea, and select all does its job across regex101.com and some random other site.
https://user-images.githubusercontent.com/16505052/153948058-e1de4394-4899-4eed-b331-86e91bf46aa0.mp4

**Comment by bburgess19** [comment]
@working-name Thank you again for the help. You're exactly right—the issues stemmed from some of the extensions I have/doing the inputs within a text box.
