### ISSUE TITLE
Lock threads to only the original author

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#173]
If an authenticated user creates a regex, let them choose whether the regex should allow others to "update" the regex (or test string) in a thread. If the regex is LOCKED, only the author can make changes and push updates to the revision thread; all others would only have the FORK REGEX option available, where they could start their own threads.

This option only needs to be available from a user's login/history page. By default, regex threads are unlocked, but can be overridden manually on a per-user and per-thread basis.

This would not work for threads which contain submissions already by more than the original author: any threads with existing contributions would not have the "lock/unlock" feature available.

**Comment by fatbearinc** [comment]
Has this been considered or implemented?  It would be very useful so that regex examples could be shown to readers, also allowing readers to modify the regex, but not allowing readers to update the regex.  This would be worth a donation!

**Comment by firasdib** [comment]
I was thinking about this the other day for the new version and came to the conclusion its rather pointless, and adds a lot of complexity throughout the app. Simply does not seem worth it if you ask me.

1. You can always statically link to a regex which no one can modify.
2. If you link to a regex without a version, you will be redirected to the first version (instead of last as it is now).

Not only that, you can already lock a regex so only you, the author, can view it. I do realize that this feature would avoid people saving stupid stuff on your otherwise neat regex, but as I said, I don't think its worth the trouble.

If you disagree please feel free to reopen the issue.
