### ISSUE TITLE
Group Name invalid character errors could be more specific (simple to reproduce)

### ISSUE THREAD

**Issue by isibley765** [firasdib/Regex101#1732]
## Bug Description
Just error reporting on a named group that could be clearer.

I had a dash in my name that should have been an underscore, but the error was that the group was incomplete vs something more  specific & helpful.

### Reproduction steps
Just make a regex pattern against a string that has a named group, but use a dash in said group's name.

Something like this, maybe
> Regular expression:
> `(?P<number-block>\d+)`
> 
> Test String:
> `Shouldn't have found it yet 928371968987123 should have found it by now.`

Notice `(?P<number-block>\d+)` should be `(?P<number_block>\d+)`, `-` is invalid for a group name apparently.

### Expected Outcome
Some form of error hinting that the group's name has an invalid character, or at least is the point of failure.

### Current Outcome
> All the errors detected are listed below, from left to right, as they appear in the pattern.
> `(?` Incomplete group structure
> `)` Incomplete group structure

### Browser
Chrome v98.0.4758.109

### OS
Mac Big Sur v11.6

**Comment by firasdib** [comment]
This is actually harder than it seems, since the tokens can mean quite a few different things in the different flavors.

The lexer will look for a valid set of characters between `<` and `>`, and if it fails, it will proceed to the next one, and the next one, etc. Eventually, it gets treated as an incomplete conditional statement, and you see the error.

If I were to try to catch this error, I'd have to extend the characters it initially looks for between `<` and `>`, and then validate afterwards again. Problem if defining which characters that should be, as there are quite many of them.
