### ISSUE TITLE
Pattern error with valid javascript regex

### ISSUE THREAD

**Issue by localhosted** [firasdib/Regex101#1733]
## Bug Description

The regex `/[^\d-.]/g` should be valid javascript regex

Opening the developer tools and running `"1343215235-gkgoker".replace?.(/[^\d-.]/g, "")` works as expected but regex101.com shows a "pattern error"

![image](https://user-images.githubusercontent.com/8821661/156429748-9b3a53a7-0c08-40cf-9d30-3c234078f43c.png)

### Browser
Firefox Developr Edition

### OS
Windows 10

**Comment by firasdib** [comment]
This is intentional because Javascript is generally very confusing (and ambiguous) when it comes to the range token. I have tried to work around it for a long time, but finally elected to just mark it as an error when it is placed in such a way that it might be confusing or cause ambiguous behavior.

Let me run through an example: `/[\d-z-a]/` does not work as expected. In most flavors, where ranges with shorthand expressions are allowed (e.g. Golang), the result of this expression would be: `\d`, the literal `-` and a range `z-a` (which is invalid). However, in Javascript, this is not the case, and everything except for `\d` is treated literally. This is not what most people expect.

I could try to work around it again, but I am unsure if its worth the effort. If you use the `u` flag in JS, it already implements this strict behavior, and would generate an error.

**Comment by localhosted** [comment]
Ok, the linting was complaining about "unecessary escaping", but I guess I'll just use /u

**Comment by firasdib** [comment]
Which linter was that?

I tried it in IntelliJ, and it actually got it wrong too:
![image](https://user-images.githubusercontent.com/1335165/156584921-1a973337-4797-4e65-aae1-ff8df78fc230.png)
It thinks the range is a-z, not z-a.

**Comment by working-name** [comment]
At least until I stopped using intellij products they had a couple of issues linting regexes - I used to use phpstorm

**Comment by localhosted** [comment]
It was in a Create React App project with Typescript

**Comment by briancodes** [comment]
@firasdib On this point:
> but finally elected to just mark it as an error when it is placed in such a way that it might be confusing or cause ambiguous behavior.

May I ask how you find this particular pattern to mark it as an error? I'm also running into ambiguities with range shorthand,  spotted via your website, and wanted to validate RegExp using the same approach you have
