### ISSUE TITLE
`/u` modifier mentions `UTF-16` but should mention `UTF-8`

### ISSUE THREAD

**Issue by wgevaert** [firasdib/Regex101#1753]
## Bug Description
The UI of this app mentions UTF-16 for the global modifier `/u`, but the [php docs about global modifiers](https://www.php.net/manual/en/reference.pcre.pattern.modifiers.php) say it is UTF-8.

### Reproduction steps
1. Set `/u` modifier
2. Make some regex
3. Look at `Explanation`, section `Global pattern flags`: Mentions UTF-16

### Expected Outcome
It should mention UTF-8, as per [the docs](https://www.php.net/manual/en/reference.pcre.pattern.modifiers.php)

**Comment by firasdib** [comment]
Since the website implements PCRE2 (not PHP) and runs in your browser, it uses UTF-16. So in the case of regex101, since this is a implementation detail, this is the correct explanation. But for other languages (e.g. PHP, which has their own implementation), it can be UTF-8 or even UTF-32.

**Comment by firasdib** [comment]
That said, I'm open to ways of clarifying this if you have any ideas.

**Comment by wgevaert** [comment]
I did some digging, and it seems the issue is more sophisticated than I thought.

[PCRE2](https://www.pcre.org/current/doc/html/pcre2.html) is a C/C++ implementation/library, not some kind of standard, so the website "implementing" PCRE2 is something odd to say.

The UTF version used by the PCRE2 function is given as a suffix, e.g. `pcre2_compile_8` compiles UTF-8 bytestrings, `pcre2_compile_16` compiles UTF-16 etc. Alternatively, one can set `PCRE2_CODE_UNIT_WIDTH` to fix the charset at compile time and just use `pcre2_compile`.

In particular, PCRE2 does not have modifiers such as `/gium` etc, options should be passed in C/C++ style as bitmask of option constants. (nor does it have delimiters such as `/<pattern>/`, just pass `<pattern>`).
Any well-used php implementation takes a delimited pattern and these modifiers and passes these in a C/C++ style to the `pcre2_compile` function.

I am not sure what regex-dialect this website is representing. The use of modifiers and delimiters suggest it represents some dialect such as php, yet you say it represents PCRE2.

If this website is supposed to reflect the PRCE2 functionality, it should not assume the encoding is `UTF-16`. It can, however, assume the encoding with the `PCRE2_UTF` option is either UTF-8, UTF-16 or UTF-32.

I suggest something along the line of `u modifier: unicode. Pattern strings are treated as unicode (UTF-8, UTF-16 or UTF-32 depending on implementation). Also causes escape sequences to match unicode characters.` is better.

Note furthermore, that copy/pasting UTF-8 strings to this website works correctly on most browsers/OSes (probably because my browser/JavaScript engine handles encoding issues), so for the end-user, talking about everything being UTF-16 is highly confusing. An encoding-agnostic approach would be best imho.

**Comment by firasdib** [comment]
If you had dug a little further you would have learned that PCRE stands for Perl Compatible Regular Expressions, and is in fact a regular expression engine that matches a pattern with a given string in a Perl compatible manner. The syntax you speak of is Perl syntax.

The PCRE engine does not come with a complete implementation, but is something you have to write yourself, which is something both I and [PHP](https://github.com/php/php-src/blob/c0d890e918ff7b4212ef5a2e118a165f2c8eda39/ext/pcre/php_pcre.c) has done.

Everything in Javascript is UTF16, even if you paste in UTF8 strings. Since PCRE supports UTF16 out of the box, its an unnecessary step to convert the string to UTF8 before matching, and then back to UTF16 when returning the result. For the purposes of the website and results, they will be the same. Some discrepancies can be found in implementations that use UTF8 (such as PHP).

**Comment by firasdib** [comment]
I've said what needs to be said, you can argue semantics on stackoverflow.
