### ISSUE TITLE
Is it possible to get a flavor pre selected ?

### ISSUE THREAD

**Issue by jallegre-vm** [firasdib/Regex101#1764]
## Question

Is it possible to have a flavor pre selected , for example by having a flag in the url https://regex101.com/?flavor=ecmascript
This will allow to ensure the right flavor is selected when hitting the page from a favorite url

**Comment by working-name** [comment]
@jallegre-vm it is possible, although not an official feature. What you're looking for is `?flavor=javascript`


Then you have these that are a bit tricky, the rest are directly the flavor name (aka `golang`).

- `php` => PCRE2
- `pcre` => PCRE
- `dotnet` => .NET

DISCLAIMER: Since this is not an official feature, expect it to break or change in the future.

**Comment by firasdib** [comment]
@working-name is correct, however, `pcre2` is for PCRE2. In fact, its the detault, so any invalid defaults to that :-)

Otherwise you can go to the settings and select your preferred language/flavor, and it will be remembered regardless of url.
