### ISSUE TITLE
Start a completely new, blank expression

### ISSUE THREAD

**Issue by bburgess19** [firasdib/Regex101#1766]
## Feature
Often times I don't fully close out regex101 after I finish testing my expression, so when I come back and want to make a new expression, the easiest way is to close the tab and reopen the website. I could manually erase all of the text from the expression and demo text, remove the unit tests, and save a new expression, but it would be lovely if there was an elegant way to do this with a button!

Although this isn't the direst necessity, there have been a few times when I've inadvertently overwritten a previous expression by doing the whole clearing-text maneuver and updating instead of saving, so this would be a most welcome feature!

**Comment by working-name** [comment]
Hi there!

Actually my favorite way of getting a new page is clicking the logo. 1 button, no copy pasting or other weird steps.

To get a new regex trunk that has nothing to do with the previous you were working on, you hit save regex rather than update.

Do either of these options match what you had in mind?

https://user-images.githubusercontent.com/16505052/161399646-46bfd161-9367-4a9e-a8fc-b4d8e237f021.mp4

**Comment by bburgess19** [comment]
Yes indeed! Thank you for the speedy and informative response! This was exactly what I was looking for :)
