### ISSUE TITLE
Add option to expand escaped characters in test strings (like \n or \t)

### ISSUE THREAD

**Issue by David263** [firasdib/Regex101#1784]
## Feature
I specified a one-line test string that included the "\n" escape for the newline character. It was very frustrating that I could not get a match. My suggestion is to expand newline characters and other escapes in the test string, since they actually work in PHP, etc.

One interesting case is where one would like to distinguish whether a \r character matches in the test string. For that, you must have expansion of the test string.

If you have some reason why escapes should not be expanded in the test string, simply provide an option to expand them or not, so the user can decide.

**Comment by working-name** [comment]
Hi there,

Could you share an example link for the newline stuff? My example: https://regex101.com/r/Uc6lV7/1

In options there is a way to turn on visualization of spaces and newlines.

As far as being able to retain/test `\r` on the site, I'm afraid that's not possible in codemirror, see #931

**Comment by David263** [comment]
The example confuses a backslash-n combination with the newline character, so it fails to show that a pattern containing "\n" will actually fail to match a test case containing "\n". Visualization of spaces and newlines is a different issue. Also, a failure to be able to test carriage returns, while unfortunate, is still a different issue. I don't know how to provide an "example link" to show the failure. Do you mean a PHP program?

**Comment by working-name** [comment]
No, I mean a regex101.com link with a string and regex that show the problem you're describing. You can click save regex in the left sidebar and you'll get a link. Please remove/redact sensitive information, and if you plan on removing that link in the future save the delete link which will appear in the modal after save.

**Comment by David263** [comment]
I have made a test case at link https://regex101.com/r/pTvM55/1 . The test case works in PHP but fails in Regex 101.

**Comment by working-name** [comment]
I see, this is common to pretty much every programming language out there. In certain string types, escape codes will be expanded. For PHP for example, if you have `echo 'hi\n';` that will print out `hi\n` literally. That is not a newline character. If however the same thing is double quoted `echo "hi\n";` then the string becomes:

```
hi

```

The second example will have the character `\x{000A}` which is a newline character.

The site itself does not interpret the string through any kind of programming language before displaying it to your browser. So if you paste a literal `\n` in the text string, it'll stay as the two characters. If you pasted a newline character `\x{000A}` then likewise it'll stay a newline.

If for example you wanted regex to match a literal `\n` you could type in `\\n` in the regex field, or `\x{005C}\x{006E}` if you wanted the two codepoints for `\` and `n`.

So both PHP and the site agree on the newline part and the literal `\n` in terms of behavior and matching, so long as the input is the same. For PHP, the same input means 2 different things depending on how it's enclosed, whereas the site takes it as you give it.

**Comment by David263** [comment]
The test case is supposed to be a string, interpreted according to the same rules as the search pattern. The specific programs are listed in RE101, and include PHP, ECMAscript, and a number of others. Any discussion of the literal character string backslash, n (as when using single quotes in PHP) is irrelevant to this issue.

In patterns, the string"\n" is usually escaped to indicate a newline (linefeed). My point is that in all of the languages you support for patterns, the languages also support escape sequences that look similar in source strings.

I'm not concerned with "two different things", as my test case makes clear: I simply suggest that the escaped \n in a pattern should match the escaped \n in a test case. As a user of RE101 I expect this and am surprised (and waste a lot of time) when I find that \n fails to match \n.

I really think I'm repeating myself, which should not be necessary. I think my OP plus this example makes it clear what I am suggesting.

And again, if this makes you uncomfortable (change is not usually comfortable), just add an option to expand the usual escaped characters in test strings in the usual ways for the programming languages you list.

Please do respond if any part of my suggestion remains unclear.

**Comment by working-name** [comment]
Sorry, I must have not done a good job explaining it. The input textarea is a simulated editor built by Marijn, called codemirror, which is really a fancy DOM manipulation in javascript based on the value of an underlying textarea.

What that means is that the text you paste in does not get parsed by PHP first, then returned back to your textarea, it's just straight up codemirror. While it might be arguably useful to parse the string in PHP and have it expand escape sequences, that would be an extra step and more development to keep track of. Then some of the listed flavors in the left sidebar have 3 or more kinds of strings (python for example), which would inevitably cause some confusion and clutter the settings portion of the app.

Also, your statement that your regex works in PHP but not on the site is only going to be true in one of the two cases I mentioned: https://onecompiler.com/php/3xzx4ktkf - so it's not as cut and dry as "do what PHP does", because it does both.

As far as the programs listed on the site, they're meant as regex engine flavors rather than code execution in those programming languages. The site only tests regex matching, not code execution - if you type `echo "hi";` anywhere on the site there won't be a `hi` coming back at you. Each regex flavor as we call it has different capabilities, and PHP is just a common example of a PCRE2 implementation - there are other languages employing that particular flavor (perl compatible...). Does that make sense?

As far as misunderstanding your request - that's not the case, I get it. No need to repeat yourself.

**Comment by David263** [comment]
While you are correct on some minor points, I think you have missed the big picture here, which is optional expansion of escaped characters in test strings. You and I will just have to agree to disagree. I'm done trying to defend my suggestion.

**Comment by Ymiros0** [comment]
I think that if you do not add this feature you should perhaps add a note or something that the input in "test string" is interpreted as a raw string as imo it can be quite confusing to have the page say there is no match while in your code it does match because \n automatically gets converted into a newline in a normal string.

**Comment by firasdib** [comment]
The page tries to be WYSIWYG in that regard. Expanding newlines would be a bit tricky, as you would have to understand the details of the language, when things can/should be escaped, etc.

I would recommend you do this in some other tool.
