### ISSUE TITLE
Convert regex for use in code upon clicking copy in regular expression input

### ISSUE THREAD

**Issue by jwarner112** [firasdib/Regex101#1789]
## Bug Description

When constructing an expression for Golang, regex options don't properly translate and the tool isn't very clear about them. Unlike most flavors, Go does not appear to support the post-expression options `/like-so/gmi`, but insists on configuration at the start of the expression, e.g. `` `(?gmi)like-so` ``.

### Reproduction steps

1. Go to Regex101 tool and enter the test string `TEST`
2. Select flavor `PCRE2` and regex option `i`
3. Add regex `test` and see insensitivity correctly defined in the explanation panel
4. Notice that the test string matches
5. Copy expression and paste elsewhere to get `/test/i`, which compiles and works
6. Change flavor to Golang and notice the test string still matches
7. Copy expression and paste elsewhere to get `` `test`i ``, which provides a syntax error in Go (as it seems `` `(?i)test` `` is the only valid form

### Expected Outcome

Given all the UX indications on Regex101, I would expect the `Copy` button in the Golang flavor to provide `` `(?i)test` `` over `` `test`i ``

### Browser

Firefox 99.0.1 (64-bit)

### OS

MacOS 11.6.5 (Big Sur)

**Comment by working-name** [comment]
Hi @jwarner112 

Took me a little bit to understand which copy you're using. 

As a workaround, there's a tool on the left sidebar called `code generator`. Click it, and if you already have the Golang flavor selected it will give you a short demo code snippet showing you how to use it. Since it is code, your regex will appear in the most commonly used syntax as part of the target language.
