### ISSUE TITLE
Add a "no delimiter" option to the delimiter menu?

### ISSUE THREAD

**Issue by plasticinsect** [firasdib/Regex101#1796]
Some common real-world uses of regular expressions do not have any delimiter at all, because the regex is entered into a form field. (e.g. a regex search in a text editor). However, RegEx101 insists that a character be selected as the delimiter, and will then insist that all occurrences of that character be escaped. This can be a real nuisance sometimes, especially when trying to write a regex to filter URLs, because URLs contain so many characters commonly used as delimiters. It would be helpful if the list of delimiters also had a "no delimiter" option, that does not require any character to be specified.

**Comment by working-name** [comment]
@plasticinsect just out of curiosity, what do you use that has no need for delimiters?

**Comment by plasticinsect** [comment]
@working-name As part of my job, I regularly use regexes in a text editor (typically Notepad++) for many things. I often do complex search-and-replace transformations to convert the text output from one application to make it suitable as input for another. (e.g. transforming a raw log file into a list of URLs that can be fed to a web crawler for further analysis) I also frequently use regex searches while programming, to sweep for specific types of errors, to check for name collisions, etc. If my code fails because I made a mistake, my habit is to immediately do a regex-based search to make sure the same mistake doesn't exist somewhere else. This has caught more than a few hidden bugs. In all these cases, because the regex is entered into a form field in the text editor, there is no delimiter.

Also, some of my colleagues frequently need to use regexes to configure filtering for various web-related services such as Google Analytics, various PPC campaigns, Google Search Console, and many others. This is not strictly my department, but I've often been asked to help with complicated regular expressions for this. Again, there's no delimiter, because the regex is entered into a web form.

In general, any application that involves entering the regex into some sort of form will not use a delimiter. The idea of a delimiter really only applies to programming.  Programming is, obviously, a major application for regexes, but it's not the only one. For me personally, about 70% of the regular expressions I write wind up getting entered into some form field or other (and therefore do not make use of a delimiter), and about 30% are part of programming code (and therefore do).

**Comment by OnlineCop** [comment]
To add to the list:
- Command-line search-only tools (`grep`, `ripgrep`, etc.) typically need no delimiter (search-and-replace tools like `sed`, `awk`, `perl`, etc. obviously need those delimiters)
- GUI-based IDEs, text editors, SCM merge tools where the Find or Find In Files dialogs need no delimiters (basically, anything not CLI-based like Vim/Emacs)

**Comment by DidierLoiseau** [comment]
I was really confused because I wanted to test a regex from Notepad++, but Regex101 was bothering me with the slashes in a URL, part of a regex. I hadn’t noticed the delimiter option, but even then, it does not make sense to have to select the one of PCRE/PCRE2/EcmaScript/Python flavors for Notepad++.

I suppose if #1821 is implemented, it would more or less cover this use-case (as the spec does not enforce a specific delimiter, from a quick glance), but maybe it doesn’t make sense either since that standard is not implemented by Notepad++ (a quick search seems to indicate [they use the BOOST implementation](https://community.notepad-plus-plus.org/topic/11019/what-standard-for-regular-expressions-is-notepad-using), and there was notepad-plus-plus/notepad-plus-plus#816 to switch to PCRE which got stale and closed).

I must say it looks a bit tricky from a UX perspective since users would probably not know what is the actual flavor of their editor. A generic "Text editor” flavor would be simple, but then it would be unclear which implementation to use.

**Comment by firasdib** [comment]
I think there are too many use cases in order to satisfy them all, so we have to make some sacrifices. 

I don't think this is a big enough issue to warrant a change of this nature (adding a new flavor with no delimiters, etc).
