### ISSUE TITLE
Accented characters are NOT considered "word characters" by regex101

### ISSUE THREAD

**Issue by PO1970** [firasdib/Regex101#1860]
## Bug Description
Regex: 

\b1970-\w
or
\b1970-[^\W]
or
\b1970-[a-zA-Z_0-9]
i.e. the character after "1970-" MUST BE a word character

### Reproduction steps
Input:

1970-?
1970-@
1970-a
1970-u
1970-é
1970-ő

### Expected Outcome
Both "1970-é" and "1970-ő" should match but they do not (at regex101.com).
They   do   in MS Office and LibreOffice (and also a CAT tool).

### Browser
Include browser name and version
Chrome 104.0.5112.80

### OS
Include OS name and version
Windows 10 Home, version 21H1

**Comment by firasdib** [comment]
What flavor are you using? I don't think this is a bug.

**Comment by PO1970** [comment]
Hi, 
Sorry, I'm not an IT expert, I could find out what "flavor" means ("The term "flavor" refers to the regex engine – the syntax and additional properties supported by the particular regex engine...") but I don't think I need that info.
I just happened to find regex101.com that claims itself to be a good place to "build, test and debug regexes", so I gave it a whirl and found out what I reported. 
Okay, let's not call it a "bug", what then what is it?
If regex101.com thinks about regexes in a different way than and MS Office+LibreOffice, I won't be able to use it for my "ordinary mortal" stuff.

**Comment by firasdib** [comment]
Well, let me try to summarize it in short. Regular Expressions are search patterns, and each language or tool implements them in a slightly different way. That means that regular expressions in Notepad++ are not the same as the ones in MS Office, they all use their own flavor, if you will.

For that reason, regex101 supports a series of different flavors (which you can select in the sidebar on the left).

Since you are using MS Office, you are likely going to get the best result by usnig the `.NET` flavor, which is developed by Microsoft.

I hope this helps.

**Comment by PO1970** [comment]
Wow, indeed, so bl...dy simple, .NET is what I need to select first of all, and ...bingo....:O), works fine, cheers.
