### ISSUE TITLE
Unclear/incomplete quiz tasks instructions

### ISSUE THREAD

**Issue by chCharly** [firasdib/Regex101#1866]
I think it would be a lot friendlier if each task give you a full and clear set of requirements to start, imo it's not a good approach to just give you ambiguous hints every time your regex doesn't fulfill a requirement, it feels like a bureaucratic process where every time you try to do it they tell you that you are missing another document. I think having some sort of Unit Tests like list of requirements would be perfect...

_Originally posted by @chCharly in https://github.com/firasdib/Regex101/issues/1562#issuecomment-1214432359_

**Comment by firasdib** [comment]
Thank you for the feedback.

I currently don't have time to baby the quiz, which is why its getting a bit neglected. The quiz runs on simple yaml-file configurations, so if anyone would like to take over maintenance of it, I'd be happy to hand it over.

**Comment by mrkpl125** [comment]
The quiz is extremely vague and unclear. I have been learning and using regex for quite a while but I can't get past even the second task: 'Capitalizing I'. This is not to mention that when I tried substition in the very same tool , that is in the Regex editor - it works. 

For example, the pattern: 

\bi\b

with the replacement value 'I' results in replacing all 'stand-alone'  'i's as well as those with contractions like 'i'm'. You can check it in the editor. 

But the test description keeps complaining: 
Test 7/9: You are not replacing all occurrences of i. I think I would very much like to capitalize every "I" in my sentences! Remember, the engine will only match the first occurrence unless you tell it otherwise!

Hwat? :) 

Another example of extreme vagueness: 

"Find all occurrences of 4 or more whitespace characters in a row throughout the string." 

Ok here you are: \s{4,} . This was my solution, with which ChatGPT also agreed (checked just in case). And yet, here is what we have the test results: 
"Test 10/14: What if there's more than one occurrence?"

So clearly the quiz is not vague, it's simply broken. Or at least the expected result is completely different from what is given by he problem description.

**Comment by rreo** [comment]
@mrkpl125 The emphasis for both hints was "capitalize every "i"" and "more than one occurrence". You had to toggle something to match more than one occurrence. But yes I agree the hints could be made clearer. I had no prior experience in regex when doing this quiz and I resorted to googling the answers to figure out what was wrong. Or perhaps the hint is fine, but the UI for toggling flags should be made more obvious to communicate that it is an important piece of the solution, as newbies and refreshers tend to not know/forget about them.

**Comment by rreo** [comment]
I personally relate to @mrkpl125 at task 15, when I was met with this hint.

![image](https://github.com/firasdib/Regex101/assets/80513066/b9e23445-b765-4053-9610-b206593198f8)

I interpreted it as "my regex is not matching all cases", and I've spent some time questioning my sanity. 

Regardless, I appreciate the quizzes as they help me learn. Cheers.

**Comment by mrkpl125** [comment]
I think the quizes simply lack example tests, so that one could easily see exactly what strings they are supposed to match and not match. Without such tests, it's a bit of guessing and you have to use the regex editor anyway to play with your solution.

**Comment by firasdib** [comment]
Closing this, please open individual specific issues for cases we can work on improving :)
