### ISSUE TITLE
Javascript evaluator is not matching expression when it should

### ISSUE THREAD

**Issue by danpetitt** [firasdib/Regex101#1872]
### Reproduction steps
Using a simple url matching expression:
```
^(https?):(\/\/.*\.[^\/]+)#?(?:[.\!\/\\w]*)
```

With content:
```
https://w.
```

Does not find any matches; however if you used this expression in Chrome or Edge it evaluates to true using simple code like below:
```
const valRE = new RegExp('^(https?):(\/\/.*\.[^\/]+)#?(?:[.\!\/\\w]*)', 'i');
console.log(valRE.test('https://w.')); // Returns true
```

### Expected Outcome
The reg ex tester should, in this example, match the value but it does not.

### Browser
Include browser name and version
Microsoft Edge Version 104.0.1293.54 (Official build) (64-bit)

### OS
Include OS name and version
Windows 11

**Comment by firasdib** [comment]
It looks like the website is functioning as it should. 

Your example is using the `new RegExp` syntax which takes a string, which will be subject to the javascript string handling (which will transform `\\` into `\`, etc).

`console.log('^(https?):(\/\/.*\.[^\/]+)#?(?:[.\!\/\\w]*)') ` will return `^(https?):(//.*.[^/]+)#?(?:[.!/\w]*)` (this is the regex actually being used)

Your escaped dot is no longer escaped, which is why your example works, but not on the website.
