### ISSUE TITLE
Pattern showing error for C#

### ISSUE THREAD

**Issue by FarhanRafi** [firasdib/Regex101#2017]
## Question
Can anybody help me to understand why **\".+\"** & **".*"** these regex are showing pattern errors for C#? 
These regex are working fine in other sites & environments but showing pattern errors in the regex101 website. 
"".*"" is working fine in regex101 site. But backslash as escape character isn't working

**Comment by OnlineCop** [comment]
Due to .NET's delimiters differing from typical `/search/` or `/search/replace/` notation, verbatim `@"..."` are used (see [this article](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/verbatim). This verbatim notation allows the `\` escape character to be entered as you would typically find in other regex syntaxes/flavors, with `\d` or `\w` working the way you would expect.

But because of that, double quotes themselves are not `\"` but instead need to be `""`.
