### ISSUE TITLE
Negative lookahead incorrectly excludes the latest matching character 

### ISSUE THREAD

**Issue by naftalmm** [firasdib/Regex101#2023]
## Bug Description
Match information is not correct in case if test string contains character specified in negative lookahead.
Reproducible on all flavours.

### Reproduction steps
Regexp: ^0+(?!\\$)
Test string: 000$
Match: 00

### Expected Outcome
Match: 000

### Browser
Chrome 109.0.5414.120

### OS
Win7

**Comment by working-name** [comment]
@naftalmm try `\$` inside the negative lookahead if you want to match the dollar sign character. `$` by itself means `end of input` or `end of string` if you have `/m` flag turned on.

**Comment by naftalmm** [comment]
Yes, sorry, that's what I've meant originally.
Anyway, if we use `$` by itself, it's also reproducible with another input:

Regexp: ^0+(?!$)
Test string: 000
Match: 00

Expected Outcome
Match: 000

**Comment by working-name** [comment]
Yes, `$` by itself behaves as expected because it's a metacharacter - it has special meaning for the regex engine. If you want the regex engine to consider it just a dollar sign, you need to escape it by prepending a `\` in front of it, like so `\$`.

In other words, this is not a bug, it's a feature of the regex engine. There are plenty more metacharacters, among which: `.`,`^`,`+`,`*`,`?`...and so on. 

I hope this makes sense.

**Comment by naftalmm** [comment]
Ok, I've got it, thanks!
