### ISSUE TITLE
When the site is down for maintenance, specify the exact date and time it started.

### ISSUE THREAD

**Issue by YousufSSyed** [firasdib/Regex101#2093]
There are lots of people that use regex101 and is critical to their work, it can be a little frustrating when the site is down for maintenance. While I do appreciate there's an estimated time for when it finishes, it should also say the date and time the maintenance began to get a better estimation of when the site would be back up.

**Comment by firasdib** [comment]
Thank you, I will improve the maintenance page for the future.

One problem with having a maintenance page is that existing users, who have visited the site before (and thus have a running service worker), wont be able to run the app, since the service workers only kick in when its offline. If there's a maintenance page, it's technically not offline.

Either way, hopefully this will not need to be repeated in the future.

Thanks for your input and patience!
