### ISSUE TITLE
Empty capture groups.

### ISSUE THREAD

**Issue by bytesaber** [firasdib/Regex101#210]
The summary does show capture group order.   However you have to carefully look to see if there is a missing capture group.
1
2
4
  -vs-
1
2
NO MATCH
4

With an option to use up the extra browser window space, I would find such an option useful.  Another regex tool that I have been using displays this, and I've become used to this for my needs.

**Comment by firasdib** [comment]
Groups are not displayed if they did not take part in the match. Whats the problem?

**Comment by AnomicsAcid** [comment]
This would be useful for me too. I'd like the 'NO MATCH' to appear. Even if it didn't match I still need to write the capture group in my programming for future use when it will match. 

Using bytesaber's example, When I look at the list of matches I will see the third one down and think that is the third match instead of the fourth. It would be less confusing if the third group was accounted for.

A setting that could be toggled for this option would satisfy those who like it or not.

**Comment by firasdib** [comment]
How about this: http://i.imgur.com/B9zTQiV.png ?

**Comment by bytesaber** [comment]
I think that would work.  All it really is, is a request for a visual place holder, so that we can see the breaks in longer match lists.  When you capture 25 items, it can be hard to squint and count which ones matched.  If instead there was a visual break, such as the example you just showed, that should work great.

**Comment by firasdib** [comment]
I understand. I could make it an option for sure. Will keep fiddling with it.

**Comment by firasdib** [comment]
This has been added, and as an option. Will be pushed live soon.

**Comment by firasdib** [comment]
Note: there will be no message if the group is not even attempted to be matched by the regex engine! For example, `/(a)|(b)/` matched against `a` will not show that second group did not participate, for obvious reasons.

**Comment by AnomicsAcid** [comment]
Been enjoying this feature. Thanks!
