### ISSUE TITLE
The Global Flag is not valid for PHP

### ISSUE THREAD

**Issue by dbareis** [firasdib/Regex101#2160]
## Bug Description
* The regexp option is allowed to be set when the language is set to PHP.
* The global flag is removed when you go to generate the code: **$re = '/^\s*(.*?)\s*$/m'**;

### Expected Outcome
I expect the global flag to be missing from the options selection.

**Comment by working-name** [comment]
Hi @dbareis,

Thanks for writing in. PHP is a little special with the global flag because instead of utilizing it, there's a dedicated function for it. So if you look at the generated code, the function name is `preg_match_all()` versus `preg_match()` when you do not utilize the global flag.

Hope this helps!

**Comment by dbareis** [comment]
I suppose that is true :-)
