### ISSUE TITLE
Code Generator for C# creates broken syntax for 'pattern' string.

### ISSUE THREAD

**Issue by ZStoner** [firasdib/Regex101#2186]
## Bug Description

In the `C#` Code Generator, the `pattern` string is using (`/`_Slashies_`/`) Regex syntax instead of (`@"`_Quoted_`"`) syntax.  This is clearly a C# syntax error.
The closest existing generator languages that create this syntax appear to be `PHP` and `Ruby`.  `JavaScript` is similar but different.

### Reproduction steps

* _RegEx Flavor_: `PCRE2`
  + Also repros with flavors: `PCRE`, `ECMAScript`, `GoLang`
  + ***Does not*** repro on flavors: `Python`, `Java`, `.NET (C#)`, `Rust`
* _Match RegEx_: `([[:punct:]]+)|(\w+)`
* _Test String_: `any word character !!!`
* _CodeGen Lang_: `C#`

#### Generated Code (C#):

```csharp
using System;
using System.Text.RegularExpressions;

public class Example
{
    public static void Main()
    {
        string pattern = /
([[:punct:]]+)|(\w+)
/;
        string input = @"any word character !!!";
        
        foreach (Match m in Regex.Matches(input, pattern))
        {
            Console.WriteLine("'{0}' found at index {1}.", m.Value, m.Index);
        }
    }
}
```

#### C# Syntax Error:

```csharp
        string pattern = /
([[:punct:]]+)|(\w+)
/;
```

### Expected Outcome

The `pattern` variable should look something like this for `C#`...
```csharp
        string pattern = @"([[:punct:]]+)|(\w+)";
```

### Browser
Edge 119.0.2151.72

### OS
Windows 11 22H2 (22621.2715)

**Comment by Jamirais94** [comment]
> ## Bug Description
> In the `C#` Code Generator, the `pattern` string is using (`/`_Slashies_`/`) Regex syntax instead of (`@"`_Quoted_`"`) syntax. This is clearly a C# syntax error. The closest existing generator languages that create this syntax appear to be `PHP` and `Ruby`. `JavaScript` is similar but different.
> 
> ### Reproduction steps
> * _RegEx Flavor_: `PCRE2`
>   
>   * Also repros with flavors: `PCRE`, `ECMAScript`, `GoLang`
>   * _**Does not**_ repro on flavors: `Python`, `Java`, `.NET (C#)`, `Rust`
> * _Match RegEx_: `([[:punct:]]+)|(\w+)`
> * _Test String_: `any word character !!!`
> * _CodeGen Lang_: `C#`
> 
> #### Generated Code (C#):
> ```cs
> using System;
> using System.Text.RegularExpressions;
> 
> public class Example
> {
>     public static void Main()
>     {
>         string pattern = /
> ([[:punct:]]+)|(\w+)
> /;
>         string input = @"any word character !!!";
>         
>         foreach (Match m in Regex.Matches(input, pattern))
>         {
>             Console.WriteLine("'{0}' found at index {1}.", m.Value, m.Index);
>         }
>     }
> }
> ```
> 
> #### C# Syntax Error:
> ```cs
>         string pattern = /
> ([[:punct:]]+)|(\w+)
> /;
> ```
> 
> ### Expected Outcome
> The `pattern` variable should look something like this for `C#`...
> 
> ```cs
>         string pattern = @"([[:punct:]]+)|(\w+)";
> ```
> 
> ### Browser
> Edge 119.0.2151.72
> 
> ### OS
> Windows 11 22H2 (22621.2715)

@report.policy.courts.com

**Comment by OnlineCop** [comment]
@ZStoner: POSIX-notation character classes, such as `[[:punct:]]`, are not valid in .NET (at least according to regex101 when the .NET flavor is selected): https://regex101.com/r/DJjPfN/1

The Code Generator is expected to do a minimal amount of changes:
1. Validity of the PATTERN is done at the FUNCTION level (Match, Substitution, etc.), _**not** the TOOLS level_ (like Code Generator).
2. The delimiter specified in the currently-selected FLAVOR is used, _even if it is not valid for the **selected** LANGUAGE_.
3. Each LANGUAGE has its own formula to escape special characters in PATTERN, _taking the **current delimiter** into account_.

.NET stores regex PATTERNs in "quoted strings", so regex101 uses quotes for its delimiters.
- Since .NET supports multiple types of "quoted strings", including string literals (`@"..."`, `@"""..."""`, `@""""...""""`, `@"""""..."""""`), regex101 uses these to avoid problems with things like multi-line patterns.

Using string literals reduces the complexity of escaping special characters in C# strings, so most `\` characters are written without conversion.
- Some flavors, like Java, don't have alternative string types, so each `\` character in PATTERN or SUBSTITUTION is escaped as `\\`.

What you're seeing is an effect of using `PCRE2` _FLAVOR_ but with `C#` _LANGUAGE_, where the delimiter isn't changed to one of C#'s "quoted string" types.
