### ISSUE TITLE
Left sidebar toggle

### ISSUE THREAD

**Issue by PerfectlyFineCode** [firasdib/Regex101#2263]
## Feature
I'd love to be able to toggle the left sidebar due to being in the way most of the time.
It takes so much space and you only configure it one time then ignore it for the rest of the time you play with regex.

**Comment by working-name** [comment]
Hi @PerfectlyFineCode,

I'm going to assume you mean you want a `keyboard shortcut` for it?

Otherwise there's an option that allows you to always collapse the left sidebar but you'd have to click the burger menu to toggle it.
<img width="240" alt="image" src="https://github.com/firasdib/Regex101/assets/16505052/9e8b0b14-2010-49f5-8b45-680bf97e7ce1">

**Comment by firasdib** [comment]
This will be included in a very nice way in the next major version that is being worked on.
