### ISSUE TITLE
First test runs slower than the rest

### ISSUE THREAD

**Issue by Ezbaze** [firasdib/Regex101#2275]
## Bug Description
The first test consistantly runs slower than the rest, even if the next one is exactly the same.
![image](https://github.com/firasdib/Regex101/assets/68749104/a5f56cc2-38ff-4deb-bd43-f0edc56a5a9d)

### Reproduction steps
First 2 tests [in here](https://regex101.com/r/iTucF4/4) but the expresion doesn't matter as long as it's slow enough to see the diffrence in time.

### Expected Outcome
First test should have similar time to one that isn't first :)

### Browser
Chrome - Version 124.0.6367.119 (Official Build) (64-bit)

### OS
Windows 11

**Comment by firasdib** [comment]
This is a side effect that can't be worked around, since the first test also "initializes" and warms up the engine. The subsequent tests don't have to worry about this.

For what it's worth, the time is not super relevant or something you should put too much weight into. If you see one test deviating by a lot, then that's worth investigating.
