### ISSUE TITLE
What exactly is then Exact Regular Expression?

### ISSUE THREAD

**Issue by sunilpandya** [firasdib/Regex101#2291]
## Bug Description
I am testing following Regular expression for testing email
/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/gm
email sunilpandya@hotmail.com sunil.pandya02@gmail.com 
But your Tester says no match found
then what is the exact regular expression, all programmer for php
Regular expression suggest above Regular Expression for PHP

### Browser
Include browser name and version

### OS
Include OS name and version

**Comment by working-name** [comment]
Hi @sunilpandya,

The regular expression you pasted has `^` and `$` which mean start of line and end of line respectively, given that the `/m` flag is on. Therefore you'd have to have a single email address per line, to test if it matches.

If you need further help with regex, please use the social button at the top right and pick your favorite platform. Github issues are more suited for bugs and feature requests rather than help with understanding or coming up with a regex.
