### ISSUE TITLE
Code Generator: JS code doesn't run again on same regex

### ISSUE THREAD

**Issue by bazsi69** [firasdib/Regex101#2300]
## Bug Description
When ran multiple times (e.g. placed in a function) for the same regex string, the generated code doesn't find a match, because the regex.lastIndex is not reset. The generated code should take care of this, e.g. after the "const regex = ..." line, the second line should be regex.lastIndex = 0;

### Reproduction steps
run the generated code multiple times

### Expected Outcome
for the same regex and str arguments, the code should generate the same results when ran multiple times

### Browser
N/A

### OS
N/A

**Comment by Tassanee14** [comment]
A.sai.com
Domain//THE. >>Sai.net@a.sai.com.

**Comment by working-name** [comment]
Hi @bazsi69 

Would you mind updating this fiddle to re-create the issue you describe?

https://jsfiddle.net/bcrn9dz7/

**Comment by bazsi69** [comment]
Done, please check https://jsfiddle.net/bazsi69/he9q6dcy/ (sorry didn't save when I updated the fiddle address you provided)

**Comment by working-name** [comment]
Got it. Yes, you are correct, a zero-width regex like the `\W` in this case, coupled with the re-use of the same `regex` variable will mess up indices. Your fix would work, but so would instantiating the regex variable again, like you do by calling the function with a "new" regex every time (your bottom 3 repeats). 

Even though the regex characters are the same, the fact that you feed the function a regex rather than a variable ends up creating a "new" regex variable for that function's run.

However, the code generator itself doesn't go past the single run, nor does it wrap anything in a function. I would suggest that's a bit out of the scope of the code generator.

That being said, I think this is a great edge case to keep in mind when utilizing .exec(), and it probably won't hurt to include a comment about it in the code generator.

Thanks for bringing this up! ❤️

**Comment by firasdib** [comment]
I will add a comment reflecting this necessity.

Thank you!
