### ISSUE TITLE
Import expression (own but anonymous or foreign) into current account when clicking "Edit title and tags"📝

### ISSUE THREAD

**Issue by scrutinizer11** [firasdib/Regex101#2310]
## Bug Description

The action fails when I click to save an edited expression via _Edit title and tags_.

### Reproduction steps

1. Sign Out
2. Compose a regular expression and make the app generate a link.
3. Sign In
4. Access the expression by going back in history or via the link.
5. Go to _Edit title and tags_ and try to save it.
6. The operation has failed. The message "Unable to save changes. Please try again" on hovering over the red exclamation mark. 

### Expected Outcome
Standard Outcome

### Browser
Firefox 78, Chromium/Chrome 117+.

### OS
macOS 10.9-10.15.

### Additional info.

I'm not sure the anonymous status is involved in the build-up of the error. I'm merely replicating the steps leading to the manifestation.

**Comment by working-name** [comment]
Hello! 

Can you describe what "standard outcome" is? You want the app to "move" the regex you previously saved to now be owned by your account?

#### Cannot edit personal title/tag
That's because you don't have an entry for that regex in your account. I was able to edit these two after I favorited someone else's regex (that's essentially the case here).

#### Cannot delete it
Since you didn't create it, the delete link (which you can always save when you post anonymously and later want to remove) is not under your account. The only way to remove that entry is via its own delete link.

I'm not sure I'd consider this a bug, to me it makes sense that you should not be able to remove someone else's regex. That being said, maybe there is a point to migrating a regex that you just saved while not logged in. That would of course only work before the cookies are cleared.

**Comment by scrutinizer11** [comment]
The standard outcome is actualizing the promise of the prompt when I click on _Edit title and tags_ to save the regex without favouring it, converting a previously anonymous link to a saved one.

**Comment by working-name** [comment]
I see. That function (`Edit title and tags`) exists no matter what URL you visit - should that apply to someone else's regex as well, or only when it is determined your browser created the regex prior to you logging in?

**Comment by scrutinizer11** [comment]
Someone else's regex.

**Comment by firasdib** [comment]
In the new version I will add a new category to the account page which will list all entries, since the existing ones only show the ones that are related to you in some way. When you add tags/titles to others entries, they will be saved to your account and placed under the "all" category.

Thanks for reporting this issue!
