### ISSUE TITLE
Engine Error

### ISSUE THREAD

**Issue by AV3RG** [firasdib/Regex101#2388]
## Bug Description
Unable to initialize the regex engine in Zen browser

### Reproduction steps
Visit the website in Zen browser
I used rust and then whatever regex you choose, the engine wont start

### Expected Outcome
The regex capturing works normally

### Browser
Zen Browser [1.0.1-a.19 (Firefox 132.0.1) (64-bit)]

### OS
Windows 11 23H2

**Comment by working-name** [comment]
Zen browser... promises not to give your data away yet it's fully dependent on and connects to all of the mozilla services including location and so on before you even try to load up an internet page. _Not impressed_.

Tried it out on macOS, same version of the browser, it has no trouble getting whatever wasm it needs to run any flavor I've tried, including rust.

Would you please try and re-create this in a private window, with `Tools` -> `Browser Tools` -> `Web Developer Tools` open on the network tab before you visit the site? That way you can catch any networking or ad-blocking or connection issues. That's generally the culprit. And I mentioned private window because that's usually not going to activate addons. AKA rule out add-on interference, network issues, connection issues, DNS resolution troubles and so on.

Thanks :)

**Comment by working-name** [comment]
Closing for now, but please comment when you had a chance to test things out.

**Comment by AV3RG** [comment]
Hey yea apologies, it ended up working. It was a weird DNS issue on my end and it was occurring on several sites just in Zen
