### ISSUE TITLE
Inconsistency Between Regex101's 'match' Function and Python's re.match Method

### ISSUE THREAD

**Issue by Sofahamster** [firasdib/Regex101#2389]
## Bug Description

In the Python `re` module, there is a distinction between `re.match` and `re.search`. The `re.match` function only searches from the beginning of a string, implicitly adding a `^` at the start of the regex pattern. However, Regex101 does not follow this behavior. Its "match" function behaves like `re.search`, matching substrings anywhere in the input. This can be confusing and might lead users to look for mistakes in their regex patterns when they are actually using the wrong method.

### Reproduction steps

1. Use any regex pattern, e.g. `\d+`.
2. Enter a test string that doesn't match from the start, e.g. `abc123`.
3. Observe that `123` is matched.

### Expected Outcome

The pattern should not match because the function in the left-side pane is called "match", which in Python should only match from the beginning of the string.

#### Suggestions

1. Alter the behavior to follow the actual `re.match` function in Python.
2. Rename "match" to "search" for Python.
3. Implement both "match" and "search" functions, with "match" behaving like `re.match` and "search" behaving like `re.search` in Python.

### Browser
Firefox 132.0.2 

### OS
Windows 11

**Comment by working-name** [comment]
Hi Sofahamster,

The Python version matters, and I say that because the site is being updated for Python 3's re module (see https://github.com/firasdib/Regex101/issues/1464#issuecomment-758062925)

That being said, the example regex would match 123 no matter where it is, because you didn't instruct the engine to only look in the beginning of the string (with `^`) or line (when you turn on MULTILINE flag `/m`). If the `/g` GLOBAL flag is not enabled, then the engine exits after it finds the first `123`.

If that's not the behavior you see on your end, it's very likely that the regex isn't exactly `/123/` in your case, there may be a sneaky `^` in the beginning, or some other regex tokens that artificially make it look like 123 is only matched in the beginning of a string.

If you'd like to discuss regex some more, or would like to request help from volunteers who enjoy writing regexes for people, please pay us a visit in Discord or IRC. The links are under the `social` button, top right.
