### ISSUE TITLE
[Outdated] Query with only "flavor" (without "regex") seems to malfunction

### ISSUE THREAD

**Issue by MasterInQuestion** [firasdib/Regex101#2391]
E.g. https://regex101.com/?flavor=javascript

    Compare:
    https://regex101.com/?flavor=javascript&regex=
    https://regex101.com/?flavor=javascript&regex=1

    See also:
    [ https://github.com/firasdib/Regex101/issues/2090#issuecomment-1902493474](https://github.com/firasdib/Regex101/issues/2090#issuecomment-1902493474)

**Comment by working-name** [comment]
Hi Master,

I seem to remember `regex` being required to reflect other passed arguments in the past. It's also a [deprecated feature](https://github.com/firasdib/Regex101/issues/414#issuecomment-214503178), not quite fully documented as you can see given the [FAQ](https://github.com/firasdib/Regex101/wiki/FAQ#how-to-prefill-the-fields-on-the-interface-via-url). So in that respect it's not malfunctioning because there are no standards, and sometimes behavior changes.

See https://github.com/firasdib/Regex101/issues/2249#issuecomment-2027797142 https://github.com/firasdib/Regex101/issues/1764#issuecomment-1086185706 

Probably not what you wanted to hear. I'll be closing for now since it's not really an active feature, but this **_does not_** mean my point is to discourage conversation.

**Comment by MasterInQuestion** [comment]
Thanks for the info.
    Maybe it should be reconsidered, for general interoperability.

**Comment by firasdib** [comment]
I will investigate this :)

**Comment by firasdib** [comment]
I've fixed this locally, it will be working when the next release is pushed :)

**Comment by MasterInQuestion** [comment]
So it should be "Fixed" then.
    Have you verified the potential test cases?

    Verified fixed as of 2025-04-15.

**Comment by MasterInQuestion** [comment]
I think now better documentation of the "flavor" 's matching would be needed.
    But I cannot edit the wiki.

["FAQ"](https://github.com/firasdib/Regex101/wiki/FAQ#URL-interop): Revise the URL-interop section.
[[
    For most cases, permalink shall work.
    Accessible through the UI or [API](https://github.com/firasdib/Regex101/wiki/API).

    If unfit, try alike query parameters below:
    `https://regex101.com/?flavor=${Flavor}&regex=${RegEx}&flags=${Flags}&delimiter=${Delimiter}&testString=${Text}&subst=${Replacement}`
    .
    Flavor codes:
    [pcre2] PCRE2 (PHP >=7.3)
    [pcre] PCRE (PHP <7.3)
    [javascript] ECMAScript (JavaScript)
    [python] Python
    [golang] Golang
    [java] Java 8
    [dotnet] .NET 7.0 (C#)
    [rust] Rust
    See also:
    [ https://github.com/firasdib/Regex101/issues/1764#issuecomment-1086075580](https://github.com/firasdib/Regex101/issues/1764#issuecomment-1086075580)
    [ https://github.com/firasdib/Regex101/issues/1993](https://github.com/firasdib/Regex101/issues/1993)
    .
    Tech background on URI/URL interop:
    [ https://github.com/MasterInQuestion/talk/discussions/6#discussion-5812048](https://github.com/MasterInQuestion/talk/discussions/6#discussion-5812048)

    Note the content of permalink overrides the setting.
]]
(don't copy-submit; the syntax differs...)
