### ISSUE TITLE
Add "sed" and "awk" to code generator

### ISSUE THREAD

**Issue by federico-piazza** [firasdib/Regex101#272]
It would be nice to have in Code Generator the sample for sed and awk

**Comment by mskadu** [comment]
Or grep - possibly the most frequent command regexps arenused with.

**Comment by firasdib** [comment]
I'd be happy to if someone could clear up the "rules" for each flavor, so I can try to make the output as nice as possible.

**Comment by fedepia** [comment]
@firasdib  As far as I know, grep and sed have parameters to support PCRE regex. In case of grep I think it is grep -P and in case of sed it is sed -r (-E in mac). Also I think there is ssed for full pcre support.

**Comment by devnoname120** [comment]
It would be very useful, it's really painful to escape the regex string for sed.

**Comment by kanihal** [comment]
for sed,  +1
It would be very useful.

**Comment by phdoerfler** [comment]
### sed, awk, grep

I would recommend not doing `awk` and focussing solely on `sed` for now. Awk is a very different beast and `sed` should be installed pretty much everywhere where there is also `awk`.
I would also avoid `grep` for now. Whilst it at first sounds like the goto regex evaluator for the cmdline in my personal experience it has a lot of unexpected limitations when it comes to using it with extended regex.

### sed and macOS

Keep in mind that on macOS the default `sed` is from BSD which has quite different behaviour and flags.
However simply using `gsed` instead of `sed` gives you the ubiquitous GNU sed with all the familiar flags and behaviour.

### sed as a drop-in regex evaluator

My go to flags for GNU `sed` which allow me to basically copy paste RegEx from Regex101 are:

```bash
gsed -r 's/YOUR_REGEX_GOES_HERE/YOUR_SUBSTITUTION_GOES_HERE/FLAGS_GO_HERE;t;d'

# Examples
gsed -r '/Amperage/s/^.+\s+([-0-9]+)\s*$/\1/;t;d'
sed -r '/cd/s/.+;\s*cd\s+(.+)/\1/;t;d'
history 1 | sed 's/^ *[0-9]* *//' |
```

Here is what `-r` does:

```text
       -E, -r, --regexp-extended

              use extended regular expressions in the script (for portability use POSIX -E).
```

As to `;t` and `;d`: Those are sed commands that I dare not touch. I grandfathered these from a more seasoned `sed` veteran and I have had 0 problems with them but a great many problems without them. If you care to learn more, you can do so from [the GNU documentation](https://www.gnu.org/software/sed/manual/html_node/Branching-and-flow-control.html) but be warned.

**Comment by phdoerfler** [comment]
I made a first draft of a `sed` code generator:

```javascript
class Sed extends PureComponent {

  //
  // Proptypes

  static propTypes = {
    regex: PropTypes.string.isRequired,
    flags: PropTypes.string.isRequired,
    delimiter: PropTypes.string.isRequired,
    testString: PropTypes.string.isRequired,
    isSubstituting: PropTypes.bool.isRequired,
    isGlobal: PropTypes.bool.isRequired,
    substString: PropTypes.string
  };

  //
  // Control

  // If you need to manipulate any data, you should preferably do it in a function defined 
  // on the class body here. This could for example be sanitizing data (escaping quotes, etc).

  //
  // Render functions

  render() {
    return (
      <Highlight lang="sed">
        {this._renderCode()}
      </Highlight>
    );
  }

  _renderCode() {
    const { regex, flags, delimiter, testString, isSubstituting, substString, isGlobal } = this.props;

    const codeString = new CodeString();
    
    if (! isSubstituting) {
      codeString.append("This generator only supports substitution. Please update your regular expression accordingly");
      return codeString.toString();
    }

    codeString.append(`sed -r \'s/${regex}/${substString}/${flags};t;d\' <<< "${testString}" `)
    
    return codeString.toString();
  }

}

export default Sed;
```

**Comment by firasdib** [comment]
Wow, I've totally missed this. Many thanks @phdoerfler 

I'll add this to my todo list.

**Comment by Doqnach** [comment]
FYI: `sed -E`, the `-E` is very much a BSD flag: https://linux.die.net/man/1/sed vs https://www.freebsd.org/cgi/man.cgi?query=sed&sektion=&n=1

**Comment by guest271314** [comment]
> **sed as a drop-in regex evaluator**

Can you provide any guidance on how to convert these JavaScript `RegExp`'s 

```
source_outputs
.match(/(?<=Source\sOutput\s#)\d+|(?<=application\.icon_name\s=\s").+(?=")/g)
.find((_, index, arr) => /chromium|chrome/i.test(arr[index + 1]));

sources
.match(/(?<=Source\s#)\d+|(?<=Name:\s).+(?=\n)/g)
.find((_, index, arr) => /monitor/i.test(arr[index + 1]));
```


to `sed` or `grep` format so that I do not have to send the text back to JavaScript from a shell script to match where I will need to send the matched data back to the shell script for further processing?

**Comment by guest271314** [comment]
FWIW I solved https://github.com/firasdib/Regex101/issues/272#issuecomment-731899721 by adjusting the code at https://stackoverflow.com/questions/50666954/switch-puls-audio-record-stream-for-gstreamer-pipeline

```
#!/bin/bash
SOURCE_OUTPUT_INDEX=`pactl list source-outputs | grep -E "(Source\sOutput|media\.name)" | grep Record\Stream -B1 | grep -o -E -m1 "[0-9]+"`
SOURCE_INDEX=`pactl list sources | grep -E "(Source\s|device\.class)" | grep "$1" -B1 | grep -o -E -m1 "[0-9]+"`
pactl move-source-output $SOURCE_OUTPUT_INDEX $SOURCE_INDEX
```

```
./toggle_source.sh monitor 
./toggle_source.sh sound
```

Am still interested in the canonical and correct conversion of the JavaScript `RegExp` to `sed` and `grep`.

**Comment by Doqnach** [comment]
@guest271314 please join the chat (IRC) if you are looking for this type of help. Your question is kind of outside the scope of GitHub issues, and you commented on a long closed issue.

**Comment by firasdib** [comment]
It's in progress. Better late than never: https://github.com/firasdib/Regex101/issues/1230#issuecomment-5133454421
