### ISSUE TITLE
Add setting: Treat each line in "Test String" as a separate string.

### ISSUE THREAD

**Issue by Bartolomeus-649** [firasdib/Regex101#282]
For easy testing of the RegEx on multiple strings there should be an option to treat each line in the "Test String" box as a separate string. That is, an option to convert "Test String" to "Test Strings"

The function should be that the RegEx is applied to each line as if it were the only line in the "Test String" box.
"Match Information" should display info on the line where the caret is (or another way to activate a specific line)

A line should be considered to end at the first \n

**Comment by firasdib** [comment]
Use the `g` flag along with the `m` flag. With anchors in your regex, each line becomes its own test case.

Otherwise you can try the unit tests.

**Comment by 649** [comment]
It is not really the same since expressions like this  `[^>]*` wraps to the next line

**Comment by firasdib** [comment]
In that case I believe the unit test feature is best suited for this. What you're saying is not a bad idea, but I believe adding another feature for a pretty specific problem will make things cluttered, as there are a lot of those feature suggestions which I would also consider implementing.

**Comment by 649** [comment]
I don't really think it is a specific problem that will be solved by this.  It is more like having multiple test data strings and not just one.
There are a lot of upsides to run the RegEx on each line, one for example is that if will be faster in many cases containing look-around, +, * and so on.

**Comment by OnlineCop** [comment]
Isn't this exactly what the Unit Tests on the website are for? Given the same regular expression, each test string is considered individually, where each outcome can be specified (matches, does not match, starts with, contains, ends with, ...). While it may be slightly burdensome to individually add each line into its own unit test, this lets a user specify exactly when a match is doing what it's expected to do, and when making any modifications to the original regular expression will break any of the previous searches.

**Comment by 649** [comment]
With that argument one could completely remove the Test String box since all strings can be placed in the Unit Tests.

The Test String box is for help when you write your RegEx, the Unit Tests are to ensure you don't break anything that previously worked when modifying an existing RegEx.
In the Text String Box you see results as you type while it takes, sometime, several minutes to run all the unit tests. You get visual cues on how the RegEx matches the text in Test String while you only get a fail or OK for Unit tests. You can debug the RegEx and see the steps taken to match text in the Test String box which is not possible with unit tests.
So, no, Unit Tests are not a very good way of handling several Test Strings while writing your RegEx.

My point is that using flags such as `g` and `m` is not enough to get the same functionality as treating each line in the Test String box as separate entity and run the whole RegEx on each line individually.

Take it as a suggestion for further enhancements of the site. Put it in the backlog and prioritize it together with everything else, or ignore it if you feel that's the correct decision.

**Comment by firasdib** [comment]
It's not a bad idea, I will keep it in mind. I've been planning a refresh of the website, we'll see what happens.

Thank you!

**Comment by firasdib** [comment]
> My point is that using flags such as g and m is not enough to get the same functionality as treating each line in the Test String box as separate entity and run the whole RegEx on each line individually.

I don't get this though. The other editors that have an explicit "treat each line as its own string" implicitly use `gm` flags the exact same way.

I'm closing this unless there are any objections.

**Comment by Bartolomeus-649** [comment]
As I said 2015-05-14, any expression that wraps across line breaks does not work well with the options available today.
https://github.com/firasdib/Regex101/issues/282#issuecomment-102152579

**Comment by edswangren** [comment]
> In that case I believe the unit test feature is best suited for this. What you're saying is not a bad idea, but I believe adding another feature for a pretty specific problem will make things cluttered, as there are a lot of those feature suggestions which I would also consider implementing.

I realize this is very and I'm being a bit of a jerk skipping most of the chatter after this response, but if it at all matters (it does not, but still I type) I'm not sure how niche a case this is.

unit tests are tedious and it seems to me the more niche feature. I can't imagine how I would justify using your site as a test host instead of the systems everyone else works with and integrates on. I can't imagine anyone but the most casual of us could either. a third party host for regex testing. that can't perform as well as your test env. I mean... c;mon.

What I need is to paste in and edit a bunch of variations and quickly scan for issues. that's it. that's what the text box would and could provide. I'm not going to dick around with a UI that has me expanding a row to paste in a test to click a button and click once more to accomplish what the Enter key can provide and for no added value whatsoever. I don't get it

but I don't get everything out there, so just my $0.02. I imagine most of us use your site as I do, a tool to help get through those times we're sadly faced with a solution best suited to regular expressions. I open -> test -> hate life -> dick around -> read -> celebrate -> leave. I just want out,

**Comment by edswangren** [comment]
I also don't care because I've fixed your site by way of tampermonkey. I love the new feature, it's perfect.
