### ISSUE TITLE
\u explained incorrectly

### ISSUE THREAD

**Issue by firasdib** [firasdib/Regex101#301]
`[^\u0000-\u007F]+` does not have proper tooltips or explanation

**Comment by nhahtdh** [comment]
`\u` is not supported in PCRE, unless you turn on an option to make it compatible with JS (the flag is not exposed on PHP side)

On Python side, it's quite a mess, due to the treatment of `\u` escape sequence in raw string. The `\u` escape sequence in regex is also just supported in Python 3.3. as explained here: https://github.com/firasdib/Regex101/issues/209

**Comment by firasdib** [comment]
`\u` works as intended in PCRE, but is explained incorrectly in JS-mode: https://regex101.com/r/aJ3zB8/1

**Comment by nhahtdh** [comment]
Oh, this part
```
\u0000 the literal character u0000 (case sensitive)
                             ^^^^^
```

**Comment by firasdib** [comment]
Fixed in v2
