### ISSUE TITLE
Setting timeout to 5000ms does not time out.

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#311]
Values of 1000ms and 2000ms time out as expected. 5000ms does not time out at all, it seems.

**Comment by nhahtdh** [comment]
It times out normally for me: https://regex101.com/r/hM0cA8/1

**Comment by firasdib** [comment]
This was a funny edge case.

What @OnlineCop was experiencing was that the actual regex engine and parsing of the result had finished in 5s (which is what I limit), and then handed off to the browser to paint it on screen. THAT was what was taking all the time, since there was a lot of html being generated.
