### ISSUE TITLE
How to insert regex with unicode on python in regex101

### ISSUE THREAD

**Issue by re4lfl0w** [firasdib/Regex101#345]
I choose JS regex then success regex matching. But in python, No matching.
I have succeed with [가-힣]+
Why??
https://regex101.com/r/dS8sU8/1

I found the answer.
http://stackoverflow.com/questions/393843/python-and-regular-expression-with-unicode
Yes. I'll insert ur. How about in regex101?

**Comment by nhahtdh** [comment]
Unicode escape sequence `\uhhhh` and `\Uhhhhhhhh` are not supported in `re` syntax in Python 2 and Python 3 version < 3.3.

In Python 2, Unicode escape sequence in Unicode string literal **and** Unicode raw string literal is converted to Unicode character. So what `re` package sees is `[가-힣]+`, rather than `[\uac00-\ud7a3]+` for the code `ur"[\uac00-\ud7a3]+"` or `u"[\uac00-\ud7a3]+"`

In Python 3 version prior to 3.3, Unicode escape sequence in Unicode string literal is converted to Unicode character. However, the sequence is left alone in raw Unicode string literal. Combining with the fact that `\u` is not supported in re, as a result, `re.compile(r'[\uac00-\ud7a3]+')` doesn't match Korean character at all.

Unicode escape sequence are only supported in `re` in Python 3.3 and above.

I guess regex101 compiles the `re` package from Python 2, so Unicode escape sequences are not supported.
