### ISSUE TITLE
I don't care about "Catastrophic backtracking"

### ISSUE THREAD

**Issue by willsheppard** [firasdib/Regex101#348]
Could you please provide an option to turn off detection of what you call "catastrophic backtracking"? It really is meaningless for my application and I can't test my regular expression in your site at all. Thanks!

**Comment by nhahtdh** [comment]
It's usually indication that your regex has problem. If you happen to use engines which don't run into such problem (e.g. Go), then I think you should find a proper tester for them, instead of using regex101...

**Comment by firasdib** [comment]
Catastrophic backtracking indicates that there is an "infinite" loop in your regex. If I disable this it will just lock up your browser and you'll have to forcefully terminate it. As @nhahtdh said, this typically indicates a logical error in your expression that you should aim to solve.

**Comment by willsheppard** [comment]
I notice the word "usually" in your reply "It's usually indication that your regex has problem". I was not previously aware that regex101 was not a proper regex tester. I don't believe it's possible to have an "infinite" loop in a regex. I'm using Perl. The backtracking is not a problem for me, except in your tester.

Don't get me wrong, the information on [this page](http://www.regular-expressions.info/catastrophic.html) is very useful. It's just a bit disappointing that this "catastrophic backtracking" error is preventing me from testing my regex. I don't see why it has to be enforced and can't be optionally turned off if it doesn't affect my application at all.

**Comment by firasdib** [comment]
Yes, you can create an infinite loop in regex. Please show me your regex and I will try to find your error and help you understand why this happens.

Perl is probably one of the engines with the most trouble with catastrophic backtracking.

**Comment by nhahtdh** [comment]
> I notice the word "usually" in your reply "It's usually indication that your regex has problem". I was not previously aware that regex101 was not a proper regex tester.

@willsheppard  I'm just another user of regex101, and I look at the list of issues here from time to time to look for interesting bugs. regex101 is a good regex tester for the languages listed (PCRE, JavaScript, Python (2)) but for other languages, the behavior may varies and sometimes have significant difference. That's why I suggest that you use the right tool for the right job, seeing that you didn't mention any language in the original comment.

As for "usually", it's from my experience as user of regex101, but I only remember having run into such cases once or twice (don't remember the test case to reproduce).

> Don't get me wrong, the information on this page is very useful. It's just a bit disappointing that this "catastrophic backtracking" error is preventing me from testing my regex. I don't see why it has to be enforced and can't be optionally turned off if it doesn't affect my application at all.

It's true that some catastrophic patterns work normally in Perl, since Perl has some optimization to reduce the time complexity in those cases. However, PCRE doesn't necessarily implement those optimization - that's why it's inappropriate to insist that the tester should also support those pathological cases. The tester is good for detecting them, though, so it gives you a chance to fix the pattern to remove them completely (providing that you know how to, though).
