### ISSUE TITLE
JS RegEx Substitution Error Alert Issue

### ISSUE THREAD

**Issue by JeremyCrouch** [firasdib/Regex101#354]
I have a simple JS flavor RegEx pattern that has 1 capturing group and 2 non capturing groups. I am using a substitution pattern to display the first capturing group, $1, plus some literal text after that. In the Substitution box if the character after the $1 (ex. $19OK) is a number is gets highlighted red and an error is displayed above it stating that "Subpattern reference does not exist.". However the resulting output in the box below is correct. It is incorrectly grouping the numeral after the capturing group number as part of the capturing group... Attached is a screenshot of the example and the error.

Thanks,

Jeremy
![js_regex_issue1](https://cloud.githubusercontent.com/assets/13983074/9497136/9fc319ce-4be1-11e5-972b-1702c32f7318.png)

**Comment by nhahtdh** [comment]
On a tangential note, the interpretation of `$19` is implementation defined when there are less than 19 capturing groups. You should use `$019` to refer to content in capturing group 1, followed by 9.

**Comment by JeremyCrouch** [comment]
Thanks nhahtdh,

I'm new to RegEx and all of the many online resources I have looked at suggest using $1 for group 1.  I've looked at rexegg.com, stackoverflow.com posts, regular-expressions.info and even the quick references on regex101.com... none of them have ever mentioned this.

**Comment by nhahtdh** [comment]
@JeremyCrouch Firefox and Chrome (the 2 I tested on) interpret `$19` depending on the number of capturing groups the pattern has. However, the specification allows the implementation to always interpret `$19` as referring to capturing group 19. What I suggested is a specification-conforming way to write the regex.

In general, well, you can't tell. You need to check the documentation of the language/engine you are using. Websites which describe the general regex syntax only.mention enough for you to use. They won't go into edge cases, since it varies.

(You still need to test regardless, just to make sure that the code runs correctly on whatever you want to support)

**Comment by JeremyCrouch** [comment]
Thanks nhahtdh, that makes sense. I am using the JS flavor library that comes with MS Office, specifically in Access VBA. Using $19 for group 1 plus a literal 9 works there and my project will never be moved to a different platform, so I think I'm safe. However I do feel this is akin to using an undeclared variable in VBA and relying on the compiler to do the right thing.

I noticed that in the PCRE flavor you can use the substitution syntax ${1}9. This encapsulates the group number and seems safer, but this does not work using JS.

Using the JS regex tester on the regex101 site is there any syntax that does not produce a warning message to substitute a group followed by a literal number?

regex: (^6) Sample text: 6 Substitution: $19 and $019 both produce the warning.

**Comment by nhahtdh** [comment]
> Using the JS regex tester on the regex101 site is there any syntax that does not produce a warning message to substitute a group followed by a literal number?

It's a bug on regex101.

(I did mention that our exchange about `$19` and `$019` in JavaScript replacement string is tangential to this bug report)

**Comment by firasdib** [comment]
Fixed in v2
