### ISSUE TITLE
RegOops

### ISSUE THREAD

**Issue by designdrumm** [firasdib/Regex101#382]
Hello,
I am fairly new to RegEx so please pardon me if this is a novice question.
Using your regex tester (and others) I have come to something I "think" may be a bug in regex.
Consider the following string..

vehicle10-vehicle-name

Running regex pattern:
"/(\w+)([0-9+]+)-(.*)/"

results in..
array(
	1	=>	vehicle1
	2	=>	0
	3	=>	vehicle-name
)

If changed it to.
"/(\D+)([0-9+]+)-(.*)/"

it works as expected.
array(
	1	=>	vehicle
	2	=>	10
	3	=>	vehicle-name
)

Why is the 10 getting split up by the \w?

Best,
Karl

**Comment by designdrumm** [comment]
(\d+) instead of ([0-9+]+) does the same as well.

**Comment by firasdib** [comment]
Hello,

This is because the engine is trying to satisfy the conditions you applied as greedily as possible.

`\w` matches digits or letters, and you gave it a greedy quantifier: +

This means grab as much as you can and give back if have to. So it grabs `vehicle10` but then next token wants at least one digit, so it backtracks and matches `vehicle1`

Hope this helps.

Mvh/Best regards,
Firas Dib

**Comment by designdrumm** [comment]
That makes sense. So how to make reluctant?

**Comment by firasdib** [comment]
Use a shorthand that does not include digits, like `\D` or `[^\d]`

Mvh/Best regards,
Firas Dib

**Comment by designdrumm** [comment]
Ok, that is what I had done. Thank you for the greedy explanation. That was the key.

Best,
Karl
