### ISSUE TITLE
Display railroad diagram

### ISSUE THREAD

**Issue by rugk** [firasdib/Regex101#400]
The only big feature IMO which is missing here is the display of a [railroad diagram](https://en.wikipedia.org/wiki/Syntax_diagram). [Here](https://github.com/klorenz/atom-regex-railroad-diagrams) you can see a JS implementation of this for the text editor Atom.

**Comment by firasdib** [comment]
I personally don't find these very helpful, especially not when the regex becomes complex, but I can understand their appeal.I believe the main issue is that it would not be arbitrary to implement something like this for the more complex PCRE engine, and it would easily become quite cluttered when trying to display all the information.

**Comment by OnlineCop** [comment]
https://github.com/forhappy/RegexKit is one place where this was partially hacked onto the top of the current site. There are several places that this does not work/render correctly, however. Look-arounds. (DEFINE) groups. `\K` operators. The list goes on. While this does work with some very limited cases, there are also may cases where it breaks. I would personally lean toward something that is implemented all the way, or not at all, rather than have something that is patch-worked together and faulty.

**Comment by nhahtdh** [comment]
^ It's hard to actually "read" the visualization. I find a well indented regex much easier to read than that.

**Comment by TWiStErRob** [comment]
#958 mentioned https://regexper.com/

A thought: since it's not a feature yet, and could be a long solution to implement for all flavors, would linking to an external site (deeplink) be a bad thing?

**Comment by firasdib** [comment]
@TWiStErRob Their parser is awful, and won't work for us.

Regardless, this issue has been alive for 4 years and has no thumbs up or any other requests.

Personally, I don't like this feature, and it does not seem widely requested. Therefore, I'm closing this issue. Reopen if you disagree.

**Comment by TWiStErRob** [comment]
Disagree on "does not seem to widely requested" as my feeling is that most people don't know this visualization type exists, or that it makes sense for regex.

Hmm: Actually, how can a regular expression be visualized like this (linear diagram) when most flavors are not actually regular in the Chomsky hierarchy (looking at you lookaround)?
