### ISSUE TITLE
( ( Sed | Grep ) Engine )

### ISSUE THREAD

**Issue by tjt263** [firasdib/Regex101#404]
Hey. Just want to say that I think ***Regex101*** is pretty cool. It's been a great learning tool for me; having (more or less), taught me the majority of what i know regarding regular expressions, aided me in my understanding of various tools & scripts, plus, it's helped me to write dozens of my own over the course of (approximately) the last 2 weeks or so.

Anyway.. I would like to make a suggestion. Actually it's more of a feature request: I just noticed the ***SUBSTITUTION Engine*** hiding down the bottom there and i think that having a fully fledged ***`sed`*** and/or ***`grep`*** Engine/Module/***Component***, (possibly similar to that one) would be a great addition.

Alternatively; they could be new ***FLAVOR(s)*** alongside ***PCRE(PHP), JavaScript, Python, etc.*** 
Or; they could live in the ***TOOLS*** section and perhaps even integrate with the ***Code Generator.***

**Comment by nhahtdh** [comment]
Dup of https://github.com/firasdib/Regex101/issues/196

**Comment by firasdib** [comment]
Thanks @nhahtdh. Unsure how to contact you, so I'll write it here. Please send me an email to contact@regex101.com - would love a quick chat :smile:

**Comment by tjt263** [comment]
@nhahtdh I really don't think it's quite the same..

**Comment by nhahtdh** [comment]
The duplicated issue covers sed, which uses either BRE or ERE. It might be implemented as a tester for BRE/ERE (issue https://github.com/firasdib/Regex101/issues/165) plus code generator for sed. As for full-fledged implementation, I'm not sure whether regex101 should do that or not, since it would require a major interface change to support it. I would imagine it becoming a debugger for sed at that point.

As for grep, it usually implements 4 modes: BRE, ERE, plain text and Perl regex. Again, we see an overlap in POSIX BRE/ERE. As for Perl regex, you can use PCRE, though it's better to test with actual program, since implementations may differ on different systems.
