### ISSUE TITLE
%2B not properly decoded to "+"

### ISSUE THREAD

**Issue by working-name** [firasdib/Regex101#414]
Hello there! Great job with the organizing of issues and stuff :+1: 

Quick wee thing: this [URL](https://regex101.com/?regex=a%2B) should result in `a+` in the regex field, but it seems `%2B` is decoded to a space character.

Happy new year!

**Comment by nhahtdh** [comment]
(Terrible) work-around, for the time being: https://regex101.com/?regex=a%252B

**Comment by working-name** [comment]
brilliant if you ask me :+1: Thank you!

**Comment by nhahtdh** [comment]
@working-name  Well, since this is a bug, expect the link to break at any time...

**Comment by working-name** [comment]
Noted. Will keep an eye out, thank you.

**Comment by firasdib** [comment]
The URL parameters have been deprecated entirely in v2 and will as such not be implemented.

**Comment by MasterInQuestion** [comment]
Seems working as intended now:
    https://regex101.com/?regex=a%2B
    ; "a+"
    (actually shall be already working years ago IIRC...)

    A lot have changed ever since.
    For historical interests:
    https://github.com/firasdib/Regex101/wiki/FAQ/_compare/89023104a14f37b95f6e318cf98f0c1bbdb66525
    [ https://github.com/firasdib/Regex101/issues/292](https://github.com/firasdib/Regex101/issues/292)
