### ISSUE TITLE
add explosive/catastrophic backtracking warning

### ISSUE THREAD

**Issue by Groostav** [firasdib/Regex101#420]
Hey guys, In short I'm wondering if you can get the 'no-match' indicator to tell me how many steps it took to _not_ find a match. Reading the various articles online has me spooked about using the regex `.*?` (or as one of the devs on our team named it `RELUCTANT_NOISE`).

Following my company's story format:

> as a relatively new regex author and having the unfortunate task of parsing this lovely type of document I would like to know if my regular expression is likely to cause explosive backtracking, so that I can properly develop my feature

A couple of articles that have me spooked:
- http://www.rexegg.com/regex-explosive-quantifiers.html
- http://www.regular-expressions.info/catastrophic.html

My use case would be:
1. write a regex containing `.*?`
2. test it on 2 or 3 documents with regex 101
3. provide a very large document that _doesn't_ match the supplied regex, assert that the number of steps taken does not appear to be exponential on the input size. 
4. tweak the document to give the regex a closer match (still no complete match), again asserting that the steps taken to _not_ find a match are not too high

does this seem reasonable?

Thanks guys!

**Comment by nhahtdh** [comment]
Regarding the number of steps when nothing is matched, it's already there on the UI?

![](https://cloud.githubusercontent.com/assets/564162/12611797/34e682d0-c521-11e5-9515-77b63e10a2f2.png)

Regarding `.*?`, for each of them in the form `.*?<pattern>.*?<pattern>.*?...`, it will increase the complexity by a factor of n (so 1 of them will make complexity O(n^2), 2 will make the complexity O(n^3)...), so it's not exactly exponential.

**Comment by Groostav** [comment]
that's not what I'm seeing?

![wat](https://cloud.githubusercontent.com/assets/1680611/12653153/0ca801cc-c5a3-11e5-825a-9a58abd214af.png)

**Comment by nhahtdh** [comment]
@Groostav: The number of steps is generated from the debugging function of PCRE. In your case, since the test string doesn't contain any `y` (which is required by your regex), the match fails immediately during the initial precondition check (which checks for `y` and also probably `x`), before it starts doing the normal matching by traversing the NFA. Basically, the number of steps is probably recorded as 0.

The initial precondition check is not account for in the number of steps taken, since it's an optimization which takes place outside the normal matching operation of the regex and the concept of steps doesn't apply to this initial precondition check.

Depending on the language you are using, if it doesn't support this optimization, you might want to go to Regex Debugger function and check on Disable Internal Engine Optimization checkbox. It will show you the large number of steps taken when running without optimization.

As for the UI, between the 2 options:

- Show the huge number of steps when the regex run with optimization turned off (which is non-default) to indicate that the regex is poorly written and may not work on different engine.
- Show the actual number of steps taken with optimization on (default mode), which aligns with the performance of the PCRE engine in default mode.

I think it makes sense to go for the later one (current behavior), since it's not possible to turn off the optimization in PHP at all.

The UI probably could be enhanced by adding a new option/flag to turn off the optimization, and the engine will show the number of steps accordingly. Whether it is worth implementing or not, Firas will decide, I guess.

**Comment by Groostav** [comment]
Thanks for this @nhahtdh, I wondered if it was something like that, but clearly didn't spend enough time investigating.

Any chance you can add a simple a timeout to said regex engine?

**Comment by nhahtdh** [comment]
@Groostav The timeout function is already implemented (and you can configure timeout period in the settings) - if you write a terrible regex and the string is long enough, it will show timeout error, or a huge number of steps. The thing is, you, as a user, need to provide an input string which reveals the problem.

It would be certainly be great if we can detect the problem from the regex without the input string, but that's going to be a hard problem to solve with gazillion features in PCRE.

Your approach of watching the trend of the number of steps depends a lot on your test string, and I'm not sure how the UI would need to change to support that.

**Comment by Zarthus** [comment]
@nhahtdh @firasdib - shall we mark this issue as wontfix, or do we believe this issue can be enhanced in a meaningful way past the functions already implemented?

**Comment by nhahtdh** [comment]
@Zarthus There are a two problems being discussed here:

1) Display of "number of steps" when the engine fails the match outright. It can be some textual indicator, a number zero or something else. Let's keep the UI consistent.

2) Warning for high complexity regex

The simplest approach is to show some sort of statistics for various test string in one screen. I guess this can be placed in the unit test feature, though I imagine that majority of people don't use it at all.

As for detecting problems in a regex without input string, I don't think it's feasible to implement.

**Comment by firasdib** [comment]
I can't display the amount of steps things take when the match fails outright because it'll be too expensive. The debugger will do this.

I can't warn if a regex is complex, but matching is halted if it goes bananas.
