### ISSUE TITLE
? Quantifier with wrong description.

### ISSUE THREAD

**Issue by cbaldan** [firasdib/Regex101#421]
Hello.

The **?** quantifier description seems incorrect.
**e.g.**
Bla bla bla ((?i)captureGroup)?\s**?**then it continues

Tooltip says:

> Quantifier. Repeat previous token one or zero times, as many times as possible

I think this quantifier is one or zero times, but not as many times as possible.

Regards,
Cleber.

**Comment by OnlineCop** [comment]
Actually, this description is accurate.

`?` will try to match one time. If it can't, it will try to match zero times (and it can ALWAYS match zero times).

`??` will try to match zero times. Then if text after it won't match when that thing is matched zero times, it goes back and tries to match it one time.

Therefore, `?` matching "as many times as possible, giving back as needed" is correct: It _tries_ to match 1 time, and will fall back to 0 times if it can't. `??` matching "as few times as possible, expanding as needed" is correct: It _tries_ to match 0 times, and will fall back to 1 time if it must.

**Comment by cbaldan** [comment]
Well, I still think that last part of the description is deceiving, because it makes it look like you are using asterisk (\*) instead of **?**.

e.g.
**Regex:** Allow only dash in between >(-)?<

This will only find a match with this phrase:
> Allow only dash in between >-<

And the description saying _"...as many times as possible"_ makes it look like you are using the asterisk, meaning that the phrases below should give a match, but they don't:
> Allow only dash in between >-<
> Allow only dash in between >--<
> Allow only dash in between >--<

Am I still looking at it wrong?

**Comment by OnlineCop** [comment]
The "greedy" pattern `Allow only dash in between >(-)?<` should match only the top 2 lines:

    Allow only dash in between ><
    Allow only dash in between >-<
    Allow only dash in between >--<

On the top line, it will _try_ to find the `-` there: it will attempt to match 1 time, (`as many times as possible`). It will not find the `-` character and will try to match 0 times.
On the middle line, it will _try_ to find the `-` character again. It will succeed on its first try, without the need to backtrack.
On the bottom line, it will _try_ to find a single `-` there. It will succeed, and then try to match the next character. It expects a `<` but it encounters another `-` instead. It will backtrack and try to match 0 `-` characters after the `>` character. It expects a `<` to immediately follow, but since it encounters a `-`, the match fails.

The "lazy" pattern `Allow only dash in between >(-)??<` should match the top 2 lines:

    Allow only dash in between ><
    Allow only dash in between >-<
    Allow only dash in between >--<

On the top line, it will _try not_ to match the `-` there: it will try to match 0 times. It will succeed immediately.
On the middle line, it will _try not_ to match the `-` there, but since the next character is not a `<` as it expects, it tries to match the `-` character 1 time and then match the `<` after it. That succeeds.
On the bottom line, it will _try not_ to match the `-` there, but cannot match the `<` so it tries to match the `-`. It cannot match that either, so the match fails.

Now, if there were no `<` character at the end of either of those patterns: `Allow only dash in between >(-)?` vs `Allow only dash in between >(-)??` using the same text, then the behavior acts differently:

    Allow only dash in between ><
    Allow only dash in between >-<
    Allow only dash in between >--<

Both expressions would match the top line as `Allow only dash in between >`
The greedy expression would match `Allow only dash in between >-` while the lazy expression would match `Allow only dash in between >` (without the trailing `-`).
Both expressions would match the 3rd line exactly the same as it matched the 2nd line.

Since there is nothing after the patterns that "forces" the text to backtrack in order to match, the greedy `(-)?` would match the first `-` in all cases, whereas the lazy `(-)??` will never match the `-` character.

From the text of http://www.pcre.org/pcre.txt:

> However,  if  a quantifier is followed by a question mark, it ceases to
> be greedy, and instead matches the minimum number of times possible, so
> the pattern

>     /\*.*?\*/

> does  the  right  thing with the C comments. The meaning of the various
> quantifiers is not otherwise changed,  just  the  preferred  number  of
> matches.   Do  not  confuse this use of question mark with its use as a
> quantifier in its own right. Because it has two uses, it can  sometimes
> appear doubled, as in

>     \d??\d

> which matches one digit by preference, but can match two if that is the
> only way the rest of the pattern matches.
