### ISSUE TITLE
\Z in Python regex does not work correctly

### ISSUE THREAD

**Issue by TZanke** [firasdib/Regex101#433]
Regex: \A[^\t\n\r]*\Z
String: abcd1234\n

Does not match in Python (from code generator)

but matches in https://www.regex101.com

After adding a second newline it works.

**Comment by nhahtdh** [comment]
Confirm on Python 2.7.10

```
>>> import re
>>> p = re.compile(ur'\A[^\t\n\r]*\Z')
>>> test_str = u"abcd1234\n"
>>> p.findall(test_str)
[]
```

Permalink: https://www.regex101.com/r/tM6mJ8/1

I'm quite sure this is because Python flavor is implemented on PCRE engine by only allowing a subset of syntax to pass. Since `\Z` in Python can only match at the end of the string, while `\Z` in PCRE can match before the terminating newline, it results in what you are seeing.

As a fix, `\Z` in Python should be mapped to `\z` in PCRE instead, (though the better solution is to port the Python code instead of running it on a different engine).

**Comment by firasdib** [comment]
Fixed in v2
