### ISSUE TITLE
Incorrect regex validation

### ISSUE THREAD

**Issue by quantumew** [firasdib/Regex101#459]
Using Python `re` module in regex I found what seems to me to be an issue. If I do `re.search("[^\\]\*", "test\*")` I get an invalid expression error. On your site with Python selected it says it is a valid expression. If I add another backslash `[^\\\]\*` then it works with `re` but not with your website. Not a big deal but thought I would point this out. Thanks. Love Regex101 btw.

**Comment by nhahtdh** [comment]
Please use the Code generator feature to get the code for Python:

[Permalink](https://regex101.com/r/uK4xA5/1)

The code generated is 

    import re
    p = re.compile(ur'[^\\]\*')
    test_str = u"a*"
     
    re.search(p, test_str)

which works correctly in Python 2. Note the raw string literal (denoted by `r` prefix in the string literal). `u` prefix has to be removed for the code to work in Python 3.

Anyway, I guess the GUI needs to be enhanced to avoid confusion, since it shows `"` around the string, but no string literal interpretation happens at all -- whatever you enter into the regex input is taken literally.

**Comment by firasdib** [comment]
@nhahtdh Poke me on Slack and we'll figure this out.

**Comment by nhahtdh** [comment]
Let me reopen this issue here for tracking.

**Comment by firasdib** [comment]
Still relevant in v2?

**Comment by nhahtdh** [comment]
Fixed in v2 with the `r` prefix on the GUI.
