### ISSUE TITLE
0*([1-9][0-9]?|1[0-9][0-9]|2[0-4][0-9]|25[0-5]) should match 234 and doesn't

### ISSUE THREAD

**Issue by mojadita** [firasdib/Regex101#461]
I don't actually know the implementation, but trying to match numbers from 0 to 255, I found this regexp and for string 234 it only matches 23 in the regex101 web page.

**Comment by AndrioCelos** [comment]
The first option matches `23` and then ends, so that takes priority.

**Comment by nhahtdh** [comment]
As explained by the comment above, due to the order of alternation, only 23 in 234 is matched. If you want to use the regex without assertion, just place the first alternation at the end to fix it:

    0*(1[0-9][0-9]|2[0-4][0-9]|25[0-5]|[1-9][0-9]?)

We force it to try the 3 digits numbers first, then the 2 and 1 digit number cases.

Normally, this is part of IPv4 validation regex, which are usually anchored to the beginning and the end of the string, so the engine is force to backtrack to check the later branches. Without the anchors, the engine stops as long as it finds a match.

If you are using this for IPv4, do note to remove `0*`, since it denote octal number (the standard allows octal and hexadecimal in IPv4 representation).

**Comment by mojadita** [comment]
Nope, if your implementation does
      this, your implementation does it bad... Checked with java, javascript,
      vim, and C regexps... 
      
      The finite automaton (deterministic or not) compiled for this
      expresion must match either.  If not, you are not implementing
      regexp properly.  No precedence is defined for the | operator in a
      regexp.  Please check against bibliography.
      
    
    
      Luis Colorado
      
      
        
          
            
              Luis

                Colorado
              Hakarinnen
                2, P170
              02100 Espoo,

                FI
              Mobil +358 40 7732177
              Email lc@luiscoloradosistemas.com
              Email luiscoloradourcola@gmail.com
              Email lc@lcssl.es
            
             
            
              
          
        
      
       
    El 03/04/16 a las 17:00, Andrio Celos
      escribió:
    
    
      The first option matches 23 and then ends, so
        that takes priority.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly or view
          it on GitHub

**Comment by nhahtdh** [comment]
> No precedence is defined for the | operator in a regexp.  Please check against bibliography.

There is precedence for `|` in most of the regex engines (JavaScript, Java, Ruby, Python, PCRE) out there, since they do not implement theoretical regular expression by transforming the regex to DFA - they are backtracking engines.

Only engines which implements BRE and ERE does not have precedence for `|` and match the longest string possible. Even so, the implementation may hide a backtracking engine underneath (which means that the complexity is not linear in the length of the input).

**Comment by mojadita** [comment]
Yes, but that single regexp does not match the input string.  The |
operator stands for the union of the two regular languages that match the
subexprs at each side, and that doesn't give any precedence to each of the
regexps at each side.  If i were supposed to test that regexp to run on my
java project, I would touch with differences between your implementation
and java one.  What is clear (for both, you and me) is that the regexp of
the subject should be matched by the one above, but your implementation
doesn't.

By the way, as I said, even with backtracking, the regexp is matched in
java, C, vi, vim and javascript.  If you plan to be consistent with all
these environments, you'll have to cope about this and issue backtracking
in these cases.  As I see, efficiency is not a main target in your project,
so precise results should be a must.  And I don't see any documentation
about precedence in your regexp simulator online.

You can discuss all the day, but as it is not complete, and you defend that
as a feature and not a bug, I'm afraid I will take it of from my list of
bookmarks.

I recommend you to read in the book "Compilers, principles, techniques and
tools", from Aho and Ullman, about the techniques of compiling a regexp to
get a DFA (or you can use the easier NFA instead) to match a regexp and
implement what is shown there.  It's a classical must for anyone interested
in the parsing and matching of regular languages.


*Luis Colorado Urcola*
*Hakarinne 2, N170*

*02100 EspooFI*
*Cellphone: +358 40 77 321 77*

2016-04-08 5:50 GMT+03:00 Hong Dai Thanh <notifications@github.com>:

**Comment by nhahtdh** [comment]
Before you make any claim about the incorrect implementation of regex101, it's actually compiled from PCRE source code to run on browser, and JavaScript is run on the browser's implementation.

Just take a simple test case in JavaScript:

    /a|abc/.exec("abc")

It will output `["a"]` in the console. You can repeat the same test (with the correct method) in Java, Python, Ruby, Perl and you will get the same result.

In Java, if you are using `String.matches`, it implicitly anchors the regex, so the engine must backtrack to make sure that the match is the whole input string. If you use Matcher.find(), you will reproduce the same result as above.

In C, if you are using the POSIX API, it will output your expected output "abc", since they implement the BRE and ERE standard.

The behavior of backtracking engine when dealing with alternation is also documented in http://www.regular-expressions.info/alternation.html. And with all due respect, I suggest that you read [Mastering Regular Expressions](http://shop.oreilly.com/product/9780596528126.do). It describes the behavior of regex engines in popular languages, which are mostly implemented as backtracking engine.

**Comment by mojadita** [comment]
Well, I have read the books you propose, and also the "Compilers,
principles, techniques and tools", from Aho, Sethi and Ullman (which is the
one I recommended you to consult, as it's more directed to the
implementation details for regexp compilers, not to the use of them), or
the "Introduction to Automata Theory, languages and Computation" also from
Prof Ullman and Hopcroft which states all the theoretical details of
regular languages.  I have followed a course in Automata from University of
Stanford with Professor Ullman, and all the references I use don't make
assumptions about the order of operands around the | operator (which itself
represents the UNION of the two regular language SETS, which itself happens
to be commutative and associative)  I am not going to test your simple
case, because the one that matters me was the one I posted (and I have not
anymore that problem).  I am not learning to use regexps, I use them for
more than 30 years up to now.  I feel myself completely qualified to make
the assumption I made, the regexp in the issue I posted is incorrectly
matched for the sorter "23" string, instead of matching the longer "234"
string.  *This is incorrect implementation*, independently of the way you
selected to implement.  And trust me, I'm an expert in the matter, so
before making any assumption on my experience or knowledge, be careful to
first check it with me.  Finaly, I know the regexp I posted was corre ctly
formed and that it should match the longer string I posted in the example.

Don't bother me with other examples that work because I know there are
many, just center on the one I posted that does not, and repair it (if you
want or you feel qualified to do it)  When I posted the issue, my intention
was only to help you find the problem and to inform you of some
missbehaviour in your implementation.

But as your toolkit unqualifies itself to do the right work, I will
unselect it next time, and will use another.


*Luis Colorado Urcola*
*Hakarinne 2, N170*

*02100 EspooFI*
*Cellphone: +358 40 77 321 77*

2016-04-08 8:49 GMT+02:00 Hong Dai Thanh <notifications@github.com>:

**Comment by firasdib** [comment]
@mojadita I such a case you can report your concerns regarding the regex engines to the respective owners.

PCRE bug reports: https://bugs.exim.org/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&product=PCRE
Python bug reports: https://bugs.python.org/

As for the javascript you'll have to contact each browser vendor individually, unless you can get in touch with someone on the ECMA committee and have them change the standard directly.

To clarify for anyone reading this: there is nothing wrong with regex101 and how it executes or evaluates the regular expressions.
