### ISSUE TITLE
Position in pattern show error in regex debugger

### ISSUE THREAD

**Issue by Zjmainstay** [firasdib/Regex101#501]
When I test the pattern `/<div.*?>\d+<\/div>/` to match this content: `<div>ABC</div><div>123</div>`, it show me the below step, but I think it is wrong for the position when it use `.*?` .

![Position in pattern show error in regex debugger](https://dl.kraken.io/web/c8/3531a335599c58c7ada43dd9bd0649/regex101%20debugger.png)

**Comment by nhahtdh** [comment]
One way to think about this is that the engine is trying to match `>` and in doing so, it backtracks on `.*?` implicitly in each step and retry with a larger repetition. The "implicitly" is probably due to the implementation of the engine, which doesn't count such action as a backtracking action.

(I don't actually know the actual reason though - just throw out some guess based on my experience with the internal of regex engines).

**Comment by Zjmainstay** [comment]
ok, thanks!
