### ISSUE TITLE
Negative lookahead false match

### ISSUE THREAD

**Issue by andreaswin** [firasdib/Regex101#505]
Using a negative lookahead regular expression of '(?!.*@example\.com$).*' and a test string of 'somestring@example.com', the website claims the regex matches. This is incorrect as the test string should not match the regex in question.

**Comment by OnlineCop** [comment]
I would argue that this works exactly as intended. https://regex101.com/r/aF7yP9/1

A regex will return as soon as it can return a SUCCESS. It will only "keep trying" while there is a FAILURE, until it exhausts all possible branches.

In this case, `(?!.@example.com$).` begins at the first character of the test string. It encounters an **s** from the word **somestring@example.com** and asserts that it cannot match, at that point, "any character" (which **s** would be considered as an "any character") followed immediately by the **@** character. Since **so**mething does not match "any character followed by **@**", the match at that assertion fails. As it is a _negative_ look-ahead, a failure within the pattern becomes a SUCCESS. And then it matches that trailing `.` since it is allowed to proceed to the next character. This, of course, matches the **s** of **something@example.com**.

If you changed the `.` in the negative look-ahead with `.*`, then you will notice that it finds a valid match after the @ character: https://regex101.com/r/aF7yP9/2

This, again, is because there is no anchor to specify that the text cursor cannot move forward, trying to find future areas where this matches. If you were to throw a ^ (beginning of string) anchor (https://regex101.com/r/aF7yP9/3), then it cannot proceed to the next character, and will consider the entire string to NOT be a match, which is probably what you want.

**Comment by andreaswin** [comment]
My apologies, the bug report unfortunately contained a typo - I am indeed testing with an asterisk at the end, this is the actual regex I'm testing with:

```
(?!.*@example.com$).*
```

Due to the negative lookahead, I wouldn't expect this regex to match 'somestring@example.com'.

**Comment by firasdib** [comment]
@andreaswin Its because the regex isn't anchored. If It fails at one position, it simply tries another where it works.

**Comment by OnlineCop** [comment]
https://regex101.com/r/aF7yP9/4 contains your updated expression. Notice that it still matches, but now only after the @ portion. To see why, take a look at the "regex debugger" on the left, expanding the "match 1 - finished in 325 steps" section.

After it fails to match at the beginning **s** (lines 1-28), it moves to the next character in the string (the **o**), and tries again and again, failing each time.

Now take a look at line 310.

This is where the text cursor starts after the **@** character. It does its usual "match .* to the end of the line and backtrack until it finds something" routine down to line 322, and at that point, it sees that there are no @ characters coming up, and the match succeeds.

So again, you want to have a  ^  beginning-of-string assertion in order for this to NOT match anywhere on the line.

**Comment by andreaswin** [comment]
Thanks for clarifying - ^(?!.*@example.com$).* does indeed seem to be the regex I am looking for here.
