### ISSUE TITLE
Javascript different behavior with an iterated alternation 

### ISSUE THREAD

**Issue by WinterGuardian** [firasdib/Regex101#508]
Hard to explain: https://regex101.com/r/zP6iC1/1 Try in PHP, Python vs Javascript

The second member of the iteration is captured in javascript even if the first should capture '0' 0 times.
This only happen when inside the alternation is iterated. 

Sorry If I don't have the right terminology.

**Comment by nhahtdh** [comment]
This is the behavior of JavaScript RegExp according to the specs - it does not allow a repetition to be empty unless it has to fulfill a minimum number of repetitions. Due to this behavior, the last repetition is never empty if min != max, and it also results in some quirks, such as `(0*|1){5}` only matching an empty string on input `1`.
