### ISSUE TITLE
False explanation for range with double escapes

### ISSUE THREAD

**Issue by DeepSnowNeeL** [firasdib/Regex101#509]
For this regex : (\\+)?([0-9][\\.\\-\\+ ]?){9,15}
We can find this false explanation due to the "-" between the two escape sequences :

> \\-\\ a single character in the range between the following two characters
> \\ the literal character \
> \\ the literal character \

**Comment by DeepSnowNeeL** [comment]
Well my bad, I just need to put the "-" in the end of the [] so it doesn't count as a range

**Comment by nhahtdh** [comment]
Are you using regex101 for Java? The thing is the input for regex is "raw" regex (no string literal escaping rule), so, for example, if you want to escape `+`, put a single `\` before it. When you put double backslash, it will be treated as matching a single literal backslash, rather than escape sequence.

**Comment by DeepSnowNeeL** [comment]
Yeah I miscopied the escaped java regex str..
Thanks :)

Le mer. 6 juil. 2016 11:49, Hong Dai Thanh <notifications@github.com> a
écrit :
