### ISSUE TITLE
Second text field for input/output of escaped regex

### ISSUE THREAD

**Issue by shmidt** [firasdib/Regex101#512]
Could be great if there was a second text field for input/output of escaped regex.
So C/JS developers could paste there regex, change descaled regex in main text field and grab escaped regex from second one.

**Comment by nhahtdh** [comment]
Currently, the regex in string literal is available from the code generator. It probably would clutter the UI, though.

I can see some merit from this if user is able to edit the regex in the string literal directly -- they can see what the raw regex seen by the engine. This would enable us to provide support for Python 2 (which we dropped support in version 2), since [user can be confused](https://github.com/firasdib/Regex101/issues/209#issuecomment-70689715) when they learn that `\uhhhh` is not recognized by re package, and only in string literal.

**Comment by firasdib** [comment]
As @nhahtdh said I believe this will just clutter the UI. You can open the code generator and copy it from there. The new version will support multiple languages.
