### ISSUE TITLE
JQuery is blocked in China.

### ISSUE THREAD

**Issue by Zjmainstay** [firasdib/Regex101#514]
Hi,

There is no doubt that regex101 is the best regular expression test site I have encountered.

But most people got a problem that we can not visit fonts.googleapis.com.

Thus, we were hardly to open regex101 to use it.

So, I hope regex101 can use local font and css, so that we can easily visit and use regex101.

Thank you very much.

**Comment by Zarthus** [comment]
To describe the issue in slightly more detail:

When google fonts is blocked for some reason, the initialization process for regex101 hangs waiting for the fonts to load forever. 

The problem is that the initialization process only ever waits for the first font to be loaded, and instead of failing with a timeout it hangs forever (so fallback fonts are never used or considered). While regex101 works fine with different fonts, if the first one is not available, you will never finish loading.

Local CSS is perhaps not the right way to fix this, and perhaps a global timeout on initialization might be useful, or at the very least consider fallback fonts.

**Comment by nhahtdh** [comment]
Would it be a good idea to switch to [jQuery CDN](https://code.jquery.com/)? [This post](http://edjiang.com/post/97299595332/how-googles-cdn-prevents-your-site-from-loading) suggests it as a solution.

**Comment by hapylestat** [comment]
@nhahtdh not so much, i can remember the times when jQuery site was hacked. So google or local is much more preferred over another CDN

**Comment by DRSDavidSoft** [comment]
How about a check if the $ is defined or not, after attempting to load from Googe APIs? if it can not be loaded from the server, try to use the local version. I have the same problem in my designs from time to time, and this is the solution that I use.

P.S. @Zjmainstay I knew Internet blocking and censorship was a thing in China, but your government also blocks access to Googe APIs and jQuery? What do they think with themselves? :|

**Comment by firasdib** [comment]
v2 does not have jquery as a dependency, and does not make use of any CDN, so this will not be a problem in the future. For now we should just try to work around it.
