### ISSUE TITLE
\E can appear anywhere in the pattern without preceding \Q

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#519]
If the *atom* `\E` appears without preceding `\Q`, it should be ignored, instead of throwing an error like the current behavior.

[Permalink](https://regex101.com/r/qI1rV1/1)

Test cases, from pcretest with PCRE 8.38:

```
  re> /^\Eabc[\E-a]abcde\Efghi/
------------------------------------------------------------------
  0  61 Bra
  3     ^
  4     abc
 10     [\-a]            # Character class of hyphen - and a
 43     abcdefghi
 61  61 Ket
 64     End
------------------------------------------------------------------
Capturing subpattern count = 0
Options: anchored
No first char
No need char
```

```
  re> /[a-\Ed]/
------------------------------------------------------------------
  0  36 Bra
  3     [a-d]
 36  36 Ket
 39     End
------------------------------------------------------------------
Capturing subpattern count = 0
No options
No first char
No need char
```

We still throw error for non-sense like these one, though:

```
  re> /[a-\E\d]/
Failed: invalid range in character class at offset 6
```

```
  re> /(?\E:abcd)/
Failed: unrecognized character after (? or (?- at offset 2
```

**Comment by firasdib** [comment]
Yes, this is correct, and the behavior was intentional by me. I have had a hard time deciding if the site should be 101, ie, help and best practice or simply a direct translation of the PCRE behavior. As you said, a lone `\E` is valid, but its not recommended to use that escape sequence unless you actually mean to end a quote.

What do you think?

**Comment by firasdib** [comment]
Adjusted for in v2 + added warning
