### ISSUE TITLE
When first letter of group name(except only 'R') is 'R' letter, don't match in if statement

### ISSUE THREAD

**Issue by NecZdmr** [firasdib/Regex101#532]
Example;
for text => abc
(?<REASON>a)(?(REASON)(?<s>b)|$) -> This group name does not match in if statement
(?<REASON>a)(?(R)(?<s>b)|$) -> Same group name is matched successfully with letter 'R'.

in this case it consists only group name began with the letter 'R'.

It was tested in the same situation in c# and the problem did not happen.

Browser : Google Chrome

Necati Ozdemir
Natek Bilisim A.S.

**Comment by nhahtdh** [comment]
C# and PCRE are not fully compatible, so there are bound to be differences, and it's what you are seeing here. `(?(R)...|...)` in PCRE checks whether overall recursion condition succeeds or not - and apparently, PCRE treats a pattern without any recursion as success and go on to match `b`.

However, you first test case does unearth a bug in regex101. Currently, regex101 returns error `(REASON) Reference to non-existent subpattern`, but according to pcretest 8.38, it's a valid pattern:

```
$ pcretest -d
PCRE version 8.38 2015-11-23

  re> /(?<REASON>a)(?(<REASON>)(?<s>b)|$)/
------------------------------------------------------------------
  0  36 Bra
  3   7 CBra 1
  8     a
 10   7 Ket
 13  16 Cond
 16   1 Cond ref
 19   7 CBra 2
 24     b
 26   7 Ket
 29   4 Alt
 32     $
 33  20 Ket
 36  36 Ket
 39     End
------------------------------------------------------------------
Capturing subpattern count = 2
Max back reference = 1
Named capturing subpatterns:
  REASON   1
  s        2
No options
First char = 'a'
No need char
data> abc
 0: ab
 1: a
 2: b
data>
```

**Comment by nhahtdh** [comment]
PCRE and C# are not compatible, so there are bound to be differences in behavior. There are still merit in this bug report, though, since it uncovers a discrepancy between the tester and actual behavior of the library.

This is a weird feature in PCRE, where the parser will try to find the nearest named group to the left which matches the prefix specified in the condition.

For example, I construct a regex with named groups starting with 26 English alphabet, appended with a random number, then have a conditional pattern at the end (`T` in this example). The conditional pattern as described by `214   7 Cond ref` points to the 7th capturing group, which is correct.

```
$ pcretest -d
PCRE version 8.38 2015-11-23

  re> /(?<Z7>)(?<O3>)(?<J5>)(?<P0>)(?<V3>)(?<R4>)(?<T6>)(?<L1>)(?<S0>)(?<X7>)(?<Y4>)(?<Q3>)(?<C0>)(?<U0>)(?<F5>)(?<E5>)(?<D5>)(?<B6>)(?<H8>)(?<M7>)(?<A2>)(?<K9>)(?<W6>)(?<G8>)(?<N9>)(?<I3>)(?(T)a|b)/
------------------------------------------------------------------
  0 227 Bra
  3   5 CBra 1
  8   5 Ket
 11   5 CBra 2
 16   5 Ket
 19   5 CBra 3
 24   5 Ket
 27   5 CBra 4
 32   5 Ket
 35   5 CBra 5
 40   5 Ket
 43   5 CBra 6
 48   5 Ket
 51   5 CBra 7
 56   5 Ket
 59   5 CBra 8
 64   5 Ket
 67   5 CBra 9
 72   5 Ket
 75   5 CBra 10
 80   5 Ket
 83   5 CBra 11
 88   5 Ket
 91   5 CBra 12
 96   5 Ket
 99   5 CBra 13
104   5 Ket
107   5 CBra 14
112   5 Ket
115   5 CBra 15
120   5 Ket
123   5 CBra 16
128   5 Ket
131   5 CBra 17
136   5 Ket
139   5 CBra 18
144   5 Ket
147   5 CBra 19
152   5 Ket
155   5 CBra 20
160   5 Ket
163   5 CBra 21
168   5 Ket
171   5 CBra 22
176   5 Ket
179   5 CBra 23
184   5 Ket
187   5 CBra 24
192   5 Ket
195   5 CBra 25
200   5 Ket
203   5 CBra 26
208   5 Ket
211   8 Cond
214   7 Cond ref
217     a
219   5 Alt
222     b
224  13 Ket
227 227 Ket
230     End
------------------------------------------------------------------
Capturing subpattern count = 26
Max back reference = 7
Named capturing subpatterns:
  A2  21
  B6  18
  C0  13
  D5  17
  E5  16
  F5  15
  G8  24
  H8  19
  I3  26
  J5   3
  K9  22
  L1   8
  M7  20
  N9  25
  O3   2
  P0   4
  Q3  12
  R4   6
  S0   9
  T6   7
  U0  14
  V3   5
  W6  23
  X7  10
  Y4  11
  Z7   1
No options
No first char
No need char
```

## Case 1

There is a bug in regex101 in the first case, since regex101 currently rejects it saying that the capturing group does not exist (!), while it actually is there. pcretest 8.38 shows that the regex is compiled and run successfully

```
  re> /(?<REASON>a)(?(REASON)(?<s>b)|$)/
------------------------------------------------------------------
  0  36 Bra
  3   7 CBra 1
  8     a
 10   7 Ket
 13  16 Cond
 16   1 Cond ref
 19   7 CBra 2
 24     b
 26   7 Ket
 29   4 Alt
 32     $
 33  20 Ket
 36  36 Ket
 39     End
------------------------------------------------------------------
Capturing subpattern count = 2
Max back reference = 1
Named capturing subpatterns:
  REASON   1
  s        2
No options
First char = 'a'
No need char
data> abc
 0: ab
 1: a
 2: b
data>
```

## Case 2

This case reflects the quirk in PCRE where it tries to find a capturing group which has the prefix as specified in the conditional pattern. This takes priority over identifying `(?(R)...)` as checking the overall recursion condition, which regex101 mistook it for. As you can see in the debug output, `16   1 Cond ref`, the conditional pattern checks the capturing group 1, which corresponds to the named group REASON.

```
  re> /(?<REASON>a)(?(R)(?<s>b)|$)/
------------------------------------------------------------------
  0  36 Bra
  3   7 CBra 1
  8     a
 10   7 Ket
 13  16 Cond
 16   1 Cond ref
 19   7 CBra 2
 24     b
 26   7 Ket
 29   4 Alt
 32     $
 33  20 Ket
 36  36 Ket
 39     End
------------------------------------------------------------------
Capturing subpattern count = 2
Max back reference = 1
Named capturing subpatterns:
  REASON   1
  s        2
No options
First char = 'a'
No need char
data>

```

## Extra bug

By the way, regex101 fails to reject this regex from the explanation stage:

    (?<EASON>a)(?(REASON)(?<s>b)|$)

[Permalink](https://regex101.com/r/fL5qE2/1)

**Comment by firasdib** [comment]
Well this is completely outrageous by PCRE. Dumbest thing I've seen in a while.

The actual bugs are fixed in v2, but the "partial matching of group names" is not.

**Comment by nhahtdh** [comment]
@firasdib: Agree. I don't see this partial matching behavior with `\g<>` or `\k<>`. I completely agree that we reject partial matching of group names - but don't let it leaks like in case 2, where `(?(R)...)` can have a different meaning if no capturing group starting with `R` is found.

**Comment by NecZdmr** [comment]
Thanks for be interested. I understand and agree. the really interesting thing is Why R letter ?

**Comment by nhahtdh** [comment]
@NecZdmr: Simply put, `(?(R)...)` on its own has a special meaning, and regex101 is coded to handle that.

However, the code doesn't expect that PCRE has a stupid feature where it tries to find a capturing group with the prefix, and this process takes precedence over the special meaning above. Therefore, the bug slips past regex101 validation stage and displays the stupid feature with a wrong explanation in case 2.

The code also doesn't expect PCRE to handle conditional with group name starting with R, so it fails case 1.

**Comment by NecZdmr** [comment]
Right. I understand. Thanks again.

**Comment by firasdib** [comment]
Also see https://bugs.exim.org/show_bug.cgi?id=1873

**Comment by firasdib** [comment]
This has been fixed upstream but no release has been made available yet.

**Comment by firasdib** [comment]
I've upgraded to pcre 8.40 now. This should be fixed.
