### ISSUE TITLE
Java flavor

### ISSUE THREAD

**Issue by moriak** [firasdib/Regex101#54]
Any change of support for java?

Thanks for the great job.

**Comment by nhahtdh** [comment]
@Vincentyification: There are lots of f*ck up things in the reference implementation (Oracle and OpenJDK) of Java regex that wouldn't present in PCRE. For example: negation of negation of character class, definition of `\b` not based on `\w`, capturing group manage to capture stuffs in negative look-around, incorrect retention of captured content, integer overflow in length calculation to limit look-behind, high stack usage leading to StackOverflowError for greedy repetition, ... (CANON_EQ not mentioned here, since it is a buggy and unusable feature). It will cause confusion for user if you use PCRE implementation here.

**Comment by Supuhstar** [comment]
@nhahtdh +1 Great points!

**Comment by asmaier** [comment]
+1 for explicit Java support

**Comment by niccottrell** [comment]
Support for intersections in Java would be great: http://www.regular-expressions.info/charclassintersect.html (Just made a small donation re this feature)

**Comment by Claudweb** [comment]
+1 please add this

**Comment by razalghul** [comment]
+1 will make a donation for this feature.

**Comment by SlainTrue** [comment]
:+1:

**Comment by firasdib** [comment]
The new release will feature a code generator for Java which might help some, alteast with those pesky backslashes. The PCRE engine is still as close as you're going to get, which is likely going to cover it for most of your cases. But so far I have not been able to get the actual engine running. Sorry!

**Comment by xenoterracide** [comment]
me too

**Comment by simonlindberg** [comment]
Hi everybody! I just managed to compile the Java regex engine to javascript by taking the engine from the openjdk (`java.lang.Pattern`, `java.lang.Matcher`, etc.) and running [TeaVM](https://github.com/konsoletyper/teavm) on it. I've sent my work to @firasdib, so hopefully he'll get it working soon :pray: :smile:  

It's currently based on java 8, does anybody know if there is any relevant changes made to the engine since then?

**Comment by OlivierJaquemet** [comment]
@simonlindberg As far as I know, yes there were some changes made to the regexp engine after Java 8 : 
https://bugs.openjdk.java.net/issues?jql=project%20%3D%20JDK%20AND%20status%20in%20(Resolved%2C%20Closed)%20AND%20resolution%20%3D%20Fixed%20AND%20component%20%3D%20core-libs%20AND%20Subcomponent%20in%20(java.util.regex%2C%20java.util.regex%2C%20java.util.regex%2C%20java.util.regex)

**Comment by simonlindberg** [comment]
@OlivierJaquemet Looked at a few and most of them seems to be performance related or regressions i later version. I did find one that might be related, https://bugs.openjdk.java.net/browse/JDK-6609854 , might be more like it.
But since Java 8 still is the most popular version I think in that case there should be multiple java flavors available (all the LTSs perhaps?).
As long as the version is clearly stated I think only Java 8 is a good start! :)

**Comment by firasdib** [comment]
Thanks to the work by @simonlindberg, you can expect regex101 to support java shortly! Keep a close eye on the website the coming days...

**Comment by Gamebuster19901** [comment]
Can this be updated for post java 9?

I'm having issues debugging why my regex is matching everything except for the final match which regex101 says it should be matching.

My regex: `(?<amount>[\+\-]?\d*)(?<die>d\d+){0,1}(?<type>(?>(?!d\d+)[\w\s])*)`

Regex101 states that the string `d4d4d4` should match three times:

![image](https://user-images.githubusercontent.com/7155747/203471236-76cb06bb-c717-42b5-b74e-7fafbd548f86.png)

But in java it only matches twice (video below):

https://www.youtube.com/watch?v=3n-h60_WWjs

**Comment by Unihedro** [comment]
Maybe don't? Your regex is fine (if you want empty strings, since your regex also matches that, so it technically matches 4 times, not 3 (on JDK12):

![image](https://user-images.githubusercontent.com/5595067/204124427-9201a605-e7e4-487c-adfd-9286f4f69456.png)

The problem is not on regex101 but your code. Likely just fix how you're parsing the string and it should be good.

**Comment by Gamebuster19901** [comment]
> 

Apparently I'm either misusing `Matcher.hitEnd()`, or `Matcher.hitEnd()` is just broken.

https://www.tutorialspoint.com/javaregex/javaregex_matcher_hitend.htm

```java
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class TestMain {

	static final String test = "d4d4d4";
	static final Pattern regex = Pattern.compile("(?<amount>[\\+\\-]?\\d*)(?<die>d\\d+){0,1}(?<type>(?>(?!d\\d+)[\\w\\s])*)");
	static final Pattern regex2 = Pattern.compile("d4");
	
	public static void main(String[] args) {
		Matcher matcher = regex.matcher(test);
		do {
			matcher.find();
			System.out.println(matcher.group("die") + " hitEnd: " + matcher.hitEnd());
		}
		while(!matcher.hitEnd());
		
		
		System.out.println("==============");
		
		
		matcher = regex2.matcher(test);
		do {
			matcher.find();
			System.out.println(matcher.group() + " hitEnd: " + matcher.hitEnd());
		}
		while(!matcher.hitEnd());
	}
	
}

```

Which gives the output:

```
d4 hitEnd: false
d4 hitEnd: true
==============
d4 hitEnd: false
d4 hitEnd: false
d4 hitEnd: false
Exception in thread "main" java.lang.IllegalStateException: No match found
	at java.base/java.util.regex.Matcher.group(Matcher.java:644)
	at java.base/java.util.regex.Matcher.group(Matcher.java:603)
	at TestMain.main(TestMain.java:25)
```

In the first example, hitEnd() returns prematurely, and in the second example, it never returns true. Either way, I now know this isn't a Regex101 problem.

Do you think this is a JDK issue, or am I just using hitEnd() incorrectly?
