### ISSUE TITLE
Beta: Vague alert for leaving a page when you've saved something as a library, but didn't permalink it.

### ISSUE THREAD

**Issue by Zarthus** [firasdib/Regex101#560]
When you save something as a library it does not mark it as you having saved your regex, and shows the warning "saved changes might be lost". I would alter this to "You have saved your regex as a library, but you might also want to permalink it before leaving this page" or just remove the warning entirely.

![http://i.imgur.com/4QHRZ9r.png](http://i.imgur.com/4QHRZ9r.png)

**Comment by firasdib** [comment]
I think removing the warning when having saved it to the library OR as a permalink is viable. What do you think?

**Comment by firasdib** [comment]
As it turns out you can no longer modify this alert, and I believe it should be visible in this case as you technically have not saved your regular expression, and might break the expectation of some users that this modal should safe guard them of such an event.

So for consistency, this stays the same.
