### ISSUE TITLE
The replacement window does not always open

### ISSUE THREAD

**Issue by joshuaquiz** [firasdib/Regex101#580]

**Comment by nhahtdh** [comment]
It's the default behavior, since people would want to test their regex to see if it matches correctly first before doing any replacement. Do you have any argument for always expanding the replacement window? Do note that the replacement window will also affect the code generator - it will show replacement code when the replacement window is expanded, and matching code when the window is collapsed.

**Comment by joshuaquiz** [comment]
I think it would be great if when you click the plus minus button for the
replace window it would toggle the up or down of that window.

Hong Dai Thanh <notifications@github.com> schrieb am Di., 23. Aug. 2016
10:51 nachm.:

**Comment by nhahtdh** [comment]
It's a known issue https://github.com/firasdib/Regex101/issues/473, which has been fixed for the new version, but not for the current version.
