### ISSUE TITLE
Add support for javascript u and y flags

### ISSUE THREAD

**Issue by firasdib** [firasdib/Regex101#587]

**Comment by firasdib** [comment]
Note: These need to be feature tested, and can be done by constructing a regex object and checking that `sticky` and `unicode` attributes are not undefined.

**Comment by nhahtdh** [comment]
We need to detect Firefox if version 44 or higher, then we allow them to use `y` flag. Otherwise, show a warning that `y` flag does not follows ES6 specification in Firefox version prior to 44 (where it modifies the behavior of `^`, make it matches at the position of `lastIndex` instead of the usual beginning of string/line).

In Unicode mode:

- We need to recognize astral code point escape sequences: `\ud800\udc00` and `\u{10000}` are equivalent, and `\ud800\udc00` is recognized as surrogate pair for a Unicode code point regardless of whether it's inside or outside character class.
- In the case of `new RegExp("\\ud800\udc00", "u")` (one escape and one raw surrogate), Firefox (haven't tested on other browsers) simply recognize it as *code point* U+D800 followed by U+DC00 and fails to match anything. This is because Unicode mode matches in term of code points, and *code unit* `\ud800` followed by `\udc00` in the input string forms a valid astral code point U+10000, therefore, the sequence of code point `U+D800 U+DC00` can't exist in input string. Surrogate code point only works when the string contains unpaired surrogate, where JavaScript treats them as code point in surrogate range. **tl;dr** Just parse it as 2 separate token, and throw a warning if possible.

**Comment by firasdib** [comment]
So, I've added this in.

I have not added a warning for firefox because parsing versions and adding browser specific warnings is a rabbit hole I am not willing to dive into right now.

Regarding the unicode escapes, I have for now not added any warning of such. Its valid regex but could be a user error which would be nice if the tool could catch.

This is for the future though, basic support is there.

**Comment by firasdib** [comment]
Closing this issue as it has been implemented. Instead open a new issue for enhancement if applicable.
