### ISSUE TITLE
Python backtrack when it shouldn't?

### ISSUE THREAD

**Issue by Ouims** [firasdib/Regex101#595]
https://regex101.com/r/aP5zR6/7

In the debugger, for the first match, at the step 43, $ is being tested.
This is using the /m modifier and since we are at the end of a line, it should validate $ and report an overall match, but after validating $, it backtrack, what am i missing?

**Comment by nhahtdh** [comment]
It fails at step 42, and the search backtracks to try one more repetition and starts testing with `[^.\n]*`

**Comment by Ouims** [comment]
Hum? I'm not agreeing with what you are saying, step 42 is trying to match "\". from "(\.git)?". It fails and since the group is optional, the engine move forward, to the "$" in step 43. Imo $ should match and it should stop there. Are you on the freenode regex channel?

**Comment by nhahtdh** [comment]
Ah, I'm sorry, I derped the numbers:

> It fails at step **43**, and the search backtracks to try one more repetition, which starts with [^.\n]*, as shown in step **44**.

Anyway, when I read it again, it doesn't answer your question, so please kindly ignore it.

Long story short, the problem comes from `gi[^t]`. `[^t]` matches new line (step 36), so you cannot match `$` anymore (step 43). The debugger isn't quite clear in this case, and I just found a bug where the engine fails to highlight the new line character even when you select DISPLAY WHITESPACE option.

**Comment by firasdib** [comment]
So is this a bug or not?

**Comment by nhahtdh** [comment]
It's not a bug, alright. (Though it did helps uncovers some more bugs)
