### ISSUE TITLE
PCRE (php) warning or suggestion when using $ (end of line) and ^ (start of line) without m (multiline flag)

### ISSUE THREAD

**Issue by oxygens** [firasdib/Regex101#610]
PCRE (php) requires the m (multiline) modifier to support the $ and ^ tokens. It isn't obvious and they don't throw an error if used without the modifier flag (at the same time they cause the regex to not match anything).

It would be a nice improvement if regex101 would display a notification/warning about the multiline modifier beeing required, when the $ and ^ are used without it.

**Comment by nhahtdh** [comment]
It's not an error to use `^` and `$` without `m` flag. `^` and `$` matches the beginning and the end of the string in default mode, and people might want to use it with that meaning. PHP's PCRE function also doesn't enable `m` by default - you need to specify it explicitly in the regex. It's user error if they don't know/forget to specify `m` flag when they need `^` and `$` to match the beginning and end of a line.

**Comment by oxygens** [comment]
I didn't say this was an error, and I have clearly delimited this to PHP PCRE, no other Regex flavor.

Please re-read my request of adding a suggestion or warning for $ and ^ beeing completetly ignored.

**Comment by firasdib** [comment]
What you're saying makes no sense,  @oxygens. @nhahtdh explained it properly.

**Comment by oxygens** [comment]
@firasdib 
The whole thing doesn't make sense?

1)
The first statement is just an assertion, which is correct, as confirmed by @nhahtdh.

Try it yourself actually. Add a multiline text, then try to match start and end of line. You won't match anything, without a multiline modifier.

2)
Then I suggested having the interface inform the clueless user about why a multiline modifier is necessary for his ^ $ tokens to have any effect.

What else do you need to understand?

**Comment by Ouims** [comment]
Simply put, PCRE does not require the multiline mode to be used for ^ and $ to be meaningful
Just read @nhahtdh 's explanation.

> Try it yourself actually. Add a multiline text, then try to match start and end of line. You won't match anything, without a multiline modifier.

You are funny AND i'm up for the challenge: https://regex101.com/r/tO2rD5/1

**Comment by oxygens** [comment]
Try this: `^.*$`

**Comment by Ouims** [comment]
I don't need to try, I know what the dot meta characte does, you do not.
The dot meta character, by default, (i.e. not when using the single line mode, /s modifier) matches any character... except newline!
You keep embarassing yourself there, you should have double checked your fact before posting an issue, you should have quadruple checked your fact once you were told you were wrong.

**Comment by oxygens** [comment]
For the third time: I am not posting about an error, and I know how that regex works. 

I did not claim it should work otherwise.
That said, you have a real attitude problem, and you come off as frustrated individual.

For the third time: I am thinking of having an interface tooltip with a suggestion to the user to use the m modifier, for the kind of regex I have given an example of.

You people come off as arrogant indians who really need to show off and don't get simple meanings out of simple English.

I am out of here.

**Comment by Ouims** [comment]
Look:

> PCRE (php) requires the m (multiline) modifier to support the $ and ^ tokens. It isn't obvious and they don't throw an error if used without the modifier flag (at the same time they cause the regex to not match anything).

This is what you said. This is just not correct, PCRE does not require the m modifier to support the $ and ^ tokens. You can try to save the face any way you want, this assertion is simply incorrect, PCRE does not require the multiline mode to be used in any case.

> It isn't obvious and they don't throw an error if used without the modifier flag (at the same time they cause the regex to not match 

Again I'm afraid, this is non sense, the simple fact you are mentioning an error being thrown or not means you do not understand what you are talking about. You can discuss that with anyone knowing PCRE, they will all tell you the same, you can ask on Stackoverflow if you want.

> 
It would be a nice improvement if regex101 would display a notification/warning about the multiline modifier beeing required, when the $ and ^ are used without it.

Again, ^$ aren't related to multiline by any means and again: there is not a single case when using ^$ is wrong, multiline or not. 

Now, when nhahtdh pointed all of that to you, you replied sayin 'i didn't say it was an error'. Here why didn't you try to elaborate on what you meant to say then, since clearly nhahtdh didn't understand? Instead you told him to re-read what you said...

Then the author of this whole project himself (who then re-read carefuly what you said in the first post) came in and told you you are saying non sense and immediately closed the issue so much it's non sense and we're sure of it.

Then you replied with:

> 
> 1)
> The first statement is just an assertion, which is correct, as confirmed by @nhahtdh.
> 
> Try it yourself actually. Add a multiline text, then try to match start and end of line. You won't match anything, without a multiline modifier.

But the assertion isn't correct, as I proved, and in any case: nhahtdh did not confirm the assertion was correct, he simply explained how ^$ works.

Then i joined, restating, trying to be explicit. You asked that we try it so I came up with an example, and then you tell me try with ^.*$ when it's obvious that it won't match accross multiple line since . do not match newline, suggesting that you did not know how the dot work, which is why i replied explaining how it worked and why ^.*$ wouldn't work as you were expecting.
Note that even ^.*$ wouldn't match accross multiple even with the /m modifier, as I said, it's the /s modifier that is required for . to matches newline.

> For the third time: I am not posting about an error, 

You are making these 'time' up, there is no third time because nobody said you were posting about an error..

> I did not claim it should work otherwise.

> For the third time: I am thinking of having an interface tooltip with a suggestion to the user to use the m modifier, for the kind of regex I have given an example of.

Yeah you now want to suggest to use /m for the . to matches newline, but it's /s that is needed for that, so non sense all the ways.

> You people come off as arrogant indians who really need to show off and don't get simple meanings out of simple English.

I'm french, so I'm arrogant and I surrender.
Nah but the arrogance came because YOU refused to elaborate or to face the reality: you were completely wrong, none of what you said made sense, from the usage of ^$ to the dot matching newline with /m when it's /s, but look who were arrogant first:

> What else do you need to understand?



> I am out of here.

 ¯\_(ツ)_/¯

**Comment by nhahtdh** [comment]
@oxygens Gleaming from the (rather unfortunate) exchange above, you want the site to throw a warning when a) the regex contains `^` and/or `$` **and** b) the input string contains line terminator character. Is that correct?

I understand the merit, but I'm not sure whether it may cause harm by misleading newbie about usage of `m` flag.

**Comment by oxygens** [comment]
This is my use case:

$strSomeSQLWithComments (generated by MySQL Workbench):
```sql
/*qaz*/;
/*wsx*/;
/*edc*/;

SELECT * FROM stuff;

/*qaz*/;
/*wsx*/;
/*edc*/;
```

```php
// Remove comments:
preg_replace(/** @lang RegExp */ "/^\\/\\*.*\\*\\$/;/gm", "", $strDatabaseStructure);
```

[https://regex101.com/r/cP9pS9/1](url)

Without the `m` modifier in the Regex above, the Regex wouldn't work.

Generally, the `s` modifier has nothing to do with multiline input (99% of the time) and in this case it would incorrectly match queries, not just comments. As a result, it would be nice if the interface would suggest the `m` modifier with multiline input (specifically for the newbies).

_I understand the merit, but I'm not sure whether it may cause harm by misleading newbie about usage of m flag._
Totally agree that people could be mislead. Maybe if hints were formulated in a special way, they wouldn't.

I'm sorry I didn't make it clear from the get-go, that `^` and `$` were meant to make sure entire lines were matched, for safety (in my use case in particular).

**Comment by oxygens** [comment]
Or maybe suggest both flags, s and m for multiline input.

**Comment by working-name** [comment]
@oxygens in my personal experience I've bumped into cases where I wanted just the first line or last line of the input. For example, [this](https://regex101.com/r/qX4mD9/2).

If I were to use `s` or `m` I wouldn't be able to achieve that.

While I see your point, it may not warrant a site-wide tooltip suggesting said flags, simply because there's other valid uses which do not require those flags, and these use cases are valid in most regex implementations, javascript included.

**Comment by oxygens** [comment]
@working-name 
I delimiting this to PHP PCRE, nothing else, where it would be nice to tell the newbies about the m flag when they have multiline input and/or use the ^ and $ tokens (which imply multiline, or s).

See the 2 examples I have given, and imagine they are only for PHP PCRE.

Thanks.

**Comment by working-name** [comment]
@oxygens but why stop at PHP PCRE if other flavors behave the same way?

**Comment by firasdib** [comment]
I think this discussion has reached an end. The fixed proposed here is ambiguous and will thus be discarded. Thanks for your feedback anyway!

**Comment by Zarthus** [comment]
For archival purposes, I was asked to link this here: https://github.com/firasdib/Regex101/issues/835
