### ISSUE TITLE
ES6 - Handling of surrogate pairs in u mode

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#616]
As per https://github.com/firasdib/Regex101/issues/587, when `u` mode is enabled,  `\ud800\udc00` and `\u{10000}` are equivalent. It works inside or outside character class.

An example of inside character class with range:

```
/[\ud800\udc00-\ud900\udc00]/u.test('񐀀')
> true
```

**Comment by firasdib** [comment]
I don't understand the issue. Do you mean the explanation needs to be improved? Or is there a functional issue where the match does not work?

**Comment by nhahtdh** [comment]
This issue affects both functional issue and the explainer.

Currently, the regex in the example is parsed as `\ud800`, `\udc00-\ud900`, `\udc00` and the explainer detects the part `\udc00-\ud900` as out of order character range and prevents the regex from being ran against the input string.

The correct behavior is:
- In default mode, keep the current behavior
- In `u` mode, parse the character class as character range from `\u{10000}` to `\u{50000}`

**Comment by firasdib** [comment]
Okay. What is the "rule" for matching these surrogate pairs?

**Comment by nhahtdh** [comment]
The rule of UTF-16 is: a high surrogate (`d800` to `dbff`) followed by low surrogate (`dc00` to `dfff`) forms a code point (in the astral planes).

In the regex, you need to treat the following cases as code point:
- Raw high surrogate followed by raw low surrogate. For example, `/𐀀/` (you only see 1 glyph here, but there are 2 code units here in JS string)
- Unicode escape high surrogate followed by Unicode escape low surrogate. For example, `/\ud800\udc00/`
If you see raw high followed by Unicode low or vice versa, just parse them separately.

**Comment by firasdib** [comment]
I really don't know enough about this to properly implement it I'm afraid.

**Comment by working-name** [comment]
Here's something that [might help](https://r12a.github.io/apps/conversion/conversionfunctions.js). 
``` javascript
if (0xD800 <= cc && cc <= 0xDBFF) { // start of supplementary character
  highsurrogate = cc;
}
```

With this `u` flag in JS I have a feeling [this kind of thing](https://jsfiddle.net/op4c08s1/) will come up quite a bit.

**Comment by firasdib** [comment]
@working-name How is it handled? Do you add the two hex values together?

**Comment by firasdib** [comment]
Bump. Anyone knows? @nhahtdh @working-name

**Comment by working-name** [comment]
@firasdib I looked into it, but it's definitely above my pay grade. It gets even more complex when you try to separate unicode characters that are immediately after a regular character, such as an accent meant for the previous character or something like that: `foo\u0305` = `foo̅`. 

I believe the main issue is that JS can't handle it internally as it uses a different character encoding so you have to simulate UTF16 or what have you, which is where it gets hairy.

For the purpose of matching however, we might be able to get away with codepoints rather than having to go the surrogate pair way.

Hopefully this sparks some ideas: https://jsfiddle.net/op4c08s1/1/

**Comment by firasdib** [comment]
This should be working correctly after the next update :+1:
