### ISSUE TITLE
(?:) Does not create a non-capturing group

### ISSUE THREAD

**Issue by Hukacikanaka** [firasdib/Regex101#636]
Maybe not the best example, but the regex `^(?:(\w+[\s]?)*)\.` causes catastrophic backtracking when executed against `Most certainly something is wrong; catastrophic backtracking will occur.`

While the regex `^(?>(\w+[\s]?)*)\.` will fail in 21 steps with the same input.

**Comment by OnlineCop** [comment]
I don't understand how the topic, `(?:) does not create a non-capturing group`, relates to the catastrophic backtracking that's going on. Could you elaborate?

https://regex101.com/r/uF3hW9/1 (current site)
https://37.139.17.130/r/Xbcw64/1 (beta site)

Both correctly show catastrophic backtracking as you indicate. You've got a non-capture group (which in this particular case, is not contributing anything to the expression since there are no alternations or quantifiers at the end of it), along with a capture group within it (which will only keep the LAST word and optional trailing space that it encounters if it succeeded without the catastrophic backtracking).

This looks like it is working as intended, since no capture (or non-capture) groups should be returned if catastrophic backtracking occurs. Unless I'm missing something here.

**Comment by Hukacikanaka** [comment]
The catastrophic backtracking is related in that, the non-capturing group will stop the regex from backtracking in case it hits an invalid symbol within the sentence. Since, if it hits an invalid symbol, I don't want the regex to try any other possible matches because it should already be apparent that the whole sentence is invalid.

**Comment by firasdib** [comment]
@Hukacikanaka You're thinking of atomic groups, `(?>)`, not non-capturing groups `(?:)`. There is no error here.
