### ISSUE TITLE
Add ability resize horizontal and vertical panes freely

### ISSUE THREAD

**Issue by TWiStErRob** [firasdib/Regex101#639]
Forking off #638's short note.
```
[11:20] <+Zarthus> what did you mean with the last comment, resizable panes?
[11:21] <re101-wasp-559> I'm able to move vertical separator between the 2nd and 3rd third on the live site
[11:21] <+Zarthus> ah, i see
[11:23] <re101-wasp-559> and I would expect to be able to resize the subpanes on the right side too, for example: I already have a regex and looking at why it doesn't match. in that case I would look at match information and explanation
[11:23] <+Zarthus> re101-wasp-559: by collapsing other times they do resize a bit
[11:23] <+Zarthus> it's definitely more of a quality of life change there, but a good suggestion nevertheless
[11:24] <+Zarthus> I think http://i.imgur.com/FJEZN5u.png is plenty of room in general
[11:24] <re101-wasp-559> yes, but I get 50-50, which is not what's needed: match information is more important than explanation (for me), but I can't tell this to the app right now
[11:25] <+Zarthus> collapsing both windows gives me plenty of room
[11:30] <re101-wasp-559> Zarthus: **https://postimg.org/image/9hdgqm5zx/ is an example when matches are more important than explanation. I have to scroll to see all matches, but if I was able to resize it would probably fit.**
[11:31] <+Zarthus> re101-wasp-559: yeah, I agree with that point, it's worth putting that in your issue somewhere / making a new one
```

**Comment by firasdib** [comment]
I can see some merit in this, but I wonder how I would implement an intuitive UI that allows for this in conjunction with the current behavior.

**Comment by TWiStErRob** [comment]
The usual line that lets you grab the border/space between the resizable panes.
The current live version has this invisible-till-hovered bar:
![image](https://cloud.githubusercontent.com/assets/2906988/18815227/31333aa8-832a-11e6-8229-853e500426ca.png)
the new version has the same amount of free space:
![image](https://cloud.githubusercontent.com/assets/2906988/18815231/4134c7dc-832a-11e6-8c6f-e17420d1b013.png)
I like that the feature is hiding until hovered, it makes the UI clean.

If you question was geared towards the collapsible panes in right column then I guess simply disable (not show on hover) the resize bar when at least one side of it (above/below) is collapsed. Though the case when there's one collapsed and one expanded can be handled with a trick, and I think it's intuitive as well: quickly expanding the collapsed pane to 0 height and then the rest of resizing is the same as if it was expanded already. Similarly if the user drags too much toward an expanded, so much that it would be useless then you can automatically collapse the small pane (the user already did the collapse animation for you).

If neither of the above, then please expand on your concerns as I likely didn't get your question.

**Comment by firasdib** [comment]
The horizontal resizing of the right hand side has been removed because I did not like the way it functioned in the current version and I could not think of a decent way of doing it at the time. Seeing as how I considered it low prio, I left it out.

For the 3 stacked items inside the right hand side, I personally want to maintain the current behavior where they share the space. Giving the user control to weight them might be an alternative, that is, having two taking up 30% and one 40% for example or whatever the user might want.

Again, I'm not sure of the specifics or how it would work. I don't want the UI to become cluttered and confusing. Things like these require careful UX work.

**Comment by TWiStErRob** [comment]
It sounds to me that you consider free resizing mutually exclusive to the current beta's expanding behaviour. In my view it's not, the default is whatver percentages you figure are good and then there's that hidden magic line you can grab and move. I agree most people won't use, but when a user looks for it and doesn't find they'll be disappointed, like I was, but they won't necessarily be as vocal about it as I am. (If you're worried about the user doing some wierd sizing and not being able to go back: Total Commander, IDEA, a diff program and some other apps have the notion of double-click the resize bar to reset the default separation ratio.)

> I did not like the way it functioned in the current version

Do you mean the "keep pulling" percentage? I thought that was an interesting idea, never seen it before.

> I don't want the UI to become cluttered and confusing.

You always have the option of creating an advanced setting that can be set, even if the resizing doesn't work as nice as you would like, it may still be useful. Sometimes "good enough" is better than nothing.

---

`<rant>`What I don't understand is why newer releases keep removing features. I honestly ask this, not just you, but Google and other companies are doing it too. There are good working features and they do a "redesign"/"rewrite" and some old features are gone without even a remote hint of a replacement. I guess I could just write a stylish style for myself where I can manually edit the numbers in this case.`</rant>`

**Comment by firasdib** [comment]
No, I don't think its mutually exclusive, nor am I necessarily opposed to it.

What I'm saying is there is a certain UI and UX work that needs to be done which is not trivial and could be quite significant.

And to answer your rant, its typically because something adding more complexity than its worth for the few people using it.

**Comment by JMichaelTX** [comment]
I very much would like to see you return the resizing of the window panel widths, by drag-and-drop of the vertical lines between each panel.  As I expand the browser window, you auto show the left control panel, removing width from the other panels, defeating the purpose of expanding the window.
I often need to expand the Explanation Panel while keeping the width of the Editor Panel the same.

Thanks.

**Comment by xstable** [comment]
+1

**Comment by JMichaelTX** [comment]
> What I'm saying is there is a certain UI and UX work that needs to be done which is not trivial and could be quite significant.

Any progress on this?  I really, really miss having this feature.  Not having it actually slows me down because I'm having to constantly go into settings to toggle the display of a panel.  And then even when the panel shows, I often have to maximize my window, just for a moment, to see everything without having to scroll down a lot.

I'm not sure what you changed in the new version that made it so hard to keep the manual resizing.  Could you please explain?

**Comment by firasdib** [comment]
The horizontal resizer has been brought back, with a simplified behavior.
