### ISSUE TITLE
Invalid substitution backreferences are portrayed as valid

### ISSUE THREAD

**Issue by TWiStErRob** [firasdib/Regex101#648]
Some flavors use `\N` and others use `$N` for substituting captured groups.

The Substitution input box is not aware of the flavor being used and highlights invalid ones:
![image](https://cloud.githubusercontent.com/assets/2906988/18867070/07b64d62-84a3-11e6-9276-8cff4dce4b15.png)

what's even worse is that the replaced string also substitutes those with values of the captured groups:
![image](https://cloud.githubusercontent.com/assets/2906988/18867080/10e5fbe4-84a3-11e6-957b-3a3b41f8d5ed.png)

Example: https://37.139.17.130/r/qKqAA4/1

Generated JS code:

``` js
const regex = /a(b+)c/g;
const str = `abc
abbc
abbbc`;
const subst = `dollar: \$1, slash: \\1`;

// The substituted value will be contained in the result variable
const result = str.replace(regex, subst);

console.log('Substitution result: ', result);
```

output when run in Chrome's JavaScript Console:

```
2016-09-27 11:13:34.578 VM131:10 Substitution result:  dollar: b, slash: \1
dollar: bb, slash: \1
dollar: bbb, slash: \1
```

**Comment by firasdib** [comment]
From my side this has been intentional because I typically view substitutions as something you do to get a result on the site, and not something you use in code, even though this is clearly not deterministic. There was a discussion regarding this here previously: https://github.com/firasdib/Regex101/issues/578

**Comment by TWiStErRob** [comment]
> I typically view substitutions as something you do to get a result on the site

You can't assume that everyone does that, I'm pretty sure there are users who generate the code and use it in production, maybe even without testing, which could lead to invalid output as demonstrated above. Even if they don't generate the code they could just copy the "substitution" input box contents and use it. And it simply doesn't work.

I may be wrong but the name and feel of your site is geared towards beginners in regex who may not be aware of these discrepancies between languages/flavors. I also feel that one of the intents is to help people get on board with regex, not scare them off with inconsistent behavior between the site and their preferred language.

**Comment by firasdib** [comment]
Yep, you're right. I'll get to this when I have some time over.

**Comment by TWiStErRob** [comment]
I guess you could keep your version of substitution syntax and implement the flavors' as well, letting the user choose to use the site as a text editor with great regex support or just an IDE with compliant syntax.

**Comment by connorshea** [comment]
Hey, I just ran into this. I was trying to figure out how to use a captured value and the guide suggests that `$1` would be the first capture group, but that doesn't work (at least not in JS) because JS uses `\1` instead of `$1`.

For example, I was trying to match any string where the first and last characters were a vowel and also the same character. e.g. `aba` should match, `eba` should not.

Using `^(a|e|i|o|u).*$1$`, it doesn't work. What _does_ work is `^(a|e|i|o|u).*\1$`

**Comment by working-name** [comment]
Hi @connorshea, which guide suggests that? The quick reference? 

Also, it seems you're not doing a replacement, you're just using a reference to contents of group 1 within a regex. `$` is not a metacharacter in regex, only in substitution, and even so, only in some flavors. Hope this makes sense, and please let me know if I misunderstood.

**Comment by connorshea** [comment]
@working-name the quick reference, yeah. Perhaps I'm misunderstanding, but the quick reference seems to suggest that `$1` and `\1` are equivalent for PCRE. In JavaScript, the quick reference doesn't show `\1` at all despite it working fine, and `$1` doesn't seem to work in either PCRE _or_ JavaScript. If `$1` only works in specific contexts, IMO that should be clarified.

**Comment by working-name** [comment]
@connorshea I see where the confusion is, but I'm not sure how to address this. Maybe I should mention in its description that it is a replacement entity rather than a regex entity. If you want to confirm, in the quick ref you can select **✂︎ substitution** and you'll see that `$` shows up there.

Allow me a minute or so to explain what's going on:
`$` used as a [regex token](https://regex101.com/r/9VXXui/1) can mean one of two things:

1. end of input, when no `/m` flag is present.
2. end of line, when `/m` flag is present.

`$` used as a [substitution token](https://regex101.com/r/9VXXui/2) usually precedes the number of the capture group you wish to pull into the substitution. This is supported in some flavors, but others will use `\` instead of `$`. But the meaning is the same.

**Comment by firasdib** [comment]
I have now implemented language specific tokenizers, which follow the rules for each specific language to the letter. If they have a bug somewhere, or behave unexpected, please open new issues then.

This will be pushed in a few days with the huge update thats incoming. So please be patient.

**Comment by TWiStErRob** [comment]
😍 🎉, yay!
