### ISSUE TITLE
Format Regex adds extra newline after open paren

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#656]
Enter a regex containing open parens (capture, non-capture, atomic) and hit 'format regex'. Most of the generated output contains one blank line below the parentheses.

**Comment by firasdib** [comment]
I'm considering removing this feature. It don't reckon many users use it and its non-trivial to implement in a meaningful way.

**Comment by TWiStErRob** [comment]
I, for one didn't use it yet (maybe because I didn't remember Java supported it); so removal may be fine by me. However doesn't your site exists because regex is a non-trivial language and it requires non-trivial tools so people can grasp it better?

Based on our discussion yesterday I would say we need some people who deal with a lot of regexes (hint: #regex) to give some rules on what "meaningful" would be. They should be able to give clear rules, which may be simpler to implement, than guessing what would look good. I also suggest to ask a question at http://programmers.stackexchange.com/questions/tagged/regular-expressions

**Comment by OnlineCop** [comment]
I tend to use this feature frequently. Although it doesn't format it
exactly the same as I would, I do use this as a starting point to see large
regexes broken apart in the right places.

I point people toward it on #regex but you're right: it's not frequently
used. People don't know where it is, what it does, or really much about it.

**Comment by TWiStErRob** [comment]
@OnlineCop can you phrase your formatting rules in a few sentences? Or is it more intuition?

**Comment by OnlineCop** [comment]
I separate groups from one another: `(one)(?:two)(?=three)` would become

    (one)
    (?:two)
    (?=three)

Items outside of groups are not broken apart from the groups: `(one)*(?:two)[^\t ]*$\r?\n(?=three).*` would become:

    (one)*
    (?:two)[^\t ]*$\r?\n
    (?=three).*

Alternations within groups will break the group across multiple lines. I personally prefer the `|` to be at the start of the line, indented to match the level of the group, although the current syntax has the pipe at the end of each alternation to save vertical space: `(one|two\stwo.*two|three(?=four|five|six))` currently looks like this:

    (
      one|
      two\stwo.*two|
      three
      (?=
        four|
        five|
        six
      )
    )

while I personally prefer it like this:

    ( one
    | two\stwo.*two
    | three
      (?= four
      |   five
      |   six
      )
    )

Comment blocks `(?# some comment here)` should not format text at all: whitespace (including newlines and indentation) should remain the same, although if a comment immediately follows another group, it throws the indentation off:

    (one)(?# Matches
             a single word)(?:two)

would become formatted to

    (one)
    (?# Matches
             a single word)
    (?:two)

I find that perfectly acceptable and it should be up to the user to correct it.

**Comment by TWiStErRob** [comment]
I like that indent style. What happens if there's a mix of things that cause indentation? `(one|two(\stwo)(.*)two|three(?=four|f(ive)|six))` (`f(ive)` is intentional)

**Comment by OnlineCop** [comment]
I'm just eyeballing this, so I may have missed something, but that should just become

    ( one
    | two
      (\stwo)
      (.*)two
    | three
      (?= four
      | f
        (ive)
      | six
      )
    )
    ( f
      (ive)isintentional
    )

When you hit the format link, all whitespace is ignored, so ` is intentional` with a leading space before the word `is` would consider all those spaces to be part of the formatting, and will be reformatted (removed if necessary).

The exception is when the space is made non-trivial, such as `\ ` or `[ ]` or somehow otherwise denoting that it is a `\x20` character that needs to be matched.

In the last group, `f(ive) is intentional`, the `(ive)` should be on its own line and indented, but the `isintentional` should be on the same line as it would follow the same rule as in my earlier post.

**Comment by TWiStErRob** [comment]
*Sorry, I didn't mean to include the "intentional" part; that is outside the inline code block, however hardly noticeable :) It's good that you included it because it's an example of nested groups.*

So your rules can be translated into rules as follows:

	```
	(one|two(\s(tw)o)(.*)two|three(?=four|f(ive)|six))
	```

* break before every group (= opening parenthesis)

	```
	(one|two
	(\s            # new line added
	(tw)o)         # new line added
	(.*)two|three  # new line added
	(?=four|f      # new line added
	(ive)|six))    # new line added
	```

* break before every alternation (= pipe)

	```
	(one
	|two    # new line added
	(\s
	(tw)o)
	(.*)two
	|three  # new line added
	(?=four
	|f      # new line added
	(ive)
	|six))  # new line added
	```

* any new line inside an alternative increases indentation

	```
	(one
	|two
		(\s     # 2nd alternative
		(tw)o)  # 2nd alternative
		(.*)two # 2nd alternative
	|three
		(?=four # 3rd alternative
		|f      # 3rd alternative
			(ive)   # 3rd alternative + lookahead's 2nd alternative
		|six))  # 3rd alternative
	```

* any group within a group is indented

	```
	(one
	|two
		(\s
			(tw)o) # nested in group starting with (\s
		(.*)two
	|three
		(?=four
		|f
			(ive)
		|six))
	```

* group ending is put on a new line (same indent as opening)  
**if** it has a group or alternation inside

	```
	(one
	|two
		(\s
			(tw)o
		)         # here
		(.*)two
	|three
		(?=four
		|f
			(ive)
		|six
		)         # here
	)             # here
	```

* add space after group start + align alternatives with group start  
**if** it the group has group or alternation inside

	```
	( one         # added space
	| two         # aligned to "one" 
		( \s      # added space
			(tw)o #- not aligned, still indented
		)
		(.*)two
	| three       # aligned to "one"
		(?= four  # added space
		|   f     # aligned to "four"
			(ive) #- not aligned, this is just a coincidence
		|   six   # aligned to "four"
		)
	)
	```
@firasdib I have code to do this formatting based on your token model, but there are some cases where it's not defined yet.
@OnlineCop how about `/(?: (group1) | (group2) | ((nes)|(ted)) )/x`, where would you put `|(` on one line?

**Comment by firasdib** [comment]
This feature has been deleted for now. Once we manage to create a good formatter it can be re-added.

**Comment by firasdib** [comment]
Nobody seems to miss this feature. Ciao!
