### ISSUE TITLE
Feature Request: Allow URL/Bookmarks to pick flavor again

### ISSUE THREAD

**Issue by HatBeardMe** [firasdib/Regex101#662]
Please allow a shortcut such as `https://regex101.com/#python` to automatically pick the python flavor.

Also, any way to not automatically pick `g` flag?

**Comment by OnlineCop** [comment]
The `g` flag was actually one of the highest-requested features, so we added it since most people tend to want it on by default.

**Comment by HatBeardMe** [comment]
Cool, I can see why. How about the flavor and flags are stored when I'm logged in or by cookie if I'm not?

**Comment by firasdib** [comment]
Yes, the `g` flag is because a lot of users intuitively expect a regex match to be global. I got a lot of questions about this.

Setting the flavor from the URL can be done, its not too much work. Re: saving flavor/flags to cookie is generally a bad idea. User might be confused as to why this is happening or something along those lines. I think most people expect a new tab to be a fresh page and nothing else.

However, my concern with setting flavor from the URL is that it could be confusing. It will overwrite whatever has been set by a permalink, so a permalink created in PCRE with a querystring indicating Javascript, will run in JS instead of PCRE. This is somewhat a logical expectation but might stump some users. I'm not 100% sure. 

What is your use case? Simply one less click?

**Comment by TWiStErRob** [comment]
Can't you simply ignore the hash params if the url is a permalink? That seems intuitive too, since the saved data should win. In case of @HatBeardMe's example there's no saved data, just empty slate. Btw, is there some docs for possible urls or there's no action that can be passed in there (other than library). I think whatever `filterFlavors` does should work in the editor flavor too.

**Comment by HatBeardMe** [comment]
Thanks @TWiStErRob for clarifying.

Yes, I was hoping that a bookmark or link to your site could pick the flavor, however if there was a saved permalink this would have its own settings in it.

**Comment by OnlineCop** [comment]
The way the old version had it, `https://regex101.com/r/some_permalink#javascript` would force the flavor to be Javascript, even if it wasn't originally written with that one. I kinda liked that, to be honest. Instead of going "whoops: saved it in the wrong flavor, let me re-save without making any other changes besides the flavor", you just append a hashtag and you're done.

**Comment by firasdib** [comment]
Seems like you guys have done well by your own to prove my point: the behavior is ambiguous. The only thing I can think of is to have a query parameter that is the flavor that _always_ has precedence if it exists.

**Comment by dwelle** [comment]
IMO the previous behavior where it was saved to localStorage or sth like that was the best. In the new version, I've been bitten more than once by the default flavor being set to `php` while I thought I was debugging `js`. I never work in php, so I see no reason why I can't set `js` as default.

Edit: now I see the previous version had `#hash` support indeed. Well better than nothing, but I think there's `settings` tab, so why not use that.

Thanks for good work, either way!

**Comment by 5j9** [comment]
Every time I open up regex101 I have to change some of the flags. Currently there are 11 of them and in my current project I usually need `uxXgJ`. It'll take only a few seconds but I wish there was some way to adjust the defaults.
