### ISSUE TITLE
Search finds extra entries in Quick reference

### ISSUE THREAD

**Issue by TWiStErRob** [firasdib/Regex101#688]
For example why does "one of" query match:

> Line break modifier: (*LF) makes it so that only a line feed character is considered a line break. Common in UNIX documents.

It doesn't contain either words, not even their section ("group constructs") contains the words.

**Comment by firasdib** [comment]
There is an internal `keywords` array that is searched, and it must include `one` I suppose. Thats a bit overzealous I suppose.

@working-name thoughts?

**Comment by TWiStErRob** [comment]
I think that wouldn't be a problem if that keyword array was displayed.

**Comment by working-name** [comment]
I was overzealous, most likely. Was trying to cover all searches I imagined one might attempt. 

@TWiStErRob what were you trying to find by searching for "one of"?

Here's the keywords for `(LF)`
```js
keywords: [
'only', 'one', 'specific', 'return', 'carriage', 
'newline', 'line', 'break', 'kind', 'type', 'feed'
],
```

**Comment by TWiStErRob** [comment]
@working-name stuff in the "quantifiers" section.

**Comment by working-name** [comment]
@TWiStErRob those seem to be included in the results, although you get more than what you expect to. 

Personally, I don't find this to be a bug, but I can understand your point of view.

Maybe we should give `desc: "one or more of a"` priority over keywords in search results.

Otherwise, we can remove "one" from LF, and clean up the results in this particular case, but chances are this will keep showing up in the future.

**Comment by TWiStErRob** [comment]
I'm fine with it being in the results, I think the easiest fix would be to list the keywords. It would reduce the confusion if someone stumbles upon a search results which is there because of the keywords.

Though I wouldn't put frequent words into keywords in the first place:
http://www.link-assistant.com/seo-stop-words.html

*In general, a review/cleanup of quick ref might be in order: for example I tried to search for "alternation" and it doesn't find `|`. There are two entries for "carriage return" with different descriptions.*

**Comment by working-name** [comment]
I'm not convinced listing keywords is something we should do. It may look crowded. 

As far as the keyword review goes, it may not make sense for this. It would eradicate "of", "or", "one" which in my opinion are important keywords in this particular, specialized list of terms.

**Comment by TWiStErRob** [comment]
I don't see how `of` would help finding anything.

I think frequent words like "one or more" shouldn't be in the keywords, but in the actual explanation sentences. That way it's already displayed to the user and there's context and clear why the result is shown.

**Comment by working-name** [comment]
There's 4 carriage return related entries, however that's by design. They all have their proper category. For example, `\r` is used for both matching and as a replacement special character.

Also, depending on the flavor your work with, you'll get different results - only those features available to your regex engine.

As far as the keywords go, @firasdib, I assumed partial matches would apply there too. So when you type "altern" results matching partial keywords should show up already. That would take care of the "alternation" result. What do you think?

**Comment by TWiStErRob** [comment]
Yes, partial search works even "iage" finds "carriage return"s. Is it possible that "alternation", "repetition", "repeat" are not keywords for anything?

**Comment by firasdib** [comment]
I've cleaned the keywords up a bit. If you find more discrepancies, please open new issues.

**Comment by TWiStErRob** [comment]
"alternate", "alternation", "repetition", "repeat" still don't yield any results
