### ISSUE TITLE
case where PCRE mode can't handle multiple identical character classes

### ISSUE THREAD

**Issue by jnyrup** [firasdib/Regex101#689]
I get an error when trying to parse "[:][:]" in PCRE mode.
"[:][\:]" fails.
"[:]a[:]" fails.

"[.][:]" works.
"[:][.]" works.
"[\:][:]" works.
"::" works

It works fine in JavaScript mode fine.
Other sites, that uses PCRE such as https://www.debuggex.com/ http://www.phpliveregex.com/ http://www.regextester.com/ handles the case fine.

**Comment by TWiStErRob** [comment]
It looks like the regex parser/validator is too greedy. It shows the error:
> A posix character class may only appear inside a character class 

Which is designed to catch `[:alpha:]` being alone, that is the valid version is `[[:alpha:]]`. Your `[:]a[:]` likely fails because it looks like a POSIX class named `]a[`.

@firasdib when you fix this I suggest to change the error message to include the name of the POSIX class that was matched by your parser.

**Comment by jnyrup** [comment]
I guess this is handled the same place in the code, but "[..]" and "[==]"  also fails to be parsed.

**Comment by firasdib** [comment]
@jnyrup `[..]`, `[==]` and `[::]` are all invalid in PCRE, and will thus be flagged as errors.

The cases you mentioned with two separate character classes are indeed wrong and have been fixed.

@TWiStErRob It's already included.
