### ISSUE TITLE
Wrong explanation for all \g'n' like token

### ISSUE THREAD

**Issue by turlutton** [firasdib/Regex101#700]
The explanation for "Match nth subpattern" is wrong, it says "Matches the text captured in the nth group. n can contain more than one digit, if necessary. Alternate syntax for \g<n>".
It matches the -REGEX- in the group, not the text captured in the group. One could say it recurses the group.
Be careful to correct all the \g<n> like token.
@JohnDoe2

**Comment by working-name** [comment]
Done.

**Comment by dshepsis** [comment]
\gn (without quotes or brackets) is given the wrong description currently (might like \g'n' previously). It currently functions as, and is specified as (in the pcre standard) a backreference. That is, matching the exact text matched in sub-pattern n. However, the long-form description given in the bottom-right-hand corner of the interface on regex101.com claims it _recurses_ capturing group n.

This should be corrected so that all descriptions for \gn correctly describe it as a back-reference. \gn is not recursive, shouldn't be recursive, and should not be described as recursive.

Hope the verbosity of this was clear enough. See [https://regex101.com/r/9eMW1r/4](https://regex101.com/r/9eMW1r/4) for an example how \gn should behave.

**Comment by working-name** [comment]
Same goes for `\g{n}`. Fixed. Thank you dshepsis.

**Comment by firasdib** [comment]
Fixed
