### ISSUE TITLE
Don't redirect to home on following deleted links; instead show "This link is deleted."

### ISSUE THREAD

**Issue by Zarthus** [firasdib/Regex101#713]
It's confusing. :(

Link: https://regex101.com/r/KMr6Ne/1

**Comment by firasdib** [comment]
This poses a few problems:

1. This leaks information in the system. A user might have decided to hide a permalink, which shows the same behavior (it redirects). If a message was shown for a deleted regex this would potentially give someone extra info. Not that its likely any issue, but still.
2. The major issue with this is that you don't own the permalink you're given. The ID is unique while its alive for your regex, but you don't own it. If you delete it, that frees up the ID, which means it can be reused in the future.

So I'm afraid this is nothing I can implement right now.

**Comment by Zarthus** [comment]
How about a notification on top with "this regex wasn't found" together with the regex? like a popup or a toast notification

**Comment by TWiStErRob** [comment]
@firasdib what if you always show "This link is deleted"? If you phrase it like this it's always true, because either it was just deleted or it was already deleted in the past, hence it IS currently deleted.

Along with the above text there could be a [regex101.com](http://regex101.com) link as a signature and so the user can navigate to the home page. This leaks no information and the confusion of the automatic redirect is reduced.

---

I also like the popup/toast after the redirect (again, with a meaningless always true message), but that sounds harder to implement.
