### ISSUE TITLE
Regex101 high cpu usage when idle

### ISSUE THREAD

**Issue by azev** [firasdib/Regex101#738]
Whenever I access Regex101.com my computer becomes slow (cpu i7 / 8gb ram) even when it is idle and not processing any regex.
Why regex101 takes up so much system memory?

I run it on a clear Firefox profile: no plugins, no nothing, just Regex101.com. Same trouble.

**Comment by firasdib** [comment]
Sounds weird. 

Could you open your console and take a print screen of whatever you see there?

**Comment by azev** [comment]
It is really weird indeed.

The CPU usage shows < 1% usage but the system really goes slow! 
Specially the mouse speed slows down!

In Opera it doesn't happen.

I'm using firefox 50.0 but it always happened to me on firefox 
regardless of the version.

The screenshot bellow is 5s sample IDLE.

**Comment by firasdib** [comment]
I see no screenshot.

**Comment by azev** [comment]
check now please

**Comment by firasdib** [comment]
Can you take a picture of the console tab?

**Comment by azev** [comment]
The console shows no error:
App initialized  main.js:58:371
Successfully loaded previous state  main.js:58:371

**Comment by firasdib** [comment]
Its not errors I'm worried about. You should have an `asm.js` compilation message somewhere

**Comment by azev** [comment]
![s20161126145539](https://cloud.githubusercontent.com/assets/6639188/20641862/0bc8c616-b3e0-11e6-8113-b66901627921.png)

**Comment by firasdib** [comment]
Sorry, I don't know whats wrong then. Very hard to say.

**Comment by azev** [comment]
Only happens with regex101. other online regex tools won't do it.
IMHO, regex101 is WAY too heavy. Too much memory and system load just for regex parsing.

**Comment by firasdib** [comment]
Good thing its just your humble opinion then 😄.

You can join IRC to discuss it further and try to find out why your system is misbehaving.

**Comment by azev** [comment]
shu't up your ign'orant. you don't even know what is going on.

**Comment by TWiStErRob** [comment]
@azev we were here to help, Firas offered you to investigate further on IRC.

Regarding "too heavy", I tried the first few result for Google search "regex tester" and their memory usage is comparable to that of regex101. However, the feature set and presentation they provide is much-much less than this site. For example flavors, debugger, and match list. Some are more lightweight, because they do server-side parsing, but with that comes the drawback that you're presented with a spinner for every click on the UI.

The problem with this issue is that if we can't reproduce it, there's no way to investigate and fix it. I tried to repro, but all I see is some rare setTimeout events, which should be normal and they're too quick to cause any mouse issues. I remember having a slow mouse issue, but it was back in the day, when HDD I/O and PS/2 interrupts were racing for resources.
