### ISSUE TITLE
Improvement suggestion: drop the MATCH INFORMATION group highlight when it shows no useful info

### ISSUE THREAD

**Issue by chrisjj** [firasdib/Regex101#756]
e.g. with JavaScript:

![image](https://cloud.githubusercontent.com/assets/6157073/21030002/1dc40494-bd94-11e6-8330-86daac0ce9fa.png)

**Comment by TWiStErRob** [comment]
Note that your example is actually using the JS engine, which cannot show the highlighted match, because the groups don't have start/end positions (see `n/a`s in match info).

Even without these positions, I think it is still useful in some cases, for example when there are multiple matches with `/.../g` and there are alternative groups on top level. In that case you could see just from the color which path matched, for example: https://regex101.com/r/LFySVd/2
![image](https://cloud.githubusercontent.com/assets/2906988/21535176/54ec90b4-cd69-11e6-87cd-966eb4238f2d.png)
In this case if the red/green color were removed you would have to read the <code>\`a\`</code>/<code>\`b\`</code> strings to recognize the same.

**Comment by chrisjj** [comment]
Good point. Thanks. I've amended the suggestion.

**Comment by firasdib** [comment]
I don't like this "magic" behavior if I'm frank, so I'll skip this. Thanks for the feedback though.
