### ISSUE TITLE
Non-capturing group highlighted

### ISSUE THREAD

**Issue by rzucareli** [firasdib/Regex101#761]
In javascript flavor, when I put a Non-capturing group (?:) the match of the group was highlighted.

![regex bug](https://cloud.githubusercontent.com/assets/6935648/21438204/f8060a1e-c86e-11e6-8450-525e92b7b2c4.jpg)

The bracet should not be highlighted, right?

**Comment by TWiStErRob** [comment]
Actually no capturing group is highlighted. Look at the match information on the right:
![image](https://cloud.githubusercontent.com/assets/2906988/21438372/6f308aae-c880-11e6-8b45-86fd13ddc14e.png)

You don't have any groups, what you're seeing is the matches highlighted against plain text.

Compare with this: https://regex101.com/r/WRHsx0/1
![image](https://cloud.githubusercontent.com/assets/2906988/21438403/a1517584-c880-11e6-9c99-05afc6171d10.png)

Note: the behavior is the same for all flavors, with the exception that JavaScript can't highlight groups at all, because it doesn't give you positions in the input string, only the contents of the groups.
