### ISSUE TITLE
No issue, just congrats for the great tool!

### ISSUE THREAD

**Issue by GT37** [firasdib/Regex101#773]
I like the tool and I use almost every day to learn more about regex. Thanks for your work and keep going!

**Comment by CagatayUlubay** [comment]
Same here, I knew it's awesome, but TIL Quick Reference Guides.

Instead of opening Issues, we should consider thanking and express our thanks with a [Donation](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=firas%2edib%40gmail%2ecom&lc=US&item_name=Regex101&no_note=0&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_SM%2egif%3aNonHostedGuest)

**Comment by Zarthus** [comment]
I'm closing this issue in favour of comments on #768, so we don't needlessly clutter the issue repository with a bunch of open issues :)

Cheers, folks.
