### ISSUE TITLE
wrong ascii code

### ISSUE THREAD

**Issue by bvs23bkv33** [firasdib/Regex101#774]
[A-Ω]{1,}
{1,} Quantifier — Matches between one and unlimited times, as many times as possible, giving back as needed (greedy)
A-Ω a single character in the range between A (ASCII 65) and **Ω (ASCII 937)** (case sensitive)

**Comment by firasdib** [comment]
![screen shot 2017-02-13 at 08 50 55](https://cloud.githubusercontent.com/assets/1335165/22875016/9ac73b14-f1c9-11e6-8fdb-e37771d03c54.png)

Perhaps `ascii` is a bad word, `decimal` is better?

**Comment by TWiStErRob** [comment]
Looking at the method name that produces it how about `code`; or if we look at the [docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt) `code unit` would be the correct term. Or just simply use `Unicode` instead of `ASCII`, see [how nicely it integrates with search](https://www.google.com/search?q=Unicode%20937)?

**Comment by bvs23bkv33** [comment]
yes, "ASCII" is not suitable

**Comment by firasdib** [comment]
Fixed
