### ISSUE TITLE
Javascript code generator: escapes the $ in $1, $2, etc.

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#784]
The Javascript Substitution for the below regex should be

    $1$2-$5$3\n$4$5

The code generator gives the substitution line as:

    const subst = `\$1\$2-\$5\$3\\n\$4\$5`;

Here, all `$` are escaped.

https://regex101.com/r/5SqNds/2/codegen?language=javascript

**Comment by cauerego** [comment]
@OnlineCop should it?

testing on chrome console, both escaped '\$1' and un-escaped '$1' work just the same. no idea why.

although I agree it's probably better to keep the smaller version, just for simplicity.

on the other hand, \n is also escaped as \\n and now that's a what I would actually call a bug!

**Comment by TWiStErRob** [comment]
@cauerego 
> both escaped '$1' and un-escaped '$1' work just the same. no idea why.

this may help:
```javascript
a = 'val'
subst = `dollar a: $a; dollar {a}: ${a}; unescaped group: $1; unescaped new line: \n; escaped group: \$2; escaped new line: \\nEOF`
console.log(subst)
console.log('abc-defg'.replace(/(.*)-(.*)/, subst))
```

output:
```
dollar a: $a; dollar {a}: val; unescaped group: $1; unescaped new line: 
; escaped group: $2; escaped new line: \nEOF
dollar a: $a; dollar {a}: val; unescaped group: abc; unescaped new line: 
; escaped group: defg; escaped new line: \nEOF
```
notice two things:
 * after JS parsed the template literal the escaped and unescaped groups are the same, because it resolves the `\$` escape
 * dollar is only special if it's followed by `{expr}`

@firasdib I think @OnlineCop is right, escaping $ is paranoid in template strings, because it only interpolates if the expression is inside `${}` not when it's followed by `$` (I wonder if this is true for all ES versions though). Also I agree `\\n` leads to incorrect results, either the regex101 substitution shouldn't handle `\n` or it shouldn't be double escaped in generated code.

**Comment by cauerego** [comment]
I guess my point is I couldn't find any situation in which `\$1` would yield a different result from `$1`, even now, while trying again after your inputs. so that didn't really help, but thanks so much for trying, @TWiStErRob! 👍

**Comment by TWiStErRob** [comment]
Yes I understand it works the same, I was trying to point out **why** (which you where thinking about): the JS parser resolves the `\` because it has to interpret a level of escape sequences. So the regex engine never even sees `\$1`, it always gets just `$1` and hence the two forms work the same.

Anyway, from a private chat yesterday I think @firasdib is working/will work on making substs better.
