### ISSUE TITLE
Show does match/does not match icon for each unit test

### ISSUE THREAD

**Issue by danielcompton** [firasdib/Regex101#793]
When reviewing unit tests, it can be hard to know if I've defined my unit tests correctly for matching/not matching behaviour. It would be handy if there was an icon showing whether a unit test was for a match or not a match.

<img width="668" alt="screenshot of google chrome 3-03-17 9-45-48 am" src="https://cloud.githubusercontent.com/assets/811954/23526219/30918af2-fff6-11e6-9e2d-e3286f0cca58.png">

From this image, I can't tell if I've configured my unit tests correctly, and I need to expand them all to check.

**Comment by firasdib** [comment]
But there are many more permutations possible, how would one distinguish them all?

**Comment by TWiStErRob** [comment]
There are 6 possibilities in my reading, is that much?

**Comment by danielcompton** [comment]
The assertions I can see:

* regex does match
* regex doesn't match
* matched result starts with
* matched result ends with
* matched result contains
* matched result equals

I would be quite happy if there was just small text on the right hand side saying which one of those assertions was picked. Alternatively you could just have icons for regex does match, regex doesn't match, or matched result (grouping all four under this one icon).

**Comment by firasdib** [comment]
As a part of the new version I've done the following changes:

<img width="1150" alt="screen shot 2017-03-09 at 15 38 37" src="https://cloud.githubusercontent.com/assets/1335165/23754784/87031530-04de-11e7-9cbc-a44e6ccd075f.png">

How does that look?

**Comment by danielcompton** [comment]
That looks great, though I'd suggest maybe moving it over to the right hand side as there's lots of horizontal space, and less vertical space? Not a big deal though. Thanks!

**Comment by TWiStErRob** [comment]
Agree

**Comment by firasdib** [comment]
Would you rather show less of the description/title? The added vertical space is not too bad imo.

**Comment by TWiStErRob** [comment]
It's not that bad, but the 80% gaping gray looks weird and offers a nice place for this.

**Comment by firasdib** [comment]
But that gets tricky when horizontal space is limited. Wrapping it nicely will be hard when the text width is dynamic. 

Ill show another print tomorrow.

**Comment by Doqnach** [comment]
I prefer how the screenshot looks with the text underneath personally. Wonder how it looks when done next to each other? Not too crowded then?

can always have a (media-query) breakpoint where you start putting it under the name? I almost never have my browser window maximised so would often be below that width-gap so to say. No idea about mobile though since I never use the site on a mobile device.

**Comment by TWiStErRob** [comment]
@firasdib take a look at http://web.twisterrob.net/calendar-printer/#!&calendar=developer-calendar%40google.com for dynamic text width (both even title and location are dynamic length)

**Comment by firasdib** [comment]
Not sure I follow, Robert?

**Comment by TWiStErRob** [comment]
it was re:
> But that gets tricky when horizontal space is limited. Wrapping it nicely will be hard when the text width is dynamic.

I'm comparing the event display lines to your test lines, if you resize the window they move fluently around to accommodate allowed space.

Anyway, for normal window size the unspecified tests always have enough space for the new description. Then only time it would wrap is when you resize the window to extremely narrow on desktop.

@Doqnach just curious: what is the size of the window, because the breakpoints are already there. When it is about to get crowded one of the sidebars is hidden, so for this particular case there's always long empty area available.

**Comment by firasdib** [comment]
The most common resolution is 1920x1080 and after that mere 1366x768. Seldomly do people browse full screen, so here is a screen show how it'd look the majority of the time on a 1080p monitor.

<img width="1340" alt="screen shot 2017-03-10 at 09 04 42" src="https://cloud.githubusercontent.com/assets/1335165/23787097/a4f1326a-0570-11e7-8895-57200f536f63.png">

I think one line is going to be too crowded.

@TWiStErRob I was using mobile, page wasn't loading.. Thats why :)

**Comment by TWiStErRob** [comment]
Ah, sorry, I thought you'll only add this for "Untitled" ones.

**Comment by Doqnach** [comment]
@TWiStErRob I tend to be around (often just below) the 1200px width for my browser window. I have all sidebars showing (no auto-hide).

**Comment by firasdib** [comment]
Done
