### ISSUE TITLE
Need Clear Visual Indication When User is Signed In

### ISSUE THREAD

**Issue by JMichaelTX** [firasdib/Regex101#801]
With the recent changes you have made, it is impossible to quickly determine if I am signed in or not.  There is NO visual indicator in the top tool bar.

Regex101.com Toolbar:
![image](https://cloud.githubusercontent.com/assets/11052885/23927863/61c49662-08ea-11e7-98a2-bc0b0f128674.png)

**I always  want to be signed in so that when I create a new RegEx I can save it.**

Please add an icon/avatar to the tool bar which clearly indicates when the use is signed in.

For example:
Github Signed In:
![image](https://cloud.githubusercontent.com/assets/11052885/23927890/8afa1822-08ea-11e7-85b9-4630e719ad9c.png)

Github NOT Signed In:
![image](https://cloud.githubusercontent.com/assets/11052885/23927902/93f07890-08ea-11e7-8d42-83a4252e67f5.png)

Thanks.

**Comment by firasdib** [comment]
The recent change has not affected this, the button only changed place. 

Do you have a proposal as to what can be done? Changing the color of the account button perhaps?

**Comment by Doqnach** [comment]
I hardly ever login so this was pretty much the first time I logged in after the redesign. I agree with @JMichaelTX  that some form of indicator for being logged in would be useful because now there is none. Changing the colour of the icon would be a good step.

I also agree with @JMichaelTX  about the placement of the button. It wasn't the first place I was looking for it, since most services these days have it in the top bar on the far right.

**Comment by firasdib** [comment]
That is true. For me, personally, I feel the new location fits in better with how the page is structured, but I agree that its not the first place one might look. Would having two buttons be confusing? Maybe simply having the top right button be a link like the one in the sidebar?

**Comment by Doqnach** [comment]
Having two buttons pointing to the same thing does sounds confusing to me, except for small screens. On small screens the top bar could have the icon indicator and also the menu item in the left hamburger?

**Comment by firasdib** [comment]
Yes, if it were to be doubled it would be doubled in every view.

I have added profile pictures and I show which account is currently signed in (as per #802).
I have not pushed it live yet, but soon.

Question is now: should we keep the button in the left sidebar or place it on the top right of the header like it used to? And in that case, how should the button function? 

I was placed in the left sidebar because that felt consistent with how the pages are constructed, but I realize that placing it in top right is more common.

**Comment by firasdib** [comment]
Here are some screenshots of how it currently looks

<img width="253" alt="screen shot 2017-03-15 at 12 41 45" src="https://cloud.githubusercontent.com/assets/1335165/23946934/c7fc7b24-097c-11e7-9451-006c1ba4b9e0.png">
<img width="287" alt="screen shot 2017-03-15 at 12 41 17" src="https://cloud.githubusercontent.com/assets/1335165/23946936/c8128680-097c-11e7-8a0d-3e5b93d55885.png">
<img width="274" alt="screen shot 2017-03-15 at 12 41 09" src="https://cloud.githubusercontent.com/assets/1335165/23946938/c81f728c-097c-11e7-8aa8-d557eb5c35eb.png">

**Comment by Doqnach** [comment]
> Perhaps it would be enough to show the profile picture in the header (which can act as a shortcut to the account page) when you are signed in?

That would make sense in this case. If the window has enough room, also show the username next to it then? Or just the picture, like here on github?

After seeing the screenshots I'm also not entirely against putting the user at the top of the list in the left menubar, like digitok suggested on IRC. Just feels weird being there in the middle of the menubar...

> < digitok> http://imgur.com/FpZsA84

**Comment by firasdib** [comment]
@Doqnach I will only show the picture, like on github, in that case.

I don't like digitoks example because the account feature is not number 1, the regex tester is.

Proposed solution:
Leave the account button as it were in the left sidebar, but add the avatar button to the header when signed in which acts as a shortcut that takes you to the account page. How does that sound?

**Comment by working-name** [comment]
I second the proposed solution.

**Comment by firasdib** [comment]
@working-name Then the question would be why not always have the "shortcut" in the header.

I believe we're slowly drifting out of scope of this issue, since this was merely about displaying a logged in status, which I have now completed.

I will push the changes and we can open a new issue about the button placement.

**Comment by working-name** [comment]
Because I view the header shortcut/profile pic as distracting, and I think it would go against the general design cues which is based on the idea that sidebars are helpers. 

That being said, I can live with a profile pic in the header and learn to ignore it, but personally speaking a color change of the icon on the left sidebar would achieve the same thing.
