### ISSUE TITLE
Liberating your application

### ISSUE THREAD

**Issue by furkanmustafa** [firasdib/Regex101#806]
Hello,

First, I'd like to thank you, as #805, #768, #773, this application is a life saver. And it's not just useful, it is beautifully designed, and as simple as possible, while being well informing.

Second, I'd like to repeat requests ( #544, #490, #336, #302 ) for accepting payments via other companies, not just Paypal. God, I hate paypal (and it hates me, and lot's of other people).

Third (and mainly), I'd like to repeat requests ( #89, #77, ~ #76, #6 ) for releasing the source code of the application, in a bit more detail. I'd love to make 100+ USD donation if you could liberate your application via a suiting strict free software license, like [AGPL](https://www.gnu.org/licenses/agpl-3.0.en.html). It'd still be nice that you have the [complete authority](https://en.wikipedia.org/wiki/Benevolent_dictator_for_life) over the project.

That'd be nice if other people sharing a similar opinion would share their thoughts, and/or how much they'd like to contribute for such thing.

In my (biased) opinion, tools for production should not be owned, and people should not be restricted with their use of it. I do not know if you agree or not, please share your opinions.

Well, there is also the community contribution advantage, I'm guessing that part is already known.

Thanks again.

**Comment by Zarthus** [comment]
To comment on the open sourcing of the project, per https://github.com/firasdib/Regex101/wiki/FAQ#will-you-open-source-regex101, there is currently no plans to open source it.

I absolutely agree that in an ideal scenario every application ever in the world is open sourced (and showing support in favour will definitely help make that become a better priority), I just don't think that it will happen any time soon. (and that's fine in my book).

Would you be okay with it if I were to re-open issue 6 so that we have one centralized place for discussion, rather than spread it across several issues?

As for alternate payment providers, do you have any in mind that you use?

**Comment by Zarthus** [comment]
to add on to this, I've went ahead and created some GitHub projects which may make this easier to track. It's just something I'm experimenting with, but we'll see if this works out.
