### ISSUE TITLE
As a user, I want a clean list of my Regex's, devoid of historic versions. 

### ISSUE THREAD

**Issue by andy10james** [firasdib/Regex101#809]
Regex101 is great. It's a great UI, and it's interpreter and explanations of regex components is excellent - making Regex101 my weapon of choice for my Regexes. 

As an avid writer of Regexes, I would like to have a list of all my regexes. However, the existing "My Regular Expressions" lists all of the versions of every Regex I have. If I edit a rather large Regex 20-30 times, and have several of these Regexes, I now have a "My Regular Expressions" list of well over a 100 items while only a tiny handful are actually the relevant, latest version. If you delete any Regex - even an old version - all the versions of that Regex are deleted (even the latest one). 

Secondly, when creating a Regex, when you first save it you are asked for a name (as expected), but clicking "Update Regex" asks you again for a title and tags. If you don't provide one, the existing one isn't used, instead you create another entry with no title. This causes a lot of mess in the "My Regular Expressions" folder; in my above use case - unless I re-entered the Regex title 100 times - I'd have 
100 Regexes named 123456, and a couple named "RFC 1234 My Regex"; and those named ones aren't even the ones you want anymore. 

Personally, I think there are a number of _unexpected behaviours_ here. 
Some alternate behaviours I have mentioned to @firasdib are below:

> I would think of it like files in a folder on my desktop, or documents in OneDrive, Dropbox or Google Drive. If I edit it and press Save, it doesn’t ask me for the title of the document or the tags again – it’s the same document/Regex just changed content. 

> Going to find that document/regex again in my “my regexes” tab should show the latest of it. If I want to get an old version of a regex (which I wouldn’t often do), I find it easiest to open the Regex via the “my regexes” tab (since the list would be smaller than the "My History" tab so I can get to it quicker) and use the Version dropdown at the top.

Comments by @firasdib:
> If you only want to view 1 version in the "my regexes" tab, would that be first or last version? Which tags and which title should be shown? 
> It feels like someone will be upset regardless.

**Comment by kanaikimi** [comment]
I believe always the **latest** should be shown unless I specifically want an old version. 
As for which Titles and Tags should be shown - it's the same Regex/content - the Title and Tags should not be versioned and have to be re-entered on every save.

**Comment by eToThePi-i** [comment]
Another nice thing might be an edit summary, where you can specify _why_ the regex was changed. There are 2 kinds of changes I make to my regex, efficiency improvements and fixing broken regex. Currently, I use tags to mark old versions.

I think the largest issue is the separation of separate versions in [My History](https://regex101.com/account/all). Instead of listing them separately, there should be version drop down when a version is clicked on. This is a major impediment to avid users, because their old regex get buried in the history with a bunch of less useful previous versions.

**Comment by bmix** [comment]
I wholeheartedly agree! 

Once a name and tags are set for an expression, these should define same throughout any other revisions. And these revisions could then be grouped under that named item.

The last revision could be active by default, unless the user chooses to activate another revision, which, otherwise, is hidden under the current regex main item entry (root of revision tree, linking to last (or active) version)

It's really just a user interface topic, IMO. But an important one :-)

**Comment by firasdib** [comment]
This should finally be the case after the latest major update.
