### ISSUE TITLE
Unsupported regex should be removed or reformatted in generated code.

### ISSUE THREAD

**Issue by leumas95** [firasdib/Regex101#811]
For example `(?# Comment)` came from the Perl implementation of Regex, as such it is not supported everywhere else, the Java standard Regex is a good example of this.

In this case, the code generator should warn you or remove the comment blocks.

There are also named capture group constructs that Regex101 supports that are language specific, to use Java as an example again `(?<name>X)` is the only one supported so if my regex uses `(?'name'X)` it should swap it to an alternative notation or at least warn you.

**Comment by Zarthus** [comment]
This is incredibly tricky to do, and I don't believe the code generator is a good place for it, what instead would be more beneficial is if more languages were introduced so that the "IDE" automatically detects it as invalid. The code generator does not run a regex parser, it merely generates code based on language knowledge and a few variables.

Modifying the users regex at this point would lead more to errors or unexpected results, and a warning should be provided if anything.

**Comment by leumas95** [comment]
Fair point,
I did not really think of the UX or the simplest way to do this, I just think the current result are non-ideal at best, but yes I do think that it would be good to add more languages to the IDE as well as adding some sort of warning/validation.

The point stands that by generating code for 'Java' the user would expect the code to be runnable in Java etc.

**Comment by firasdib** [comment]
There is a small text at the bottom explaining this to the user. Performing full-fledged conversion between flavors is quite a big task and nothing I have planned to do.
