### ISSUE TITLE
False claim on closed issued, and locked to collaborators only

### ISSUE THREAD

**Issue by oxygens** [firasdib/Regex101#835]
[/firasdib/Regex101/issues/610](https://github.com/firasdib/Regex101/issues/610)

__Shortly after__ (weeks?) this discussion, the regex101 website has transformed the flags input field into a list of possible options, with explanations. Catered for the current regex engine.

At least, the discussion clearly pointed out that the field is not newbie friendly.

I took a lot of heat from a guy who just wanted to show off his regex skills with no constructive input on the matter. 

The owner (firas) which backed him locked the thread and called it non-sense once again.

Thankfully, @working-name walked in and turned that into something constructive.

Please fix that thread to mention the actual outcome of my "nonsense"/"ambiguity", since the ambiguity itself was beeing pointed out, ffs.

Thank you!

**Comment by Zarthus** [comment]
The issue is a bit too long for me to actively read through to all of it, and the OP in this issue is also a bit heated and genuinely feels intended just for the sake of proving a point.

Being unaffiliated with the issue, I'll link to this issue from that thread - which should suffice for archival purposes.

fwiw: There are less assery ways of proving you were right all along, please remember this is all done by volunteers.
