### ISSUE TITLE
When accessing to a non-version URL, redirect to the last one instead to the first

### ISSUE THREAD

**Issue by charly22** [firasdib/Regex101#843]
For example, if I go to `regex101.com/r/<hash>` it always redirects to `regex101.com/r/<hash>/1` while I would expect to redirect to the last version. Thanks!

**Comment by OnlineCop** [comment]
See https://github.com/firasdib/Regex101/issues/503 and the comments made by Firas.

**Comment by TWiStErRob** [comment]
He didn't really justify it...
I guess it's easier to assume there's a first version than query the latest.

**Comment by charly22** [comment]
> I guess it's easier to assume there's a first version than query the latest.

Exactly, that was my assumption also but didn't wanted to base my idea on that. Basically, at least from my POV it would be more useful being redirected to latest, even if it implies constructing a different URI schema, something like `regex101.com/r/<hash>/latest` or similar.

**Comment by firasdib** [comment]
It depends. If you're viewing a regex from the old days, where versions did not exist, you'd expect to come to the first.

Either way, you could argue for both. Is it a big nuisance to load version 1 then click the dropdown and select whichever version you like?

**Comment by OnlineCop** [comment]
My personal preference has always been to go to the latest; revision /1 is almost always a non-functional version when people join IRC and give us the link, asking for help. Clicking the dropdown is just an extra step to get to the latest.

For "pre-revision" links, I think the StackOverflow links themselves should just be updated with a `/1` on them.

**Comment by Doqnach** [comment]
I've seen plenty of people using the same single hash for a whole range of different regex though, instead of saving each individually. It's hard to say which is best because I think there will be strongly opinionated people on both sides of the discussion (which is evident by this issue and the one linked). But I guess that going to the latest would actually be the best behaviour from a UX standpoint. If you want the first version, or a specific version, just make sure to add the correct link. Makes it also easier to craft your own link to jump to the latest version, whereas crafting a link to go to the first version is already arbitrary.

**Comment by kanaikimi** [comment]
Aye, if want to see a regex, I don't care if it's been edited 100 times, I want to see the regex. I.e. the latest regex, the current regex. I don't care if it was before versioning. I want to edit the current regex and always will. There will only ever be 1 specific time you want the first version - for historic purposes, at which point you go the historic version drop down. 

Let's compare this to any of file service. If I open a file, if I open an email, if I open a code file on c9. Do I see the very first version of it? No. Because I'm not working on/editing an old version - that wouldn't make sense. So, in terms on consistency with web design, this should be changed - as @Doqnach mentions - for UX. 

You may also not notice it's the first version - the Regex101 editor has many things on the screen. I doubt the little "v1" in the top left corner is catching of the eye. Therefore - this hold significant security and stability issues for software developers using Regex101 as it currently is.

**Comment by firasdib** [comment]
What security and stability issues are you talking about?

**Comment by kanaikimi** [comment]
Half of the regex's on regex 101 are validation - namely security validation and data entry. Given that most people don't notice it's not the latest version when loading a Regex via a non-version URL, this is as good as discarding all edits made to that regex. 

Now - this isn't just a question of "which one saves their time a bit for what they want to do", it's a question of "what is the significance of those edits". Nearly all edits are made because there's a flaw in the original or a change of requirement, and *there* lies your danger. We need to think of what these Regexes are used for, i.e. *live commercial* systems, user validation, *password* validation. If you don't make these later edits apparent - *clearly* - you risk all the flaws in your user's applications. 

I could tell you a story of little bit of code a developer of British Airways (I think) put their site for what they thought was making things easier for the user. A passenger lost a few thousand British pounds because of that little mis-leading feature. 

This is clearly just opinion - but my part of the opinion here is strong not to which is easier - but to what would be better catering to value and importance of those later edits. Show them the first version if you want - but discard the importance those edits - for everyone's sake.

**Comment by Soaku** [comment]
+1

This could be just like @charly22 pointed, `/r/hash/latest`. It doesn't need to be just without version. I'm using regex to create a syntax checker, so I wish it was always viewing the latest version.

**Comment by mbaluda** [comment]
+1 for a link to the latest version

**Comment by DrunkenPoney** [comment]
+1 Definitely need a link pointing to the latest version.

**Comment by firasdib** [comment]
Perhaps using the string literal `/r/hash/latest`, as @Soaku mentioned, is a good enough solution?

**Comment by firasdib** [comment]
This has now been implemented and is in the january 2019 milestone. It'll be released soon-ish :-)

**Comment by mxmilkiib** [comment]
Might or could there be something to click in the UI to access this? It's a bit hard for some to have to manually edit a URL.

**Comment by working-name** [comment]
@mxmilkiib if you mean to switch between an entry's versions, there's a `v#` near the number of steps. Here's an example: https://regex101.com/r/HeuLIg/
![version](https://user-images.githubusercontent.com/16505052/150528902-4e3c1b08-37e1-4b2d-b1a1-6a4915651c97.jpg)
2
