### ISSUE TITLE
unicode categories

### ISSUE THREAD

**Issue by dakane86** [firasdib/Regex101#849]
weird behaviour :

- \pS match € sign : it's ok
- \p{Sc} match € sign : ok
- \pSc doesn't match € sign but consider the pattern correct : nok
- Worst : \pSc match '€c' (because it separates in \pS then 'c' character)

We could consider that \pX is correct for X of 1 character, otherwise we should use \p{X} format. But in this case, the explanation for \pSc is still 'currency signs' not '\pS followed by `c` character'.

The regex behaviour or the explanation is not correct. I can't determine.

**Comment by Doqnach** [comment]
The documentation at http://www.pcre.org/pcre.txt seems to read that the above is actually expected behaviour. I can't find a place where the documentation supports the `\pSc` syntax, only `\pS` (or in the documentation itself: `\pM` and `\pL`) syntax. In all cases of `Sc` or `Ll` they use the `\p{Sc}` syntax.

So to me your use case is expected and desired behaviour for PCRE at least.

**Comment by dakane86** [comment]
ok but when you type \pSc in the pattern box, the explanation is "all currency signs". This should be modified by 2 steps : the \pS and the 'c' character

**Comment by Doqnach** [comment]
ahhhh! Gotcha!

Yes, that is indeed a bug it seems.

**Comment by firasdib** [comment]
It would seem PCRE only supports one letter following the `\p` construct. I have fixed this now. That means if you want to use `\pSc` you need to use `\p{Sc}`. This will be clearer now.

**Comment by firasdib** [comment]
Fixed fwiw
