### ISSUE TITLE
Python regex timeout for unknown reason

### ISSUE THREAD

**Issue by Darker** [firasdib/Regex101#853]
regex: https://regex101.com/r/fTyMNZ/2

This fragment causes timeout:

```
 80a9eff:	83 c4 20             	add    $0x20,%esp
 80a9f02:	5b                   	pop    %ebx
 80a9f03:	5e                   	pop    %esi
 80a9f04:	5f                   	pop    %edi
 80a9f05:	5d                   	pop    %ebp
 80a9f06:	c3                   	ret    

program data


build/program-x86:     file format elf32-i386

Contents of section my_data:
 80c7f00 64617461 00                          data.           

```

No timeout when I run it in python

**Comment by TWiStErRob** [comment]
You can increase timeout in settings. The default is 2 seconds. Python on the website is not using a native regex engine, it is being emulated via JavaScript using PCRE I think. Emulation is always slower.

Change to PCRE flavor and open the debugger from the sidebar to see where the timeout happens. After a quick check I saw that the issue is when it is skipping normal text, versus the code you're matching. Every character takes a while.

A simple change I did improved the runtime from 6 seconds to 600ms: add `^` anchor at the beginning of your regex. Since you're parsing code it could be expected that the first indentation (`\t*`) would be on line start and not after some random text. This makes the regex engine skip non-code lines really fast.
