### ISSUE TITLE
Java code generator named groups error

### ISSUE THREAD

**Issue by ivanviragine** [firasdib/Regex101#868]
Hi there,

How are you guys?
Thanks for the amazing tool!
The java code generator is generating named groups like "?'GROUPNAME'" and it should be "?<GROUPNAME>".

Reference: https://stackoverflow.com/questions/415580/regex-named-groups-in-java

**Comment by Doqnach** [comment]
The code generator bases itself on the notation you used for the regex itself. Since JAVA is not a supported flavour (only available in the code generator) you use the PCRE engine for writing the regex, which supports a different notation. This is a known 'problem'. Best is to write the regex using the correct syntax for your specific flavour.

See #811

**Comment by ivanviragine** [comment]
I understand what you're saying, but, isn't it the whole point of code generator? To translate specifics of notation to another language?

**Comment by Doqnach** [comment]
It is, but the simple fact is that at this time JAVA is just not supported by the site as a flavour. The only thing it does is provide some simple code generation for more languages than the flavours it actually supports, since those are very common questions and the syntax is similar enough to provide such a service for those languages.

It all comes down to wanting a JAVA flavour, which would counter such problems.

**Comment by Zarthus** [comment]
The code generator just generates basic boilerplate based on common flags,
it does not do any sort of complex parsing of a regex to see if it is
supported, it just assumes the user wrote a regex that works using
regex101, and then show code on how it could be used in your application.

Think closer to the /g flag and translating from preg_replace to
preg_replace_all
