### ISSUE TITLE
Work offline

### ISSUE THREAD

**Issue by rugk** [firasdib/Regex101#945]
You already use service workers… so AFAIK the step to a complete website working offline is not far.

**Comment by firasdib** [comment]
The site works offline. Whats the problem?

**Comment by rugk** [comment]
Uh, never really tried. 😃 
Thanks.

**Comment by chillyshackk** [comment]
I'm in no way an expert in this so I spent some time tonight getting regex101 to work offline with the latest version, based on the previous scripts I saw around. Correct this if needed, but I got it working at least so I thought I'd share:

Create a folder where you want regex101, then inside that folder create a .sh script:

vim download_run_regex101.sh

Copy/Paste this inside the file:

`#!/bin/bash

trap ctrl_c SIGINT;

#put the download and run scripts in that same folder:
pushd /path/where/you/want/regex101;

wget -r --no-host-directories --no-parent https://regex101.com;
wget -r --no-host-directories --no-parent https://regex101.com/static/translations/english.json;
wget --output-document ./static/pcreWorker.js https://regex101.com/static/pcreWorker.js;
wget --output-document ./static/pcrelib.js https://regex101.com/static/pcrelib.js;
wget --output-document ./javascriptWorker.js http://regex101.com/javascriptWorker.js;
wget --output-document ./static/sw.js http://regex101.com/static/sw.js;
wget --output-document ./static/javascriptWorker.js http://regex101.com/static/javascriptWorker.js;
wget --output-document ./static/vendor.71600b0e.chunk.js http://regex101.com/static/vendor.71600b0e.chunk.js;
wget --output-document ./static/golangWorker.js http://regex101.com/static/golangWorker.js;
wget --output-document ./static/english.json http://regex101.com/static/translations/english.json;
wget --output-document ./static/golang.js http://regex101.com/static/golang.js;
wget --output-document ./static/bundle.f566b334954e3b444def.css https://regex101.com/static/bundle.f566b334954e3b444def.css;
wget --output-document ./static/bundle.f566b334954e3b444def.css.map https://regex101.com/static/bundle.f566b334954e3b444def.css.map;

function server {
  python -m SimpleHTTPServer $@;
}

function cleanup {
 echo "Closing...";
 popd;
}

function ctrl_c {
 cleanup;
 exit $?;
}

server $@;`

Save the file, make it executable (chmod +x) then run it (using: ./download_run_regex101.sh). I also made a second one so that it can just run regex101 without re-downloading once it's done, just create a second .sh file, comment out all the wget lines (add # in front of each line with wget), save, then run this one once you have downloaded a copy with the first script. I probably downloaded those files many times tonight, my bad..!

**Comment by TWiStErRob** [comment]
@chillyshackk the site works offline, just open it once online and then it'll work offline even if you close the tab. I just opened it, and then killed Wi-Fi and restarted Chrome (which also updated in the meantime) and everything worked just fine while not having Wi-Fi.

This indicator will be shown in bottom left corner:
![image](https://user-images.githubusercontent.com/2906988/58214810-01c18b00-7cef-11e9-88f3-d69882be9e0e.png)

**Comment by chillyshackk** [comment]
Yes I know I was just messing around, I clear my temp files pretty often this way I have a copy somewhere if needed :)

**Comment by dragokas** [comment]
@chillyshackk can you fix that script or give an instruction, please?

```
alex@debian:~/dev/regex101$ ./download_run_regex101.sh
./download_run_regex101.sh: line 6: pushd: /path/where/you/want/regex101: No such file or directory
--2019-11-27 06:03:55--  https://regex101.com/
Resolving regex101.com (regex101.com)... 188.166.143.210, 2a03:b0c0:0:1010::9e:4001
Connecting to regex101.com (regex101.com)|188.166.143.210|:443... connected.
ERROR: The certificate of ‘regex101.com’ is not trusted.
ERROR: The certificate of ‘regex101.com’ is not yet activated.
The certificate has not yet been activated
--2019-11-27 06:03:55--  https://regex101.com/static/translations/english.json
Resolving regex101.com (regex101.com)... 188.166.143.210, 2a03:b0c0:0:1010::9e:4001
Connecting to regex101.com (regex101.com)|188.166.143.210|:443... connected.
ERROR: The certificate of ‘regex101.com’ is not trusted.
ERROR: The certificate of ‘regex101.com’ is not yet activated.
The certificate has not yet been activated
./static/pcreWorker.js: No such file or directory
./static/pcrelib.js: No such file or directory
--2019-11-27 06:03:55--  http://regex101.com/javascriptWorker.js
Resolving regex101.com (regex101.com)... 188.166.143.210, 2a03:b0c0:0:1010::9e:4001
Connecting to regex101.com (regex101.com)|188.166.143.210|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://regex101.com/javascriptWorker.js [following]
--2019-11-27 06:03:55--  https://regex101.com/javascriptWorker.js
Connecting to regex101.com (regex101.com)|188.166.143.210|:443... connected.
ERROR: The certificate of ‘regex101.com’ is not trusted.
ERROR: The certificate of ‘regex101.com’ is not yet activated.
The certificate has not yet been activated
./static/sw.js: No such file or directory
./static/javascriptWorker.js: No such file or directory
./static/vendor.71600b0e.chunk.js: No such file or directory
./static/golangWorker.js: No such file or directory
./static/english.json: No such file or directory
./static/golang.js: No such file or directory
./static/bundle.f566b334954e3b444def.css: No such file or directory
./static/bundle.f566b334954e3b444def.css.map: No such file or directory
```

**Comment by chillyshackk** [comment]
@dragokas if these are no longer found it could mean the web site has changed. I haven't used the offline version in quite some time so I do not have the info to update it, sorry.
