### ISSUE TITLE
Relatively long phrase will cause timeout

### ISSUE THREAD

**Issue by LeoLiu1998** [firasdib/Regex101#966]
If I input phrase like "amount" or "in brief", the **regex tester in python section** will cause timeout when processing, while on my computer everything runs fine.

**Comment by firasdib** [comment]
Please post a permalink.

**Comment by LeoLiu1998** [comment]
https://regex101.com/r/8hgWKV/5/

**Comment by LeoLiu1998** [comment]
https://regex101.com/r/8hgWKV/5/

**Comment by firasdib** [comment]
Thats because your regex is ineffective. I increased the timeout on my PC and saw the following:

<img width="219" alt="screen shot 2018-03-05 at 17 47 07" src="https://user-images.githubusercontent.com/1335165/36987696-44c59752-209d-11e8-90c0-8b4de477d5b9.png">

The PCRE engine is a bit more efficient, which is why you don't notice the error there. It could be that my implementation of the python engine is incorrect, but I fail to see where right now.

**Comment by OlegBrony** [comment]
i have timeout after 2 seconds.

**Comment by firasdib** [comment]
I've fixed the python implementation, this should work better now.
