### ISSUE TITLE
Match Information should show empty groups for python

### ISSUE THREAD

**Issue by sr105** [firasdib/Regex101#978]
If you run the following Python regular expressions on regex101.com, it will not show you the empty groups, but Python will return them. The site should match the output of Python.

[Time elapses] I figured it out. If a group returns `None` in Python, the site omits the group from the Match Information, but if the group is an empty string, it will be shown. The difference came down to the following `(pattern?) ==> ''` and `(pattern)? ==> None`.

I found this very confusing. I think the site should show the None's in some manner.

Try this one: https://regex101.com/r/oDgaWO/1

Regex:

    ^(a)(b)?(c?)(d)$

TestString:

    ad

Output:

```
Match 1
--
Full match | 0-2 | `ad`
Group 1. | 0-1 | `a`
Group 3. | 1-1 | ``
Group 4. | 1-2 | `d`
```
The second group returns None and is omitted while the third group will return an empty string and be displayed.

```
Python 3.6.2 (default, Jul 25 2017, 21:35:45) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> re.match(r'^(a)(b)?(c?)(d)$', 'ad').groups()
('a', None, '', 'd')
```

**Comment by firasdib** [comment]
Non participating groups are by default not included.

Thoughts @Zarthus @nhahtdh @OnlineCop @working-name @TWiStErRob

**Comment by TWiStErRob** [comment]
After the first encounter and some investigation it should be obvious that non-participating groups are null, not `""`, but that could a lot of time wasted.
How about `Group 2. | no match |` or if you have positional info `Group 2. | 1 - 1 | no match`?

**Comment by Doqnach** [comment]
I think @TWiStErRob suggestion is good, because you can of course also have zero-length actual matches. This makes the difference more clear between no-match and zero-length-match. It has to be language agnostic so it needs a fix that not only works for Python I feel. That, or you make it dependent on flavour selection but that make it more time intensive to create.

**Comment by firasdib** [comment]
This is the problem with that approach: https://regex101.com/r/oN4Tva/1

Do you see how the match information is quite condensed? If we were to implement @TWiStErRob suggested behavior, there would be 4 entries for each match in the match info box that would show nothing.

**Comment by TWiStErRob** [comment]
I guess it depends on what you're using the site for: for text processing only the current behavior is better, you don't care about code workings, but if you want to program against, it's a must-know which one may be null. A dropdown menu on the match information header with a checkbox option? Like delimiters or flags, or first just release everywhere and see if people complain.

**Comment by Doqnach** [comment]
An option for "show non-matched groups" could provide both behaviours. But how are you going to tell users it exists seeing as they even now often overlook the settings page (myself included in the past I will add)?
An eye icon next to the export button?

**Comment by TWiStErRob** [comment]
"A dropdown menu on the match information header", that could also contain the export button. It's better to have the option ready in context rather than hidden in Settings. It's more discoverable.

I also think that the default should change to show it, and the option could be turned off, so discovery is only needed for people who are annoyed by it, in which case one would definitely look at the menu button nearby.

**Comment by firasdib** [comment]
This is the first complaint I've gotten on this, ever. Perhaps its a non-issue?

**Comment by TWiStErRob** [comment]
I've noticed it as well when I used the site for real, just didn't complain, because I spent 30 mins / hour debugging what's going on (in my app) and then I understood what's going on and why the matches are not shown as `""`.

**Comment by OnlineCop** [comment]
Sorry for not responding sooner. Just pulled a 28-hour work shift and didn't see all the commotion. I think the current implementation of showing nothing for a `null` makes as much sense as having `no match` fill up the match info area. If there were some kind of "condensed" vs "overwhelming firehose of info" toggle, I guess that we could show all the non-matches. It just seems like real estate clutter to me, especially considering that people use the site on mobile devices.

**Comment by working-name** [comment]
To me it's ... _normal_ for there to be differences in how programming languages implement this; for example, in JS you get an undefined array member while in PHP you get a blank array member.

That's why I never looked at this as an incongruence per flavor but rather as a visual representation of the two cases:

- group 2 can exist or not (whole group is optional)
- group 3 must exist but can be blank or not (only contents are optional)

Personally I don't see a need to mirror the programming language's behavior per flavor at this time, since it doesn't seem to be a widespread issue that affects many users.

**Comment by Zarthus** [comment]
I'm indifferent about this whole thing.

**Comment by sr105** [comment]
Perhaps the no-matches can be initially hidden with a clickable message in the results indicating some non-matching groups were not shown, etc.? It could be a (red?) exclamation point next to the "Export" icon with a tooltip that gives the message.

**Comment by firasdib** [comment]
There is an option in the settings to include non participating groups. That should resolve this.
