### ISSUE TITLE
Allow better version managing.

### ISSUE THREAD

**Issue by eToThePi-i** [firasdib/Regex101#982]
**Duplicate of ["As a user, I want a clean list of my Regex's, devoid of historic versions."](https://github.com/firasdib/Regex101/issues/809) (issue 809)**

~~Saving over the previous version of a regex would be nice to have. When I'm iterating a regex, I may make one tiny mistake, and then I have two separate regex saved in my history.~~

~~Also, deleting previous regex from version history would be nice, or at least allowing the ability to decouple separate versions.~~

**Comment by OnlineCop** [comment]
This is why we allow users to fork and delete old regexes. What happens if a 3rd party helps someone else on their regex (which is usually the case)? Can the original author (the one who saved revision /1) modify the 3rd-party's change? Can the 3rd party who supplied a later revision modify that same revision? Do either the owner or the 3rd party need to be logged in to make the change (currently, anonymous users can create, save, and update regexes on the site)?

**Comment by eToThePi-i** [comment]
I acknowledge the concerns with my suggestions. I will revise them accordingly.

**Comment by eToThePi-i** [comment]
@OnlineCop I just realized, this is a duplicate of ["As a user, I want a clean list of my Regex's, devoid of historic versions. "](https://github.com/firasdib/Regex101/issues/809). It should be marked as a duplicate and closed as such.

**Comment by Zarthus** [comment]
Marked as duplicate by the user, closing.
